use ratatui::{prelude::*, widgets::*};

pub struct HelpCategory {
    pub name: &'static str,
    pub lines: &'static [&'static str],
}

pub const HELP_CATEGORIES: &[HelpCategory] = &[
    HelpCategory {
        name: "NAVIGATION & EDITING",
        lines: &[
            "",
            "# COMMAND NAMING CONVENTION",
            "  PREFIX.SUFFIX - CANONICAL FORM",
            "  EXAMPLES: POSC.FREQ, FILT.CUT, ENV.ATK",
            "  SHORT FORMS REMAIN AS ALIASES (PF, FC, AD)",
            "  USE WHICHEVER FORM YOU PREFER",
            "",
            "# NAVIGATION",
            "  [ ]           CYCLE PAGES",
            "  ESC           TOGGLE HELP",
            "  F1-F8         SCRIPT 1-8",
            "  F9            LIVE PAGE",
            "  F10           METRO PAGE",
            "  F11           INIT PAGE",
            "  F12           PATTERN PAGE",
            "",
            "# EDITING (SCRIPT PAGES)",
            "  UP/DOWN       SELECT LINE",
            "  ENTER         SAVE LINE",
            "  CTRL+D        DUPLICATE LINE",
            "  CTRL+K        DELETE LINE",
            "  CTRL+C        COPY LINE",
            "  CTRL+X        CUT LINE",
            "  CTRL+V        PASTE LINE",
            "  CTRL+L/R      WORD MOVEMENT",
            "",
            "# TRIGGER & VOLUME",
            "  TR                 TRIGGER VOICE",
            "  OUT.VOL / VOL 0-1  MASTER VOLUME",
            "  SLEW.ALL <MS>      PARAM SLEW TIME (0-10000)",
            "  SLEW <P> <MS>      PER-PARAM SLEW TIME",
            "  RST                RESET TO DEFAULTS",
            "  Q/QUIT/EXIT        QUIT APPLICATION",
            "",
            "# REPL UTILITIES",
            "  CLEAR         CLEAR OUTPUT HISTORY",
            "  DEBUG <0-2>   SET VERBOSITY LEVEL",
            "  DEBUG 0       SILENT (ERRORS ONLY)",
            "  DEBUG 1       IMPORTANT (METRO, PRINT)",
            "  DEBUG 2       VERBOSE (ALL PARAMS)",
            "  PRINT \"TEXT\"  OUTPUT LITERAL STRING",
            "  PRINT <EXPR>  EVALUATE & PRINT",
            "  EXAMPLE: PRINT A, PRINT ADD 1 2",
            "",
        ],
    },
    HelpCategory {
        name: "VARIABLES & MATH",
        lines: &[
            "",
            "# VARIABLES",
            "  A B C D       GLOBAL ACCUMULATORS",
            "  X Y Z T       GLOBAL ACCUMULATORS",
            "  J K           PER-SCRIPT LOCAL VARS",
            "  I             LOOP COUNTER (IN L)",
            "  EXAMPLE: A 100 (SET), PF A (USE)",
            "",
            "# MATH (COMMAND & EXPRESSION)",
            "  ADD/+ <A> <B>   ADD",
            "  SUB/- <A> <B>   SUBTRACT",
            "  MUL/* <A> <B>   MULTIPLY",
            "  DIV// <A> <B>   DIVIDE",
            "  MOD/% <A> <B>   MODULO",
            "  MAP <V> <I1> <I2> <O1> <O2>",
            "    MAP VALUE FROM INPUT RANGE TO OUTPUT",
            "  EXAMPLE: PF MAP A 0 127 200 2000",
            "",
            "# RANDOM",
            "  RND <MAX>        0 TO MAX",
            "  RRND <MIN> <MAX> MIN TO MAX",
            "  TOSS             COIN FLIP (0/1)",
            "  EITH <A> <B>     RANDOM CHOICE A OR B",
            "  TOG <A> <B>      ALTERNATE BETWEEN A AND B",
            "",
            "# NOTE/PITCH",
            "  N <SEMI>      SEMITONES TO HZ",
            "  N 0 = C3 (131 HZ)",
            "  N 12 = C4, N 21 = A4 (440)",
            "  EXAMPLE: PF N 12, PF N ADD A 7",
            "",
        ],
    },
    HelpCategory {
        name: "CONTROL FLOW",
        lines: &[
            "",
            "# CONTROL FLOW (PRE OPERATORS)",
            "  IF <X>: <CMD>        IF X != 0 (TRUTHY)",
            "  IF <COND>: <CMD>     WITH COMPARISON",
            "  ELIF <COND>: <CMD>   ELSE-IF",
            "  ELSE: <CMD>          ELSE BRANCH",
            "  PROB <0-100>: <CMD>  PROBABILITY %",
            "  EV <N>: <CMD>        EVERY NTH TICK",
            "  SKIP <N>: <CMD>      SKIP EVERY NTH",
            "  L <S> <E>: <CMDS>    LOOP S TO E",
            "  CMD1; CMD2           SUB-COMMANDS",
            "",
            "# COMPARISONS (RETURN 1/0)",
            "  EZ <X>       X == 0 (EQUALS ZERO)",
            "  NZ <X>       X != 0 (NOT ZERO)",
            "  EQ <A> <B>   A == B",
            "  NE <A> <B>   A != B",
            "  GT <A> <B>   A > B",
            "  LT <A> <B>   A < B",
            "  GTE <A> <B>  A >= B",
            "  LTE <A> <B>  A <= B",
            "  ALSO: > < >= <= == != IN COND",
            "",
            "# SCENES",
            "  SAVE <NAME>   SAVE SCRIPTS+PATTERNS",
            "  LOAD <NAME>   LOAD SCENE",
            "  SCENES        LIST SAVED SCENES",
            "  DELETE <NAME> DELETE SCENE",
            "",
            "# RECORDING",
            "  REC           START RECORDING (WAV)",
            "  REC.STOP      STOP RECORDING",
            "  REC.PATH <P>  SET PATH PREFIX",
            "",
        ],
    },
    HelpCategory {
        name: "PATTERNS",
        lines: &[
            "",
            "# PATTERNS (WORKING - P.N)",
            "  P.N           GET WORKING PATTERN",
            "  P.N <0-5>     SET WORKING PATTERN",
            "  P.L / P.L <N> GET/SET LENGTH",
            "  P.I / P.I <N> GET/SET INDEX",
            "  P.HERE        VALUE AT INDEX",
            "  P.NEXT        ADVANCE, GET VALUE",
            "  P.PREV        REVERSE, GET VALUE",
            "  P <I> / P <I> <V>  GET/SET AT INDEX",
            "",
            "# PATTERNS (EXPLICIT - PN)",
            "  PN.L <P> / PN.L <P> <N>  LENGTH",
            "  PN.I <P> / PN.I <P> <N>  INDEX",
            "  PN.HERE <P>              VALUE",
            "  PN.NEXT <P>              ADVANCE",
            "  PN.PREV <P>              REVERSE",
            "  PN <P> <I> / PN <P> <I> <V>",
            "",
            "# COUNTERS",
            "  N1-N4         READ VALUE + AUTO-INCREMENT",
            "  N1.MIN <N>    SET MINIMUM (DEFAULT 0)",
            "  N1.MAX <N>    SET MAXIMUM (WRAPS BACK)",
            "  N1.RST        RESET TO MIN",
            "  EXAMPLE: N1.MIN 10; N1.MAX 14",
            "  CYCLES: 10, 11, 12, 13, 14, 10...",
            "",
        ],
    },
    HelpCategory {
        name: "OSCILLATORS & FM",
        lines: &[
            "",
            "# OSCILLATORS",
            "  POSC.FREQ / PF <HZ>    PRIMARY FREQ (20-20000)",
            "  POSC.WAVE / PW <0-2>   PRIMARY WAVE (SIN/TRI/SAW)",
            "  MOSC.FREQ / MF <HZ>    MOD FREQ (20-20000)",
            "  MOSC.WAVE / MW <0-2>   MOD WAVE (SIN/TRI/SAW)",
            "",
            "# FM SYNTHESIS",
            "  MBUS.FM / FM <0-16383> FM INDEX",
            "  FMEV.AMT / FA <0-16383> FM ENV AMOUNT",
            "  FMEV.DEC / FD <MS>     FM ENV DECAY",
            "",
            "# FEEDBACK FM",
            "  MOSC.FB / FB <0-16383>  FEEDBACK AMOUNT",
            "  MOSC.FBA / FBA <0-16383> FEEDBACK ENV AMOUNT",
            "  MOSC.FBD / FBD <MS>     FEEDBACK ENV DECAY",
            "",
            "# DISCONTINUITY",
            "  DISC.AMT / DC <0-16383> DISCONTINUITY AMOUNT",
            "  DENV.AMT / DA <0-16383> DC ENV AMOUNT",
            "  DENV.DEC / DD <MS>      DC ENV DECAY",
            "  DISC.MODE / DM <0-6>    MODE (FOLD/TANH/...)",
            "",
            "# LO-FI",
            "  LOFI.BIT / LB <1-16>    BIT DEPTH (16=CLEAN)",
            "  LOFI.SMP / LS <100-48K> SAMPLE RATE (HZ)",
            "  LOFI.MIX / LM <0-16383> LO-FI MIX",
            "",
            "# MOD BUS",
            "  MBUS.AMT / MB <0-16383> MOD BUS AMOUNT",
            "  MBUS.TRK / TK <0-16383> TRACKING AMOUNT",
            "  ROUT.MP / MP <0|1>      MOD -> PRIMARY FREQ",
            "  ROUT.MD / MD <0|1>      MOD -> DISCONTINUITY",
            "  ROUT.MT / MT <0|1>      MOD -> TRACKING",
            "  ROUT.MA / MA <0|1>      MOD -> AMPLITUDE",
            "",
            "# MIX",
            "  MBUS.MIX / MX <0-16383> MIX AMOUNT",
            "  MBUS.MMX / MM <0|1>     MOD BUS -> MIX",
            "  MBUS.EMX / ME <0|1>     ENVELOPE -> MIX",
            "",
        ],
    },
    HelpCategory {
        name: "ENVELOPES",
        lines: &[
            "",
            "# ENVELOPES",
            "  ENV.ATK <MS>  GLOBAL ENV ATTACK (1-10000)",
            "  ENV.DEC <MS>  GLOBAL ENV DECAY (1-10000)",
            "  ENV.CRV <V>   GLOBAL ENV CURVE (-8 TO 8)",
            "  ENV.MODE <M>  GLOBAL ENV MODE (0=AD 1=ASR 2=ADSR)",
            "  GATE <MS>     GLOBAL GATE DURATION (0-10000, 0=INSTANT)",
            "",
            "# PER-ENVELOPE OVERRIDES",
            "  AENV.ATK/DEC/CRV/MODE/GATE - AMP ENVELOPE",
            "  PENV.ATK/DEC/CRV/MODE/GATE - PITCH ENVELOPE",
            "  FMEV.ATK/DEC/CRV/MODE/GATE - FM ENVELOPE",
            "  DENV.ATK/DEC/CRV/MODE/GATE - DISCONTINUITY ENV",
            "  FBEV.ATK/DEC/CRV/MODE/GATE - FEEDBACK ENV",
            "  FLEV.ATK/DEC/CRV/MODE/GATE - FILTER ENV",
            "",
            "# LEGACY SHORT FORMS (ALIASES)",
            "  AENV.DEC / AD <MS>  AMP DECAY",
            "  PENV.DEC / PD <MS>  PITCH DECAY",
            "  PENV.AMT / PA <0-16> PITCH ENV AMOUNT",
            "",
        ],
    },
    HelpCategory {
        name: "FILTER & EFFECTS",
        lines: &[
            "",
            "# SVF FILTER",
            "  FILT.CUT / FC <HZ>      CUTOFF FREQ (20-20000)",
            "  FILT.RES / FQ <0-16383> RESONANCE",
            "  FILT.TYP / FT <0-3>     TYPE (LP/HP/BP/NOTCH)",
            "  FILT.ENV / FE <0-16383> FILTER ENV AMOUNT",
            "  FLEV.DEC / FED <MS>     FILTER ENV DECAY",
            "  FILT.KEY / FK <0-16383> KEY TRACKING",
            "  ROUT.MF / MF.F <0-1>    MOD BUS -> FILTER",
            "",
            "# RING MOD",
            "  RING.FRQ / RGF <20-2000> RING MOD FREQ (HZ)",
            "  RING.WAV / RGW <0-3>     WAVEFORM (SIN/TRI/SAW/SQR)",
            "  RING.MIX / RGM <0-16383> RING MOD MIX",
            "",
            "# COMB RESONATOR",
            "  RESO.FRQ / RF <HZ>      RESONATOR FREQ",
            "  RESO.DEC / RD <MS>      RESONATOR DECAY",
            "  RESO.MIX / RM <0-16383> RESONATOR MIX",
            "  RESO.KEY / RK <0-16383> RESONATOR KEY TRACK",
            "",
            "# COMPRESSOR",
            "  COMP.THR / CT <0-16383> THRESHOLD",
            "  COMP.RAT / CR <1-20>    RATIO",
            "  COMP.ATK / CA <1-500>   ATTACK (MS)",
            "  COMP.REL / CL <10-2000> RELEASE (MS)",
            "  COMP.MKP / CM <0-16383> MAKEUP GAIN",
            "",
            "# PAN",
            "  OUT.PAN / PAN <-16K-16K> STEREO POSITION",
            "",
            "# BEAT REPEAT",
            "  BR.ACT <0|1>  ENABLE BEAT REPEAT",
            "  BR.LEN <0-7>  LOOP DIV (0=1/16...7=8X)",
            "  BR.REV <0|1>  REVERSE PLAYBACK",
            "  BR.WIN <1-50> WINDOW SIZE (MS)",
            "  BR.MIX <0-16383> BEAT REPEAT MIX",
            "",
            "# PITCH SHIFT",
            "  PS.MODE <0|1>   MODE (NORMAL/GRANULAR)",
            "  PS.SEMI <-24-24> SHIFT (SEMITONES)",
            "  PS.GRAIN <5-100> GRAIN SIZE (MS)",
            "  PS.MIX <0-16383> PITCH SHIFT MIX",
            "  PS.TARG <0|1>    TARGET (INPUT/OUTPUT)",
            "",
            "# 3-BAND EQ",
            "  EQ.LOW / EL <-24-24>    LOW SHELF (DB)",
            "  EQ.MID / EM <-24-24>    MID PEAK (DB)",
            "  EQ.FRQ / EF <200-8000>  MID FREQ (HZ)",
            "  EQ.Q <0.1-10>           MID Q",
            "  EQ.HI / EH <-24-24>     HIGH SHELF (DB)",
            "",
        ],
    },
    HelpCategory {
        name: "DELAY & REVERB",
        lines: &[
            "",
            "# STEREO DELAY",
            "  DLY.TIME / DT <MS>      DELAY TIME (1-2000)",
            "  DLY.FB / DF <0-16383>   DELAY FEEDBACK",
            "  DLY.LP / DLP <HZ>       DELAY LP FILTER",
            "  DLY.WET / DW <0-16383>  DELAY WET MIX",
            "  DLY.SYN / DS <0-16383>  DELAY STEREO WIDTH",
            "",
            "# DELAY ROUTING",
            "  DLY.MODE / D.MODE <0-2> BYPASS/INSERT/SEND",
            "  DLY.TAIL / D.TAIL <0-2> CUT/RING/FREEZE",
            "",
            "# PLATE REVERB",
            "  REV.DEC / RV <0-16383>  REVERB DECAY",
            "  REV.PRE / RP <MS>       REVERB PRE-DELAY",
            "  REV.DMP / RH <0-16383>  REVERB DAMPING (HI)",
            "  REV.WET / RW <0-16383>  REVERB WET MIX",
            "",
            "# REVERB ROUTING",
            "  REV.MODE / R.MODE <0-2> BYPASS/INSERT/SEND",
            "  REV.TAIL / R.TAIL <0-2> CUT/RING/FREEZE",
            "",
        ],
    },
    HelpCategory {
        name: "METRO & SCRIPTS",
        lines: &[
            "",
            "# METRO",
            "  M             SHOW INTERVAL",
            "  M <MS>        SET INTERVAL",
            "  M.BPM <BPM>   SET BPM",
            "  M.ACT <0|1>   START/STOP",
            "  M.SCRIPT <1-8>  SCRIPT FOR METRO",
            "",
            "# SCRIPTS",
            "  SCRIPT <1-8>  EXECUTE STORED SCRIPT",
            "",
        ],
    },
    HelpCategory {
        name: "SYSTEM",
        lines: &[
            "",
            "# EXPRESSIONS",
            "  ALL NUMERIC ARGS ACCEPT EXPRESSIONS:",
            "  PF N ADD A 7",
            "  DC MUL PN.NEXT 0 100",
            "  A RRND 0 127",
            "",
        ],
    },
];

pub const HELP_LINES: &[&str] = &[
    "",
    "# COMMAND NAMING CONVENTION",
    "  PREFIX.SUFFIX - CANONICAL FORM",
    "  EXAMPLES: POSC.FREQ, FILT.CUT, ENV.ATK",
    "  SHORT FORMS REMAIN AS ALIASES (PF, FC, AD)",
    "  USE WHICHEVER FORM YOU PREFER",
    "",
    "# NAVIGATION",
    "  [ ]           CYCLE PAGES",
    "  ESC           TOGGLE HELP",
    "  F1-F8         SCRIPT 1-8",
    "  F9            LIVE PAGE",
    "  F10           METRO PAGE",
    "  F11           INIT PAGE",
    "  F12           PATTERN PAGE",
    "",
    "# EDITING (SCRIPT PAGES)",
    "  UP/DOWN       SELECT LINE",
    "  ENTER         SAVE LINE",
    "  CTRL+D        DUPLICATE LINE",
    "  CTRL+K        DELETE LINE",
    "  CTRL+C        COPY LINE",
    "  CTRL+X        CUT LINE",
    "  CTRL+V        PASTE LINE",
    "  CTRL+L/R      WORD MOVEMENT",
    "",
    "# TRIGGER & VOLUME",
    "  TR                 TRIGGER VOICE",
    "  OUT.VOL / VOL 0-1  MASTER VOLUME",
    "  SLEW.ALL <MS>      PARAM SLEW TIME (0-10000)",
    "  SLEW <P> <MS>      PER-PARAM SLEW TIME",
    "  RST                RESET TO DEFAULTS",
    "  Q/QUIT/EXIT        QUIT APPLICATION",
    "",
    "# REPL UTILITIES",
    "  CLEAR         CLEAR OUTPUT HISTORY",
    "  DEBUG <0-2>   SET VERBOSITY LEVEL",
    "  DEBUG 0       SILENT (ERRORS ONLY)",
    "  DEBUG 1       IMPORTANT (METRO, PRINT)",
    "  DEBUG 2       VERBOSE (ALL PARAMS)",
    "  PRINT \"TEXT\"  OUTPUT LITERAL STRING",
    "  PRINT <EXPR>  EVALUATE & PRINT",
    "  EXAMPLE: PRINT A, PRINT ADD 1 2",
    "",
    "# VARIABLES",
    "  A B C D       GLOBAL ACCUMULATORS",
    "  X Y Z T       GLOBAL ACCUMULATORS",
    "  J K           PER-SCRIPT LOCAL VARS",
    "  I             LOOP COUNTER (IN L)",
    "  EXAMPLE: A 100 (SET), PF A (USE)",
    "",
    "# MATH (COMMAND & EXPRESSION)",
    "  ADD/+ <A> <B>   ADD",
    "  SUB/- <A> <B>   SUBTRACT",
    "  MUL/* <A> <B>   MULTIPLY",
    "  DIV// <A> <B>   DIVIDE",
    "  MOD/% <A> <B>   MODULO",
    "  MAP <V> <I1> <I2> <O1> <O2>",
    "    MAP VALUE FROM INPUT RANGE TO OUTPUT",
    "  EXAMPLE: PF MAP A 0 127 200 2000",
    "",
    "# RANDOM",
    "  RND <MAX>        0 TO MAX",
    "  RRND <MIN> <MAX> MIN TO MAX",
    "  TOSS             COIN FLIP (0/1)",
    "  EITH <A> <B>     RANDOM CHOICE A OR B",
    "  TOG <A> <B>      ALTERNATE BETWEEN A AND B",
    "",
    "# NOTE/PITCH",
    "  N <SEMI>      SEMITONES TO HZ",
    "  N 0 = C3 (131 HZ)",
    "  N 12 = C4, N 21 = A4 (440)",
    "  EXAMPLE: PF N 12, PF N ADD A 7",
    "",
    "# CONTROL FLOW (PRE OPERATORS)",
    "  IF <X>: <CMD>        IF X != 0 (TRUTHY)",
    "  IF <COND>: <CMD>     WITH COMPARISON",
    "  ELIF <COND>: <CMD>   ELSE-IF",
    "  ELSE: <CMD>          ELSE BRANCH",
    "  PROB <0-100>: <CMD>  PROBABILITY %",
    "  EV <N>: <CMD>        EVERY NTH TICK",
    "  SKIP <N>: <CMD>      SKIP EVERY NTH",
    "  L <S> <E>: <CMDS>    LOOP S TO E",
    "  CMD1; CMD2           SUB-COMMANDS",
    "",
    "# COMPARISONS (RETURN 1/0)",
    "  EZ <X>       X == 0 (EQUALS ZERO)",
    "  NZ <X>       X != 0 (NOT ZERO)",
    "  EQ <A> <B>   A == B",
    "  NE <A> <B>   A != B",
    "  GT <A> <B>   A > B",
    "  LT <A> <B>   A < B",
    "  GTE <A> <B>  A >= B",
    "  LTE <A> <B>  A <= B",
    "  ALSO: > < >= <= == != IN COND",
    "",
    "# SCENES",
    "  SAVE <NAME>   SAVE SCRIPTS+PATTERNS",
    "  LOAD <NAME>   LOAD SCENE",
    "  SCENES        LIST SAVED SCENES",
    "  DELETE <NAME> DELETE SCENE",
    "",
    "# RECORDING",
    "  REC           START RECORDING (WAV)",
    "  REC.STOP      STOP RECORDING",
    "  REC.PATH <P>  SET PATH PREFIX",
    "",
    "# BEAT REPEAT",
    "  BR.ACT <0|1>  ENABLE BEAT REPEAT",
    "  BR.LEN <0-7>  LOOP DIV (0=1/16...7=8X)",
    "  BR.REV <0|1>  REVERSE PLAYBACK",
    "  BR.WIN <1-50> WINDOW SIZE (MS)",
    "  BR.MIX <0-16383> BEAT REPEAT MIX",
    "",
    "# PITCH SHIFT",
    "  PS.MODE <0|1>   MODE (NORMAL/GRANULAR)",
    "  PS.SEMI <-24-24> SHIFT (SEMITONES)",
    "  PS.GRAIN <5-100> GRAIN SIZE (MS)",
    "  PS.MIX <0-16383> PITCH SHIFT MIX",
    "  PS.TARG <0|1>    TARGET (INPUT/OUTPUT)",
    "",
    "# OSCILLATORS",
    "  POSC.FREQ / PF <HZ>    PRIMARY FREQ (20-20000)",
    "  POSC.WAVE / PW <0-2>   PRIMARY WAVE (SIN/TRI/SAW)",
    "  MOSC.FREQ / MF <HZ>    MOD FREQ (20-20000)",
    "  MOSC.WAVE / MW <0-2>   MOD WAVE (SIN/TRI/SAW)",
    "",
    "# FM SYNTHESIS",
    "  MBUS.FM / FM <0-16383> FM INDEX",
    "  FMEV.AMT / FA <0-16383> FM ENV AMOUNT",
    "  FMEV.DEC / FD <MS>     FM ENV DECAY",
    "",
    "# FEEDBACK FM",
    "  MOSC.FB / FB <0-16383>  FEEDBACK AMOUNT",
    "  MOSC.FBA / FBA <0-16383> FEEDBACK ENV AMOUNT",
    "  MOSC.FBD / FBD <MS>     FEEDBACK ENV DECAY",
    "",
    "# DISCONTINUITY",
    "  DISC.AMT / DC <0-16383> DISCONTINUITY AMOUNT",
    "  DENV.AMT / DA <0-16383> DC ENV AMOUNT",
    "  DENV.DEC / DD <MS>      DC ENV DECAY",
    "  DISC.MODE / DM <0-6>    MODE (FOLD/TANH/...)",
    "",
    "# LO-FI",
    "  LOFI.BIT / LB <1-16>    BIT DEPTH (16=CLEAN)",
    "  LOFI.SMP / LS <100-48K> SAMPLE RATE (HZ)",
    "  LOFI.MIX / LM <0-16383> LO-FI MIX",
    "",
    "# SVF FILTER",
    "  FILT.CUT / FC <HZ>      CUTOFF FREQ (20-20000)",
    "  FILT.RES / FQ <0-16383> RESONANCE",
    "  FILT.TYP / FT <0-3>     TYPE (LP/HP/BP/NOTCH)",
    "  FILT.ENV / FE <0-16383> FILTER ENV AMOUNT",
    "  FLEV.DEC / FED <MS>     FILTER ENV DECAY",
    "  FILT.KEY / FK <0-16383> KEY TRACKING",
    "  ROUT.MF / MF.F <0-1>    MOD BUS -> FILTER",
    "",
    "# RING MOD",
    "  RING.FRQ / RGF <20-2000> RING MOD FREQ (HZ)",
    "  RING.WAV / RGW <0-3>     WAVEFORM (SIN/TRI/SAW/SQR)",
    "  RING.MIX / RGM <0-16383> RING MOD MIX",
    "",
    "# COMB RESONATOR",
    "  RESO.FRQ / RF <HZ>      RESONATOR FREQ",
    "  RESO.DEC / RD <MS>      RESONATOR DECAY",
    "  RESO.MIX / RM <0-16383> RESONATOR MIX",
    "  RESO.KEY / RK <0-16383> RESONATOR KEY TRACK",
    "",
    "# COMPRESSOR",
    "  COMP.THR / CT <0-16383> THRESHOLD",
    "  COMP.RAT / CR <1-20>    RATIO",
    "  COMP.ATK / CA <1-500>   ATTACK (MS)",
    "  COMP.REL / CL <10-2000> RELEASE (MS)",
    "  COMP.MKP / CM <0-16383> MAKEUP GAIN",
    "",
    "# PAN",
    "  OUT.PAN / PAN <-16K-16K> STEREO POSITION",
    "",
    "# ENVELOPES",
    "  ENV.ATK <MS>  GLOBAL ENV ATTACK (1-10000)",
    "  ENV.DEC <MS>  GLOBAL ENV DECAY (1-10000)",
    "  ENV.CRV <V>   GLOBAL ENV CURVE (-8 TO 8)",
    "  ENV.MODE <M>  GLOBAL ENV MODE (0=AD 1=ASR 2=ADSR)",
    "  GATE <MS>     GLOBAL GATE DURATION (0-10000, 0=INSTANT)",
    "",
    "# PER-ENVELOPE OVERRIDES",
    "  AENV.ATK/DEC/CRV/MODE/GATE - AMP ENVELOPE",
    "  PENV.ATK/DEC/CRV/MODE/GATE - PITCH ENVELOPE",
    "  FMEV.ATK/DEC/CRV/MODE/GATE - FM ENVELOPE",
    "  DENV.ATK/DEC/CRV/MODE/GATE - DISCONTINUITY ENV",
    "  FBEV.ATK/DEC/CRV/MODE/GATE - FEEDBACK ENV",
    "  FLEV.ATK/DEC/CRV/MODE/GATE - FILTER ENV",
    "",
    "# LEGACY SHORT FORMS (ALIASES)",
    "  AENV.DEC / AD <MS>  AMP DECAY",
    "  PENV.DEC / PD <MS>  PITCH DECAY",
    "  PENV.AMT / PA <0-16> PITCH ENV AMOUNT",
    "",
    "# MOD BUS",
    "  MBUS.AMT / MB <0-16383> MOD BUS AMOUNT",
    "  MBUS.TRK / TK <0-16383> TRACKING AMOUNT",
    "  ROUT.MP / MP <0|1>      MOD -> PRIMARY FREQ",
    "  ROUT.MD / MD <0|1>      MOD -> DISCONTINUITY",
    "  ROUT.MT / MT <0|1>      MOD -> TRACKING",
    "  ROUT.MA / MA <0|1>      MOD -> AMPLITUDE",
    "",
    "# MIX",
    "  MBUS.MIX / MX <0-16383> MIX AMOUNT",
    "  MBUS.MMX / MM <0|1>     MOD BUS -> MIX",
    "  MBUS.EMX / ME <0|1>     ENVELOPE -> MIX",
    "",
    "# STEREO DELAY",
    "  DLY.TIME / DT <MS>      DELAY TIME (1-2000)",
    "  DLY.FB / DF <0-16383>   DELAY FEEDBACK",
    "  DLY.LP / DLP <HZ>       DELAY LP FILTER",
    "  DLY.WET / DW <0-16383>  DELAY WET MIX",
    "  DLY.SYN / DS <0-16383>  DELAY STEREO WIDTH",
    "",
    "# DELAY ROUTING",
    "  DLY.MODE / D.MODE <0-2> BYPASS/INSERT/SEND",
    "  DLY.TAIL / D.TAIL <0-2> CUT/RING/FREEZE",
    "",
    "# 3-BAND EQ",
    "  EQ.LOW / EL <-24-24>    LOW SHELF (DB)",
    "  EQ.MID / EM <-24-24>    MID PEAK (DB)",
    "  EQ.FRQ / EF <200-8000>  MID FREQ (HZ)",
    "  EQ.Q <0.1-10>           MID Q",
    "  EQ.HI / EH <-24-24>     HIGH SHELF (DB)",
    "",
    "# PLATE REVERB",
    "  REV.DEC / RV <0-16383>  REVERB DECAY",
    "  REV.PRE / RP <MS>       REVERB PRE-DELAY",
    "  REV.DMP / RH <0-16383>  REVERB DAMPING (HI)",
    "  REV.WET / RW <0-16383>  REVERB WET MIX",
    "",
    "# REVERB ROUTING",
    "  REV.MODE / R.MODE <0-2> BYPASS/INSERT/SEND",
    "  REV.TAIL / R.TAIL <0-2> CUT/RING/FREEZE",
    "",
    "# METRO",
    "  M             SHOW INTERVAL",
    "  M <MS>        SET INTERVAL",
    "  M.BPM <BPM>   SET BPM",
    "  M.ACT <0|1>   START/STOP",
    "  M.SCRIPT <1-8>  SCRIPT FOR METRO",
    "",
    "# SCRIPTS",
    "  SCRIPT <1-8>  EXECUTE STORED SCRIPT",
    "",
    "# COUNTERS",
    "  N1-N4         READ VALUE + AUTO-INCREMENT",
    "  N1.MIN <N>    SET MINIMUM (DEFAULT 0)",
    "  N1.MAX <N>    SET MAXIMUM (WRAPS BACK)",
    "  N1.RST        RESET TO MIN",
    "  EXAMPLE: N1.MIN 10; N1.MAX 14",
    "  CYCLES: 10, 11, 12, 13, 14, 10...",
    "",
    "# PATTERNS (WORKING - P.N)",
    "  P.N           GET WORKING PATTERN",
    "  P.N <0-5>     SET WORKING PATTERN",
    "  P.L / P.L <N> GET/SET LENGTH",
    "  P.I / P.I <N> GET/SET INDEX",
    "  P.HERE        VALUE AT INDEX",
    "  P.NEXT        ADVANCE, GET VALUE",
    "  P.PREV        REVERSE, GET VALUE",
    "  P <I> / P <I> <V>  GET/SET AT INDEX",
    "",
    "# PATTERNS (EXPLICIT - PN)",
    "  PN.L <P> / PN.L <P> <N>  LENGTH",
    "  PN.I <P> / PN.I <P> <N>  INDEX",
    "  PN.HERE <P>              VALUE",
    "  PN.NEXT <P>              ADVANCE",
    "  PN.PREV <P>              REVERSE",
    "  PN <P> <I> / PN <P> <I> <V>",
    "",
    "# EXPRESSIONS",
    "  ALL NUMERIC ARGS ACCEPT EXPRESSIONS:",
    "  PF N ADD A 7",
    "  DC MUL PN.NEXT 0 100",
    "  A RRND 0 127",
    "",
];

pub fn render_help_page(app: &crate::App, height: usize) -> Paragraph<'static> {
    let help_page = app.help_page;
    let scroll = app.help_scroll;
    let visible = if height > 2 { height - 2 } else { 1 };
    let fg = app.theme.foreground;
    let label = app.theme.label;

    let category = &HELP_CATEGORIES[help_page];
    let category_lines = category.lines;
    let total = category_lines.len();
    let start = scroll.min(total.saturating_sub(visible));

    let lines: Vec<Line> = category_lines
        .iter()
        .skip(start)
        .take(visible)
        .map(|&s| {
            if s.starts_with("# ") {
                let header_text = &s[2..];
                Line::from(Span::styled(
                    format!("  {}", header_text),
                    Style::default().fg(label).add_modifier(Modifier::BOLD)
                ))
            } else {
                Line::from(Span::styled(s, Style::default().fg(fg)))
            }
        })
        .collect();

    let title = format!(
        " HELP: {} ({}/{}) ",
        category.name,
        help_page + 1,
        HELP_CATEGORIES.len()
    );

    Paragraph::new(lines)
        .style(Style::default().bg(app.theme.background).fg(app.theme.foreground))
        .block(
            Block::default()
                .borders(Borders::ALL)
                .border_style(Style::default().fg(app.theme.border))
                .title(title)
                .title_style(Style::default().fg(app.theme.foreground))
        )
}
