use super::help_categories::HelpCategory;

pub const FILTER_EFFECTS: HelpCategory = HelpCategory {
    name: "FILTER & EFFECTS",
    lines: &[
        "",
        "# FILTER",
        "  FILT.CUT / FC <HZ>      CUT (20-20K)",
        "  FILT.RES / FQ <0-16383> RES",
        "  FILT.TYP / FT <0-13>    TYPE",
        "    0=SVF LP  1=SVF HP  2=SVF BP  3=NOTCH",
        "    4=MOOG  5=RES LP  6=RES HP",
        "    7=DFM1 LP  8=DFM1 HP",
        "    9=BMOOG LP  10=BMOOG HP  11=BMOOG BP",
        "    12=SC LP  13=SC HP",
        "  FLEV.AMT / FE <0-16383> ENV AMT",
        "  FLEV.DEC / FED <MS>     ENV DEC",
        "  FILT.KEY / FK <0-16383> KEY TRACK",
        "  MODF.CUT / MFF <0-16383> MOD->CUT AMT",
        "  MODF.RES / MFQ <0-16383> MOD->RES AMT",
        "",
        "# RING MOD",
        "  RING.FRQ / RGF <20-2000> FREQ",
        "  RING.WAV / RGW <0-3>     WAV (SIN/TRI/SAW)",
        "  RING.MIX / RGM <0-16383> MIX",
        "",
        "# COMPRESSOR",
        "  COMP.THR / CT <0-16383> THR",
        "  COMP.RAT / CR <1-20>    RATIO",
        "  COMP.ATK / CA <1-500>   ATK MS",
        "  COMP.REL / CL <10-2000> REL MS",
        "  COMP.MKP / CM <0-16383> MAKEUP",
        "  COMP.AUTO / CAU <0|1>   AUTO MAKEUP",
        "  COMP.MIX / CRMIX <0-16383> DRY/WET",
        "    0=DRY 16383=WET (PARALLEL)",
        "",
        "# PAN",
        "  OUT.PAN / PAN <-16K-16K> STEREO POS",
        "",
        "# PER-VOICE MIXER (GRID.MODE 3)",
        "  VOL.OSC / VO <0-16383>  OSC VOL",
        "  VOL.PLA / VP <0-16383>  PLAITS VOL",
        "  VOL.NOS / VN <0-16383>  NOISE VOL",
        "  VOL.SMP / VS <0-16383>  SAMPLER VOL",
        "  PAN.OSC / PO <-8K-8K>   OSC PAN",
        "  PAN.PLA / PP <-8K-8K>   PLAITS PAN",
        "  PAN.NOS / PNN <-8K-8K>  NOISE PAN",
        "  PAN.SMP / PS <-8K-8K>   SAMPLER PAN",
        "  MUTE.OSC / MO <0|1>     MUTE OSC",
        "  MUTE.PLA / MPL <0|1>    MUTE PLAITS",
        "  MUTE.NOS / MN <0|1>     MUTE NOISE",
        "  MUTE.SMP / MS <0|1>     MUTE SAMPLER",
        "",
        "# BEAT REPEAT",
        "  BR.LEN / BRL <0-7>  DIV (0=1/16...7=8X)",
        "  BR.REV / BRR <0|1>  REVERSE",
        "  BR.WIN / BRW <1-50> WIN MS",
        "  BR.MIX / BRX <0-16383> MIX (ACTIVATES)",
        "",
        "# PITCH SHIFT",
        "  PS.MODE / PSM <0|1>   MODE (NORM/GRAN)",
        "  PS.SEMI / PSS <-24-24> SEMI",
        "  PS.GRAIN / PSG <5-100> GRAIN MS",
        "  PS.MIX / PSX <0-16383> MIX",
        "  PS.TARG / PST <0|1>    TARG (IN/OUT)",
        "",
        "# MICLOUDS GRANULAR",
        "  CL.TRIG / CLTR        TRIGGER GRAINS",
        "  CL.PITCH / CLP <0-16K> PITCH (8K=CTR)",
        "  CL.POS / CLO <0-16K>   BUF POSITION",
        "  CL.SIZE / CLS <0-16K>  GRAIN SIZE",
        "  CL.DENS / CLD <0-16K>  DENSITY",
        "  CL.TEX / CLT <0-16K>   TEXTURE",
        "  CL.WET / CLW <0-16K>   WET MIX",
        "  CL.GAIN / CLG <0-16K>  GAIN (8K=1X)",
        "  CL.SPREAD / CLSP <0-16K> STEREO",
        "  CL.RVB / CLR <0-16K>   INTL REVERB",
        "  CL.FB / CLF <0-16K>    FEEDBACK",
        "  CL.FREEZE / CLFZ <0|1> FREEZE BUF",
        "  CL.MODE / CLM <0-3>    MODE",
        "  CL.LOFI / CLLO <0-16K> LO-FI",
        "  MODES: 0=GRAN 1=PITCH 2=LOOP 3=SPEC",
        "",
        "# 3-BAND EQ",
        "  EQ.LOW / EL <-24-24>    LOW DB",
        "  ELF <20-2000>           LOW SHELF FREQ",
        "  EQ.MID / EM <-24-24>    MID DB",
        "  EQ.FRQ / EF <200-8000>  MID FREQ",
        "  EQ.Q <0.1-10>           MID Q",
        "  EQ.HI / EH <-24-24>     HI DB",
        "  EHF <1000-20000>        HI SHELF FREQ",
        "",
    ],
};

pub const DELAY_REVERB: HelpCategory = HelpCategory {
    name: "DELAY & REVERB",
    lines: &[
        "",
        "# STEREO DELAY",
        "  DLY.TIME / DT <0-16383> TIME (EXP CURVE)",
        "  DLY.SYN / DS <0-1>      0=FREE 1=BPM SYNC",
        "  DLY.FB / DF <0-16383>   FEEDBACK",
        "  DLY.LP / DLP <HZ>       LP FILT",
        "  DLY.WET / DW <0-16383>  WET MIX",
        "",
        "# DELAY ROUTING",
        "  DLY.MODE / D.MODE <0-2> BYP/INS/SND",
        "  DLY.TAIL / D.TAIL <0-2> CUT/RNG/FRZ",
        "",
        "# PLATE REVERB",
        "  REV.DEC / RV <0-16383>  DECAY",
        "  REV.PRE / RP <MS>       PRE-DLY",
        "  REV.DMP / RH <0-16383>  DAMP (HI)",
        "  REV.WET / RW <0-16383>  WET MIX",
        "",
        "# REVERB ROUTING",
        "  REV.MODE / R.MODE <0-2> BYP/INS/SND",
        "  REV.TAIL / R.TAIL <0-2> CUT/RNG/FRZ",
        "",
    ],
};
