pub struct HelpCategory {
    pub name: &'static str,
    pub lines: &'static [&'static str],
}

pub const NAV_EDITING: HelpCategory = HelpCategory {
    name: "NAVIGATION & EDITING",
    lines: &[
        "",
        "# COMMAND NAMING CONVENTION",
        "  PREFIX.SUFFIX - CANONICAL",
        "  EX: POSC.FREQ, FILT.CUT, AENV.ATK",
        "  SHORT FORMS AS ALIAS (PF, FC, AD)",
        "  USE WHICHEVER FORM YOU PREFER",
        "",
        "# NAVIGATION",
        "  [ ]           CYCLE PAGES",
        "  ESC           TOGGLE HELP",
        "",
        "# FUNCTION KEYS (ALL TERMINALS)",
        "  F1-F8         SCRIPT 1-8",
        "  F9            LIVE PAGE",
        "  F10           METRO PAGE",
        "  F11           INIT PAGE",
        "  F12           PATTERN PAGE",
        "",
        "# ALT KEYS (NEED ITERM2 CONFIG)",
        "  ALT+L         LIVE PAGE",
        "  ALT+1 TO 8    SCRIPT 1-8",
        "  ALT+M         METRO PAGE",
        "  ALT+I         INIT PAGE",
        "  ALT+P         PATTERN PAGE",
        "  ALT+S         SCOPE PAGE",
        "  ALT+V         VARIABLES PAGE",
        "  ALT+H         TOGGLE HELP",
        "",
        "# SCRIPT MUTES",
        "  CTRL+SHIFT+1-8  TOGGLE SCRIPT MUTE",
        "  CTRL+SHIFT+M    TOGGLE METRO MUTE",
        "  CTRL+SHIFT+I    TOGGLE INIT MUTE",
        "",
        "# OTHER",
        "  CTRL+Q        QUIT APP",
        "  CTRL+UP/DN    SCROLL REPL",
        "  TAB           LIVE / GRID VIEW",
        "  CTRL+G        CYCLE GRID MODE 0-5",
        "",
        "# SEARCH",
        "  CTRL+F        SEARCH MODE",
        "  ENTER         NEXT MATCH",
        "  SHIFT+ENTER   PREVIOUS MATCH",
        "  ESC           EXIT SEARCH",
        "",
        "  HELP PAGE: SEARCHES HELP ONLY",
        "  OTHER PAGES: SEARCHES SCRIPTS",
        "",
        "# EDITING (SCRIPT PAGES)",
        "  UP/DOWN       SELECT LINE",
        "  ENTER         SAVE LINE",
        "  CTRL+D        DUPLICATE LINE (PUSH DOWN)",
        "  CTRL+K        DELETE LINE",
        "  CTRL+C        COPY LINE",
        "  CTRL+X        CUT LINE",
        "  CTRL+V        PASTE LINE",
        "  CTRL+Z        UNDO (PAGE-LOCAL)",
        "  CTRL+SHIFT+Z  REDO",
        "  CTRL+L/R      WORD MOVEMENT",
        "",
        "# TRIGGER & VOLUME",
        "  TR            TRIGGER VOICE",
        "  OUT.VOL / VOL 0-1  MASTER VOL",
        "  VCA <0|1>     0=DRONE 1=GATED",
        "  SLEW.ALL <MS>  SLEW MS (0-10000)",
        "  SLEW <P> <MS>  PER-PARAM SLEW",
        "  FLASH <MS>     HOLD MS (DEF 200)",
        "  RST            RESET TO DEF",
        "  LOAD.RST       RST MODE (0=KEEP 1=RST)",
        "  LOAD.RST <0|1> SCENE LOAD MODE",
        "  LOAD.CLR <0|1> AUTO-CLEAR ON LOAD",
        "  Q/QUIT/EXIT    QUIT APP",
        "",
        "# REPL UTILITIES",
        "  CLEAR / CLR   CLEAR OUTPUT",
        "  DEBUG <0-5>   SET VERBOSITY + OUT.*",
        "  DEBUG 0       SILENT (ALL OUT.* OFF)",
        "  DEBUG 1       ERRORS ONLY",
        "  DEBUG 2       + ESSENTIAL INFO",
        "  DEBUG 3       + QUERY RESULTS",
        "  DEBUG 4       + SET CONFIRMATIONS",
        "  DEBUG 5       + VERBOSE (ALL)",
        "  OUT.ERR <0|1> TOGGLE: SHOW ERRORS",
        "  OUT.ESS <0|1> TOGGLE: SHOW ESSENTIAL",
        "  OUT.QRY <0|1> TOGGLE: SHOW QUERIES",
        "  OUT.CFM <0|1> TOGGLE: SHOW CONFIRMS",
        "  HEADER        SHOW HDR VERB",
        "  HEADER <0-4>  SET HDR VERBOSE",
        "  HEADER 0      NAV ONLY",
        "  HEADER 1      NAV + METERS",
        "  HEADER 2      NAV + MET + TR",
        "  HEADER 3      FULL NAV + MET + TR",
        "  HEADER 4      FULL + CPU (DEF)",
        "  PRINT \"TEXT\"  OUTPUT STRING",
        "  PRINT <EXPR>  EVAL & PRINT",
        "  EX: PRINT A, PRINT ADD 1 2",
        "  REPL.DUMP     SAVE OUTPUT TO FILE",
        "  REPL.DUMP <F> SAVE TO CUSTOM FILE",
        "",
        "# NOTES PAGE",
        "  NOTE \"TEXT\"   APPEND NOTE",
        "  NOTE.CLR      CLEAR ALL NOTES",
        "  SAVED WITH SCENES",
        "",
    ],
};

pub const VARIABLES_MATH: HelpCategory = HelpCategory {
    name: "VARIABLES & MATH",
    lines: &[
        "",
        "# VARIABLES",
        "  A B C D       GLOBAL ACCUM",
        "  X Y Z T       GLOBAL ACCUM",
        "  J K           LOCAL VARS",
        "  I             LOOP COUNTER",
        "  EX: A 100 (SET), PF A (USE)",
        "",
        "# MATH (COMMAND & EXPRESSION)",
        "  ADD/+ <A> <B>   ADD",
        "  SUB/- <A> <B>   SUBTRACT",
        "  MUL/* <A> <B>   MULTIPLY",
        "  DIV// <A> <B>   DIVIDE",
        "  MOD/% <A> <B>   MODULO",
        "  MAP <V> <I1> <I2> <O1> <O2>",
        "    MAP VAL IN RANGE -> OUT",
        "  EX: PF MAP A 0 127 200 2000",
        "",
        "# RANDOM & GENERATORS",
        "  RND <MAX>        0 TO MAX",
        "  RRND <MIN> <MAX> MIN TO MAX",
        "  TOSS             COIN FLIP",
        "  EITH <A> <B>     RAND A OR B",
        "  TOG <A> <B>      ALT A/B",
        "",
        "# RHYTHM GENERATORS",
        "  ER f l s        EUCLIDEAN RHYTHM",
        "    f=FILL l=LEN s=STEP -> 0/1",
        "    EX: IF ER 5 8 I: TR",
        "  NR p m f s      NUMERIC REPEATER",
        "    p=PRIME(0-31) m=MASK(0-3)",
        "    f=FACTOR(0-16) s=STEP -> 0/1",
        "",
        "# COUNTERS",
        "  N1-N4         READ + AUTO-INC",
        "  N1.MIN <V>    SET MIN (DEF 0)",
        "  N1.MAX <V>    SET MAX (WRAPS AT MAX)",
        "  N1.RST        RESET TO MIN",
        "  SAME FOR N2, N3, N4",
        "  EX: N1.MIN 10; N1.MAX 14",
        "  CYCLES: 10, 11, 12, 13, 14, 10...",
        "",
        "# INLINE SEQUENCES",
        "  SEQ \"<PATTERN>\"  CYCLE VALS",
        "  TOKENS:",
        "    X           TRIGGER (RET 1)",
        "    _ OR .      REST (RET 0)",
        "    ?           RAND (50% 1, 50% 0)",
        "    NUMBERS     100, -12, 0",
        "    NOTES       C3, E3, F#4, Bb2",
        "  MODIFIERS:",
        "    *N          REPEAT N (C3*4 = C3 C3...)",
        "    <A B>       TOG (LIKE TOG)",
        "    {A B>       RAND (LIKE EITH)",
        "  STATE: PER-SCRIPT, PER-PATT",
        "  EXAMPLES:",
        "    SEQ \"X _ X _\"     TRIG PATT",
        "    SEQ \"C3*4 E3*2\"   REPEAT NOTES",
        "    SEQ \"<C3 E3> G3\"  TOG C3/E3, G3",
        "    SEQ \"{C3 E3} G3\"  RAND C3/E3, G3",
        "    SEQ \"X ? X ?\"     RANDOM TRIGGERS",
        "    SEQ \"<C3 E3>*2\"   TWO TOGGLES",
        "    SEQ \"{C3 E3}*2\"   TWO RANDOMS",
        "",
        "# VOICE RANDOMIZATION",
        "  RND.VOICE  RAND ALL OSC/FM",
        "  RND.OSC    RAND OSC (PF/PW/MF/MW)",
        "  RND.FM     RAND FM (FM/FB/FBA/FBD)",
        "  RND.MOD    RAND MOD ROUTING",
        "  RND.ENV    RAND ENVELOPES",
        "  RND.PL     RAND PLAITS PARAMS",
        "",
        "# FX RANDOMIZATION",
        "  RND.FX     RAND ALL FX",
        "  RND.FILT   RAND FILTER",
        "  RND.DLY    RAND DELAY",
        "  RND.VERB   RAND REVERB",
        "",
        "# PATTERN RANDOMIZATION",
        "  RND.P [MIN] [MAX]      RAND WORK PATT",
        "  RND.PN <N> [MIN] [MAX] RAND PATT N",
        "  RND.PALL [MIN] [MAX]   RAND ALL PATT",
        "",
        "# NOTE/PITCH",
        "  N <SEMI>      SEMITONES TO HZ",
        "  N 0 = C3 (131 HZ)",
        "  N 12 = C4, N 21 = A4 (440)",
        "  EX: PF N 12, PF N ADD A 7",
        "",
    ],
};

pub const CONTROL_FLOW: HelpCategory = HelpCategory {
    name: "CONTROL FLOW",
    lines: &[
        "",
        "# CONTROL FLOW (PRE OPERATORS)",
        "  IF <X>: <CMD>        IF X != 0",
        "  IF <COND>: <CMD>     WITH COMPARE",
        "  ELIF <COND>: <CMD>   ELSE-IF",
        "  ELSE: <CMD>          ELSE",
        "  PROB <0-100>: <CMD>  PROB %",
        "  EV <N>: <CMD>        EVERY NTH",
        "  SKIP <N>: <CMD>      SKIP NTH",
        "  L <S> <E>: <CMDS>    LOOP S-E",
        "  BRK                  STOP SCRIPT",
        "  CMD1; CMD2           SUB-CMDS",
        "",
        "# IF/ELIF/ELSE SCOPE",
        "  SCOPE IS SCRIPT-LOCAL (MULTI-LINE)",
        "  IF STARTS NEW CHAIN, RESETS STATE",
        "  ELIF/ELSE CHECK PRIOR IF IN SCRIPT",
        "  WORKS ACROSS LINES & SEMICOLONS",
        "  EX: IF A > 5: TR",
        "      ELIF A > 2: PF 200",
        "      ELSE: PF 100",
        "  NOTE: NEW IF RESETS CHAIN STATE",
        "",
        "# COMPARISONS (RETURN 1/0)",
        "  EZ <X>       X == 0",
        "  NZ <X>       X != 0",
        "  EQ <A> <B>   A == B",
        "  NE <A> <B>   A != B",
        "  GT <A> <B>   A > B",
        "  LT <A> <B>   A < B",
        "  GTE <A> <B>  A >= B",
        "  LTE <A> <B>  A <= B",
        "  ALSO: > < >= <= == != IN COND",
        "",
        "# SCENES",
        "  SAVE <NAME>   SAVE SCRIPTS+PATT",
        "  LOAD <NAME>   LOAD SCENE",
        "  SCENES        LIST SCENES",
        "  DELETE <NAME> DELETE SCENE",
        "  AUTOLOAD <0|1> AUTO-LOAD LAST SCENE",
        "",
        "# PRESETS",
        "  PSET <SCRIPT> <NAME>      LOAD TO 1-8",
        "  PSET.SAVE <SCRIPT> <NAME> SAVE AS USER",
        "  PSET.DEL <NAME>           DEL USER",
        "  PSETS                     LIST ALL",
        "  [F] = FACTORY, [U] = USER",
        "  EX: PSET 1 808-KICK, PSET.SAVE 2 BASS",
        "",
        "# RECORDING",
        "  REC           START REC (WAV)",
        "  REC.STOP      STOP RECORDING",
        "  REC.PATH <P>  SET PATH PREFIX",
        "",
    ],
};

pub const PATTERNS: HelpCategory = HelpCategory {
    name: "PATTERNS",
    lines: &[
        "",
        "# PATTERNS (WORKING - P.N)",
        "  P.N           GET WORK PATT",
        "  P.N <0-5>     SET WORK PATT",
        "  P.L / P.L <N> GET/SET LENGTH",
        "  P.I / P.I <N> GET/SET INDEX",
        "  P.HERE        VALUE AT INDEX",
        "  P.NEXT        ADVANCE, GET VAL",
        "  P.PREV        REVERSE, GET VAL",
        "  P <I> / P <I> <V>  GET/SET AT I",
        "",
        "# PATTERNS (EXPLICIT - PN)",
        "  PN.L <P> / PN.L <P> <N>  LEN",
        "  PN.I <P> / PN.I <P> <N>  IDX",
        "  PN.HERE <P>              VAL",
        "  PN.NEXT <P>              ADV",
        "  PN.PREV <P>              REV",
        "  PN <P> <I> / PN <P> <I> <V>",
        "",
        "# PATTERN MANIPULATION",
        "  P.PUSH <V>     PUSH VAL, SHIFT LEFT",
        "  P.POP          POP & RETURN LAST VAL",
        "  P.INS <I> <V>  INSERT VAL AT INDEX",
        "  P.RM <I>       REMOVE VAL AT INDEX",
        "  P.REV          REVERSE PATTERN",
        "  P.ROT <N>      ROTATE BY N STEPS",
        "  P.SHUF         SHUFFLE RANDOMLY",
        "  P.SORT         SORT ASCENDING",
        "  P.RND [MIN] [MAX]  RANDOMIZE VALUES",
        "  P.CLR          CLEAR (SET ALL TO 0)",
        "",
        "# PATTERN MATH",
        "  P.ADD <V>      ADD TO ALL VALUES",
        "  P.SUB <V>      SUBTRACT FROM ALL",
        "  P.MUL <V>      MULTIPLY ALL VALUES",
        "  P.DIV <V>      DIVIDE ALL VALUES",
        "  P.MOD <V>      MODULO ALL VALUES",
        "  P.SCALE <MIN> <MAX> SCALE TO NEW RANGE",
        "",
        "# PATTERN QUERIES",
        "  P.MIN          GET MINIMUM VALUE",
        "  P.MAX          GET MAXIMUM VALUE",
        "  P.SUM          GET SUM OF ALL",
        "  P.AVG          GET AVERAGE VALUE",
        "  P.FND <V>      FIND INDEX OF VAL (-1)",
        "",
        "  NOTE: PN.* VARIANTS TAKE PATTERN",
        "  NUMBER AS FIRST ARG (EX: PN.ADD 0 5)",
        "",
        "# STATE SYNCHRONIZATION",
        "  SYNC          RESET ALL STATE",
        "  SYNC.SEQ      RESET SEQ STATE",
        "  SYNC.TOG      RESET TOG/EITH STATE",
        "  SYNC.PAT      RESET PATTERN INDICES",
        "",
    ],
};

pub const SCALE_QUANTIZATION: HelpCategory = HelpCategory {
    name: "SCALE QUANTIZATION",
    lines: &[
        "",
        "# SCALE QUANTIZATION",
        "  Q <NOTE>       QUANT NOTE TO SCALE",
        "  Q.ROOT <0-11>  ROOT (C=0...B=11)",
        "  Q.SCALE <0-11> SCALE TYPE",
        "  Q.BIT <BINARY> CUSTOM SCALE MASK",
        "",
        "# SCALE TYPES",
        "  0=CHROM  1=MAJ      2=MIN",
        "  3=DOR    4=PHRYG    5=LYD",
        "  6=MIXO   7=PENT MAJ 8=PENT MIN",
        "  9=BLUES 10=WHOLE  11=DIM",
        "",
        "# Q.BIT EXAMPLES",
        "  Q.BIT 101010110101  MAJ (12-TET)",
        "  Q.BIT 10101         PENT (5-EDO)",
        "  Q.BIT <24 BITS>     QUARTER-TONE",
        "",
        "# USAGE",
        "  PF N Q A           QUANT A TO HZ",
        "  PF N Q P.NEXT      PATT TO SCALE",
        "",
    ],
};
