use super::help_categories::HelpCategory;

pub const OSCILLATORS_FM: HelpCategory = HelpCategory {
    name: "OSCILLATORS & FM",
    lines: &[
        "",
        "# OSCILLATORS",
        "  POSC.FREQ / PF <HZ>    PRI FREQ (20-20K)",
        "  POSC.WAVE / PW <0-2>   PRI (SIN/TRI/SAW)",
        "  MOSC.FREQ / MF <HZ>    MOD FREQ (20-20K)",
        "  MOSC.WAVE / MW <0-2>   MOD (SIN/TRI/SAW)",
        "",
        "# FM SYNTHESIS",
        "  MBUS.FM / FM <0-16383> FM IDX",
        "  FMEV.AMT / FA <0-16383> FM ENV AMT",
        "  FMEV.DEC / FD <MS>     FM ENV DEC",
        "",
        "# FEEDBACK FM",
        "  MOSC.FB / FB <0-16383>  FB AMT",
        "  FBEV.AMT / FBA <0-16383> FB ENV AMT",
        "  FBEV.DEC / FBD <MS>     FB ENV DEC",
        "",
        "# DISCONTINUITY",
        "  DISC.AMT / DC <0-16383> DISC AMT",
        "  DENV.AMT / DA <0-16383> DC ENV AMT",
        "  DENV.DEC / DD <MS>      DC ENV DEC",
        "  DISC.MODE / DM <0-6>    MODE (FOLD/TANH)",
        "",
        "# LO-FI",
        "  LOFI.BIT / LB <1-16>    BIT (16=CLEAN)",
        "  LOFI.SMP / LS <100-48K> SAMP RATE",
        "  LOFI.MIX / LM <0-16383> MIX",
        "",
        "# MOD BUS",
        "  MBUS.AMT / MB <0-16383> MOD AMT",
        "  MBEV.AMT / MBA <0-16383> MOD ENV AMT",
        "  MBEV.DEC / MBD <1-10000> MOD ENV DEC (MS)",
        "  MBUS.TRK / TK <0-16383> TRACK AMT",
        "",
        "# MOD ROUTING (TOGGLES)",
        "  ROUT.MP / MP <0|1>      MOD -> PRI FREQ",
        "  ROUT.MD / MD <0|1>      MOD -> DISC",
        "  ROUT.MT / MT <0|1>      MOD -> TRACK",
        "  ROUT.MA / MA <0|1>      MOD -> AMP",
        "  ROUT.MC / MC <0|1>      MOD -> FILTER CUT",
        "  ROUT.MQ / MQ <0|1>      MOD -> FILTER RES",
        "",
        "# MOD ROUTING (AMOUNTS)",
        "  MODF.CUT / MFF <0-16383> MOD->CUT AMOUNT",
        "  MODF.RES / MFQ <0-16383> MOD->RES AMOUNT",
        "",
        "# MIX",
        "  MBUS.MIX / MX <0-16383> MIX AMT",
        "  MBUS.MMX / MM <0|1>     MOD -> MIX",
        "  MBUS.EMX / ME <0|1>     ENV -> MIX",
        "",
        "# NOISE",
        "  NOISE.WAV / NW <0-2>  TYPE (WHT/PNK/BRN)",
        "  NOISE.PRI / NP <0-16K> -> PRI OSC FM",
        "  NOISE.MOD / NM <0-16K> -> MOD OSC FM",
        "  NOISE.VOL / NV <0-16K> NOISE VOL",
        "",
        "# SOURCE LEVELS",
        "  PRI.VOL / PV <0-16383> PRI OSC VOL",
        "  MOD.VOL / MV <0-16383> MOD OSC VOL",
        "  PLV <0-16383>          PLAITS MAIN VOL",
        "  PAV <0-16383>          PLAITS AUX VOL",
        "",
    ],
};

pub const ENVELOPES: HelpCategory = HelpCategory {
    name: "ENVELOPES",
    lines: &[
        "",
        "# AMPLITUDE ENVELOPE",
        "  AENV.DEC / AD <MS>       DEC (1-10K)",
        "  AENV.ATK / AA <MS>       ATK (1-10K)",
        "  AENV.CRV / AC <V>        CRV (-8 TO 8)",
        "",
        "# PITCH ENVELOPE",
        "  PENV.AMT / PA <OCTAVES>  AMT (0-16)",
        "  PENV.DEC / PD <MS>       DEC (1-10K)",
        "  PENV.ATK / PAA <MS>      ATK (1-10K)",
        "  PENV.CRV / PC <V>        CRV (-8 TO 8)",
        "",
        "# FM ENVELOPE",
        "  FMEV.AMT / FA <0-16383>  AMT",
        "  FMEV.DEC / FD <MS>       DEC (1-10K)",
        "  FMEV.ATK / FAA <MS>      ATK (1-10K)",
        "  FMEV.CRV <V>             CRV (-8 TO 8)",
        "",
        "# DISCONTINUITY ENVELOPE",
        "  DENV.AMT / DA <0-16383>  AMT",
        "  DENV.DEC / DD <MS>       DEC (1-10K)",
        "  DENV.ATK / DAA <MS>      ATK (1-10K)",
        "  DENV.CRV <V>             CRV (-8 TO 8)",
        "",
        "# FEEDBACK ENVELOPE",
        "  FBEV.AMT / FBA <0-16383> AMT",
        "  FBEV.DEC / FBD <MS>      DEC (1-10K)",
        "  FBEV.ATK / FBAA <MS>     ATK (1-10K)",
        "  FBEV.CRV / FBC <V>       CRV (-8 TO 8)",
        "",
        "# FILTER ENVELOPE",
        "  FLEV.AMT / FE <0-16383>  AMT",
        "  FLEV.DEC / FED <MS>      DEC (1-10K)",
        "  FLEV.ATK / FLAA <MS>     ATK (1-10K)",
        "  FLEV.CRV / FLC <V>       CRV (-8 TO 8)",
        "",
        "# NOTE",
        "  FMEV.CRV, DENV.CRV: NO SHORT ALIAS",
        "  FC = FILT CUT, DC = DISC AMT",
        "",
    ],
};

pub const PLAITS_SYNTH: HelpCategory = HelpCategory {
    name: "PLAITS SYNTH",
    lines: &[
        "",
        "# PLAITS ENGINE (16 ENGINES)",
        "  PL.ENG <0-15>  SELECT ENGINE",
        "  0=VA  1=FOLD  2=FM  3=GRAIN",
        "  4=HARM  5=WAVE  6=CHORD  7=VOWEL",
        "  8=CLOUD  9=NOISE  10=PARTICLE",
        "  11=STRING  12=MODAL  13=KICK",
        "  14=SNARE  15=HIHAT",
        "",
        "# PLAITS PARAMETERS",
        "  PL.FREQ / PLF <HZ> PITCH (20-20K)",
        "  PL.HARM / PLH <0-16383> HARMONICS",
        "  PL.TIMB / PLT <0-16383> TIMBRE",
        "  PL.MORPH / PLM <0-16383> MORPH",
        "  PL.DEC / PLD <0-16383> DECAY ENV",
        "  PL.LPG / PLL <0-16383> LOWPASS GATE",
        "",
        "# PLAITS TRIGGER & VOLUME",
        "  PLTR               TRIGGER ENGINE",
        "  PLV <0-16383>      MAIN OUT VOL",
        "  PAV <0-16383>      AUX OUT VOL",
        "",
        "# SIGNAL FLOW",
        "  PLAITS MIXED POST-VCA",
        "  BYPASSES: DISC, LOFI, FILT,",
        "            RING, RESO, VCA",
        "  HITS: COMP, EQ, DLY, VERB",
        "  INTERNAL: 16 ENGINES, LPG, ENV",
        "",
        "# RANDOMIZATION",
        "  RND.PL  RAND ALL PLAITS PARAMS",
        "",
    ],
};

pub const SAMPLER: HelpCategory = HelpCategory {
    name: "SAMPLER",
    lines: &[
        "",
        "# SAMPLER LOADING",
        "  KIT <PATH>        LOAD KIT/FILE",
        "    DIR = KIT MODE (ONE-SHOT PER SLOT)",
        "    FILE = SLICE MODE (AUTO-SLICED)",
        "  KIT               LIST KITS (REPL ONLY)",
        "  KIT.LEN / KL      SLOTS COUNT (EXPR OK)",
        "  KIT.INFO          CURRENT KIT INFO",
        "  STR <N>           TRIGGER SLOT (EXPR OK)",
        "  STR               RE-TRIGGER CURRENT",
        "  EX: STR 5, STR RND 0 15, STR + A 1",
        "",
        "# SAMPLER SLICING",
        "  S.SLICE / SSLC <2-128> EQUAL SLICES",
        "    DIVIDES FILE INTO N EQUAL PARTS",
        "  S.ONSET / SONS [0-10] AUTO-DETECT",
        "    FINDS TRANSIENTS, 0=MANY 10=FEW",
        "    DEFAULT 5, FALLBACK: S.SLICE 16",
        "  S.ONSET.MIN / SOMIN <10-500> MIN MS",
        "    MINIMUM MS BETWEEN ONSETS (DEF 50)",
        "  EX: S.ONSET, S.ONSET 3, SOMIN 30",
        "",
        "# SAMPLER PLAYBACK (S.*)",
        "  S.RATE / SR <0-16383>  RATE (8K=1X)",
        "  S.PITCH / SPT <-24-24> PITCH (SEMI)",
        "  S.FINE / SFN <-100-100> FINE (CENTS)",
        "  S.DIR / SD <0|1>       DIR (0=FWD 1=REV)",
        "  S.LOOP / SL <0|1>      LOOP MODE",
        "  S.START / SST <0-16383> START OFFSET",
        "  S.LEN / SLE <0-16383>  LOOP LENGTH",
        "",
        "# SAMPLER ENVELOPE",
        "  S.ATK / SA <0-16383>   ATTACK MS",
        "  S.DEC / SDC <0-16383>  DECAY MS",
        "  S.REL / SRE <0-16383>  RELEASE MS",
        "  S.SUST / SSU <0|1>     SUSTAIN MODE",
        "    0 = ONE-SHOT (PERCUSSIVE)",
        "    1 = HOLD WHILE GATE HIGH",
        "",
        "# SAMPLER OUTPUT",
        "  VOL.SMP / VS <0-16383> VOLUME (MIXER)",
        "  PAN.SMP / PS <-8K-8K>  PAN (MIXER)",
        "  S.FX / SFX <0-1>       FX ROUTE",
        "    0=BYPASS SPATIAL  1=FULL CHAIN",
        "",
        "# SAMPLER MODULATION (MODBUS)",
        "  S.RATEMOD / SRM <0-16383> RATE MOD",
        "  S.PITCHMOD / SPM <0-16383> PITCH MOD",
        "  SF.CUTMOD / SFCM <0-16383> FLT CUT MOD",
        "  SF.RESMOD / SFQM <0-16383> FLT RES MOD",
        "  NOTE: REQUIRES MODBUS SIGNAL (MB>0)",
        "",
        "# SAMPLER FX: FILTER (SF.F*)",
        "  SF.CUT / SFC <0-16383> CUTOFF",
        "  SF.RES / SFQ <0-16383> RESONANCE",
        "  SF.TYPE / SFT <0-13>   FILTER TYPE",
        "    0=SVF LP  1=SVF HP  2=SVF BP",
        "    3=NOTCH  4=MOOG  5=BUTTER LP",
        "    6=BUTTER HP  7=DFM1 LP  8=DFM1 HP",
        "    9=BMOOG LP  10=BMOOG HP  11=BMOOG BP",
        "    12=SVF LATCHED LP  13=SVF LATCHED BP",
        "",
        "# SAMPLER FX: DECIMATOR (SF.D*)",
        "  SF.BITS / SFB <1-24>   BIT DEPTH",
        "  SF.RATE / SFR <0-16383> SRR AMOUNT",
        "  SF.DECI / SFD <0-16383> DECI MIX",
        "",
        "# SAMPLER FX: GLITCH (SF.G*)",
        "  SF.PROB / SFP <0-16383> GLIT PROB",
        "  SF.MULT / SFM <0-16383> GLIT MULT",
        "  SF.GLIT / SFG <0-16383> GLIT MIX",
        "",
        "# SIGNAL FLOW",
        "  SAMPLE -> DECIMATOR -> GLITCH ->",
        "  FILTER -> MAIN MIX (VOL.SMP/PAN.SMP)",
        "  USE GLOBAL DLY/REV/CL FOR SPACE",
        "",
    ],
};
