pub struct HelpCategory {
    pub name: &'static str,
    pub lines: &'static [&'static str],
}

pub const HELP_CATEGORIES: &[HelpCategory] = &[
    HelpCategory {
        name: "NAVIGATION & EDITING",
        lines: &[
            "",
            "# COMMAND NAMING CONVENTION",
            "  PREFIX.SUFFIX - CANONICAL FORM",
            "  EXAMPLES: POSC.FREQ, FILT.CUT, AENV.ATK",
            "  SHORT FORMS REMAIN AS ALIASES (PF, FC, AD)",
            "  USE WHICHEVER FORM YOU PREFER",
            "",
            "# NAVIGATION",
            "  [ ]           CYCLE PAGES",
            "  ESC           TOGGLE HELP",
            "  F1-F8         SCRIPT 1-8",
            "  F9            LIVE PAGE",
            "  F10           METRO PAGE",
            "  F11           INIT PAGE",
            "  F12           PATTERN PAGE",
            "  CTRL+UP/DN    SCROLL REPL OUTPUT (LIVE PAGE)",
            "",
            "# EDITING (SCRIPT PAGES)",
            "  UP/DOWN       SELECT LINE",
            "  ENTER         SAVE LINE",
            "  CTRL+D        DUPLICATE LINE",
            "  CTRL+K        DELETE LINE",
            "  CTRL+C        COPY LINE",
            "  CTRL+X        CUT LINE",
            "  CTRL+V        PASTE LINE",
            "  CTRL+L/R      WORD MOVEMENT",
            "",
            "# TRIGGER & VOLUME",
            "  TR                 TRIGGER VOICE",
            "  OUT.VOL / VOL 0-1  MASTER VOLUME",
            "  SLEW.ALL <MS>      PARAM SLEW TIME (0-10000)",
            "  SLEW <P> <MS>      PER-PARAM SLEW TIME",
            "  RST                RESET TO DEFAULTS",
            "  Q/QUIT/EXIT        QUIT APPLICATION",
            "",
            "# REPL UTILITIES",
            "  CLEAR         CLEAR OUTPUT HISTORY",
            "  DEBUG <0-2>   SET VERBOSITY LEVEL",
            "  DEBUG 0       SILENT (ERRORS ONLY)",
            "  DEBUG 1       IMPORTANT (METRO, PRINT)",
            "  DEBUG 2       VERBOSE (ALL PARAMS)",
            "  PRINT \"TEXT\"  OUTPUT LITERAL STRING",
            "  PRINT <EXPR>  EVALUATE & PRINT",
            "  EXAMPLE: PRINT A, PRINT ADD 1 2",
            "",
        ],
    },
    HelpCategory {
        name: "VARIABLES & MATH",
        lines: &[
            "",
            "# VARIABLES",
            "  A B C D       GLOBAL ACCUMULATORS",
            "  X Y Z T       GLOBAL ACCUMULATORS",
            "  J K           PER-SCRIPT LOCAL VARS",
            "  I             LOOP COUNTER (IN L)",
            "  EXAMPLE: A 100 (SET), PF A (USE)",
            "",
            "# MATH (COMMAND & EXPRESSION)",
            "  ADD/+ <A> <B>   ADD",
            "  SUB/- <A> <B>   SUBTRACT",
            "  MUL/* <A> <B>   MULTIPLY",
            "  DIV// <A> <B>   DIVIDE",
            "  MOD/% <A> <B>   MODULO",
            "  MAP <V> <I1> <I2> <O1> <O2>",
            "    MAP VALUE FROM INPUT RANGE TO OUTPUT",
            "  EXAMPLE: PF MAP A 0 127 200 2000",
            "",
            "# RANDOM & GENERATORS",
            "  RND <MAX>        0 TO MAX",
            "  RRND <MIN> <MAX> MIN TO MAX",
            "  TOSS             COIN FLIP (0/1)",
            "  EITH <A> <B>     RANDOM CHOICE A OR B",
            "  TOG <A> <B>      ALTERNATE BETWEEN A AND B",
            "",
            "# INLINE SEQUENCES",
            "  SEQ \"<PATTERN>\"  CYCLE THROUGH VALUES",
            "  TOKENS: X (1), _ OR . (0/REST)",
            "          NUMBERS: 100, -12, 0",
            "          NOTES: C3, E3, F#4, Bb2 (SEMITONES)",
            "  STATE: PER-SCRIPT AND PER-PATTERN",
            "  IF SEQ \"X _ X _\": TR      TRIGGER PATTERN",
            "  PF N SEQ \"C3 E3 G3 C4\"    ARPEGGIATE",
            "  A SEQ \"0 1 2 3\"           STORE IN VAR",
            "  PF N Q SEQ \"0 3 5 7\"      WITH QUANTIZATION",
            "",
            "# VOICE RANDOMIZATION",
            "  RND.VOICE  RANDOMIZE ALL OSC/FM PARAMS",
            "  RND.OSC    RANDOMIZE OSCILLATORS (PF/PW/MF/MW)",
            "  RND.FM     RANDOMIZE FM PARAMS (FM/FB/FBA/FBD)",
            "  RND.MOD    RANDOMIZE MODULATION ROUTING",
            "  RND.ENV    RANDOMIZE ENVELOPE SETTINGS",
            "",
            "# FX RANDOMIZATION",
            "  RND.FX     RANDOMIZE ALL EFFECTS",
            "  RND.FILT   RANDOMIZE FILTER PARAMS",
            "  RND.DLY    RANDOMIZE DELAY PARAMS",
            "  RND.VERB   RANDOMIZE REVERB PARAMS",
            "",
            "# PATTERN RANDOMIZATION",
            "  RND.P [MIN] [MAX]     RANDOMIZE WORKING PATTERN",
            "  RND.PN <N> [MIN] [MAX] RANDOMIZE PATTERN N",
            "  RND.PALL [MIN] [MAX]  RANDOMIZE ALL PATTERNS",
            "",
            "# NOTE/PITCH",
            "  N <SEMI>      SEMITONES TO HZ",
            "  N 0 = C3 (131 HZ)",
            "  N 12 = C4, N 21 = A4 (440)",
            "  EXAMPLE: PF N 12, PF N ADD A 7",
            "",
        ],
    },
    HelpCategory {
        name: "CONTROL FLOW",
        lines: &[
            "",
            "# CONTROL FLOW (PRE OPERATORS)",
            "  IF <X>: <CMD>        IF X != 0 (TRUTHY)",
            "  IF <COND>: <CMD>     WITH COMPARISON",
            "  ELIF <COND>: <CMD>   ELSE-IF",
            "  ELSE: <CMD>          ELSE BRANCH",
            "  PROB <0-100>: <CMD>  PROBABILITY %",
            "  EV <N>: <CMD>        EVERY NTH TICK",
            "  SKIP <N>: <CMD>      SKIP EVERY NTH",
            "  L <S> <E>: <CMDS>    LOOP S TO E",
            "  CMD1; CMD2           SUB-COMMANDS",
            "",
            "# COMPARISONS (RETURN 1/0)",
            "  EZ <X>       X == 0 (EQUALS ZERO)",
            "  NZ <X>       X != 0 (NOT ZERO)",
            "  EQ <A> <B>   A == B",
            "  NE <A> <B>   A != B",
            "  GT <A> <B>   A > B",
            "  LT <A> <B>   A < B",
            "  GTE <A> <B>  A >= B",
            "  LTE <A> <B>  A <= B",
            "  ALSO: > < >= <= == != IN COND",
            "",
            "# SCENES",
            "  SAVE <NAME>   SAVE SCRIPTS+PATTERNS",
            "  LOAD <NAME>   LOAD SCENE",
            "  SCENES        LIST SAVED SCENES",
            "  DELETE <NAME> DELETE SCENE",
            "",
            "# PRESETS",
            "  PSET <SCRIPT> <NAME>      LOAD PRESET INTO SCRIPT 1-8",
            "  PSET.SAVE <SCRIPT> <NAME> SAVE SCRIPT AS USER PRESET",
            "  PSET.DEL <NAME>           DELETE USER PRESET",
            "  PSETS                     LIST ALL PRESETS",
            "  [F] = FACTORY (READ-ONLY), [U] = USER",
            "  EXAMPLES: PSET 1 808-KICK, PSET.SAVE 2 MY-BASS",
            "",
            "# RECORDING",
            "  REC           START RECORDING (WAV)",
            "  REC.STOP      STOP RECORDING",
            "  REC.PATH <P>  SET PATH PREFIX",
            "",
        ],
    },
    HelpCategory {
        name: "PATTERNS",
        lines: &[
            "",
            "# PATTERNS (WORKING - P.N)",
            "  P.N           GET WORKING PATTERN",
            "  P.N <0-5>     SET WORKING PATTERN",
            "  P.L / P.L <N> GET/SET LENGTH",
            "  P.I / P.I <N> GET/SET INDEX",
            "  P.HERE        VALUE AT INDEX",
            "  P.NEXT        ADVANCE, GET VALUE",
            "  P.PREV        REVERSE, GET VALUE",
            "  P <I> / P <I> <V>  GET/SET AT INDEX",
            "",
            "# PATTERNS (EXPLICIT - PN)",
            "  PN.L <P> / PN.L <P> <N>  LENGTH",
            "  PN.I <P> / PN.I <P> <N>  INDEX",
            "  PN.HERE <P>              VALUE",
            "  PN.NEXT <P>              ADVANCE",
            "  PN.PREV <P>              REVERSE",
            "  PN <P> <I> / PN <P> <I> <V>",
            "",
            "# COUNTERS",
            "  N1-N4         READ VALUE + AUTO-INCREMENT",
            "  N1.MIN <N>    SET MINIMUM (DEFAULT 0)",
            "  N1.MAX <N>    SET MAXIMUM (WRAPS BACK)",
            "  N1.RST        RESET TO MIN",
            "  EXAMPLE: N1.MIN 10; N1.MAX 14",
            "  CYCLES: 10, 11, 12, 13, 14, 10...",
            "",
        ],
    },
    HelpCategory {
        name: "SCALE QUANTIZATION",
        lines: &[
            "",
            "# SCALE QUANTIZATION",
            "  Q <NOTE>       QUANTIZE NOTE TO SCALE",
            "  Q.ROOT <0-11>  SET ROOT (C=0...B=11)",
            "  Q.SCALE <0-11> SET SCALE TYPE",
            "  Q.BIT <BINARY> SET CUSTOM SCALE MASK",
            "",
            "# SCALE TYPES",
            "  0=CHROMATIC   1=MAJOR     2=MINOR",
            "  3=DORIAN      4=PHRYGIAN  5=LYDIAN",
            "  6=MIXOLYDIAN  7=PENT MAJ  8=PENT MIN",
            "  9=BLUES      10=WHOLE    11=DIMINISHED",
            "",
            "# Q.BIT EXAMPLES",
            "  Q.BIT 101010110101  MAJOR (12-TET)",
            "  Q.BIT 10101         PENTATONIC (5-EDO)",
            "  Q.BIT <24 BITS>     QUARTER-TONES",
            "",
            "# USAGE",
            "  PF N Q A           QUANTIZE A TO HZ",
            "  PF N Q P.NEXT      PATTERN TO SCALE",
            "",
        ],
    },
    HelpCategory {
        name: "OSCILLATORS & FM",
        lines: &[
            "",
            "# OSCILLATORS",
            "  POSC.FREQ / PF <HZ>    PRIMARY FREQ (20-20000)",
            "  POSC.WAVE / PW <0-2>   PRIMARY WAVE (SIN/TRI/SAW)",
            "  MOSC.FREQ / MF <HZ>    MOD FREQ (20-20000)",
            "  MOSC.WAVE / MW <0-2>   MOD WAVE (SIN/TRI/SAW)",
            "",
            "# FM SYNTHESIS",
            "  MBUS.FM / FM <0-16383> FM INDEX",
            "  FMEV.AMT / FA <0-16383> FM ENV AMOUNT",
            "  FMEV.DEC / FD <MS>     FM ENV DECAY",
            "",
            "# FEEDBACK FM",
            "  MOSC.FB / FB <0-16383>  FEEDBACK AMOUNT",
            "  FBEV.AMT / FBA <0-16383> FEEDBACK ENV AMOUNT",
            "  FBEV.DEC / FBD <MS>     FEEDBACK ENV DECAY",
            "",
            "# DISCONTINUITY",
            "  DISC.AMT / DC <0-16383> DISCONTINUITY AMOUNT",
            "  DENV.AMT / DA <0-16383> DC ENV AMOUNT",
            "  DENV.DEC / DD <MS>      DC ENV DECAY",
            "  DISC.MODE / DM <0-6>    MODE (FOLD/TANH/...)",
            "",
            "# LO-FI",
            "  LOFI.BIT / LB <1-16>    BIT DEPTH (16=CLEAN)",
            "  LOFI.SMP / LS <100-48K> SAMPLE RATE (HZ)",
            "  LOFI.MIX / LM <0-16383> LO-FI MIX",
            "",
            "# MOD BUS",
            "  MBUS.AMT / MB <0-16383> MOD BUS AMOUNT",
            "  MBUS.TRK / TK <0-16383> TRACKING AMOUNT",
            "  ROUT.MP / MP <0|1>      MOD -> PRIMARY FREQ",
            "  ROUT.MD / MD <0|1>      MOD -> DISCONTINUITY",
            "  ROUT.MT / MT <0|1>      MOD -> TRACKING",
            "  ROUT.MA / MA <0|1>      MOD -> AMPLITUDE",
            "",
            "# MIX",
            "  MBUS.MIX / MX <0-16383> MIX AMOUNT",
            "  MBUS.MMX / MM <0|1>     MOD BUS -> MIX",
            "  MBUS.EMX / ME <0|1>     ENVELOPE -> MIX",
            "",
        ],
    },
    HelpCategory {
        name: "ENVELOPES",
        lines: &[
            "",
            "# AMPLITUDE ENVELOPE",
            "  AENV.DEC / AD <MS>       DECAY TIME (1-10000)",
            "  AENV.ATK <MS>            ATTACK TIME (1-10000)",
            "  AENV.CRV <V>             CURVE SHAPE (-8 TO 8)",
            "",
            "# PITCH ENVELOPE",
            "  PENV.AMT / PA <OCTAVES>  ENVELOPE AMOUNT (0-16)",
            "  PENV.DEC / PD <MS>       DECAY TIME (1-10000)",
            "  PENV.ATK <MS>            ATTACK TIME (1-10000)",
            "  PENV.CRV <V>             CURVE SHAPE (-8 TO 8)",
            "",
            "# FM ENVELOPE",
            "  FMEV.AMT / FA <0-16383>  ENVELOPE AMOUNT",
            "  FMEV.DEC / FD <MS>       DECAY TIME (1-10000)",
            "  FMEV.ATK <MS>            ATTACK TIME (1-10000)",
            "  FMEV.CRV <V>             CURVE SHAPE (-8 TO 8)",
            "",
            "# DISCONTINUITY ENVELOPE",
            "  DENV.AMT / DA <0-16383>  ENVELOPE AMOUNT",
            "  DENV.DEC / DD <MS>       DECAY TIME (1-10000)",
            "  DENV.ATK <MS>            ATTACK TIME (1-10000)",
            "  DENV.CRV <V>             CURVE SHAPE (-8 TO 8)",
            "",
            "# FEEDBACK ENVELOPE",
            "  FBEV.AMT / FBA <0-16383> ENVELOPE AMOUNT",
            "  FBEV.DEC / FBD <MS>      DECAY TIME (1-10000)",
            "  FBEV.ATK <MS>            ATTACK TIME (1-10000)",
            "  FBEV.CRV <V>             CURVE SHAPE (-8 TO 8)",
            "",
            "# FILTER ENVELOPE",
            "  FLEV.AMT / FE <0-16383>  ENVELOPE AMOUNT",
            "  FLEV.DEC / FED <MS>      DECAY TIME (1-10000)",
            "  FLEV.ATK <MS>            ATTACK TIME (1-10000)",
            "  FLEV.CRV <V>             CURVE SHAPE (-8 TO 8)",
            "",
        ],
    },
    HelpCategory {
        name: "FILTER & EFFECTS",
        lines: &[
            "",
            "# SVF FILTER",
            "  FILT.CUT / FC <HZ>      CUTOFF FREQ (20-20000)",
            "  FILT.RES / FQ <0-16383> RESONANCE",
            "  FILT.TYP / FT <0-3>     TYPE (LP/HP/BP/NOTCH)",
            "  FLEV.AMT / FE <0-16383> FILTER ENV AMOUNT",
            "  FLEV.DEC / FED <MS>     FILTER ENV DECAY",
            "  FILT.KEY / FK <0-16383> KEY TRACKING",
            "  ROUT.MF / MF.F <0-1>    MOD BUS -> FILTER",
            "",
            "# RING MOD",
            "  RING.FRQ / RGF <20-2000> RING MOD FREQ (HZ)",
            "  RING.WAV / RGW <0-3>     WAVEFORM (SIN/TRI/SAW/SQR)",
            "  RING.MIX / RGM <0-16383> RING MOD MIX",
            "",
            "# COMB RESONATOR",
            "  RESO.FRQ / RF <HZ>      RESONATOR FREQ",
            "  RESO.DEC / RD <MS>      RESONATOR DECAY",
            "  RESO.MIX / RM <0-16383> RESONATOR MIX",
            "  RESO.KEY / RK <0-16383> RESONATOR KEY TRACK",
            "",
            "# COMPRESSOR",
            "  COMP.THR / CT <0-16383> THRESHOLD",
            "  COMP.RAT / CR <1-20>    RATIO",
            "  COMP.ATK / CA <1-500>   ATTACK (MS)",
            "  COMP.REL / CL <10-2000> RELEASE (MS)",
            "  COMP.MKP / CM <0-16383> MAKEUP GAIN",
            "",
            "# PAN",
            "  OUT.PAN / PAN <-16K-16K> STEREO POSITION",
            "",
            "# BEAT REPEAT",
            "  BR.ACT <0|1>  ENABLE BEAT REPEAT",
            "  BR.LEN <0-7>  LOOP DIV (0=1/16...7=8X)",
            "  BR.REV <0|1>  REVERSE PLAYBACK",
            "  BR.WIN <1-50> WINDOW SIZE (MS)",
            "  BR.MIX <0-16383> BEAT REPEAT MIX",
            "",
            "# PITCH SHIFT",
            "  PS.MODE <0|1>   MODE (NORMAL/GRANULAR)",
            "  PS.SEMI <-24-24> SHIFT (SEMITONES)",
            "  PS.GRAIN <5-100> GRAIN SIZE (MS)",
            "  PS.MIX <0-16383> PITCH SHIFT MIX",
            "  PS.TARG <0|1>    TARGET (INPUT/OUTPUT)",
            "",
            "# 3-BAND EQ",
            "  EQ.LOW / EL <-24-24>    LOW SHELF (DB)",
            "  EQ.MID / EM <-24-24>    MID PEAK (DB)",
            "  EQ.FRQ / EF <200-8000>  MID FREQ (HZ)",
            "  EQ.Q <0.1-10>           MID Q",
            "  EQ.HI / EH <-24-24>     HIGH SHELF (DB)",
            "",
        ],
    },
    HelpCategory {
        name: "DELAY & REVERB",
        lines: &[
            "",
            "# STEREO DELAY",
            "  DLY.TIME / DT <MS>      DELAY TIME (1-2000)",
            "  DLY.FB / DF <0-16383>   DELAY FEEDBACK",
            "  DLY.LP / DLP <HZ>       DELAY LP FILTER",
            "  DLY.WET / DW <0-16383>  DELAY WET MIX",
            "  DLY.SYN / DS <0-16383>  DELAY STEREO WIDTH",
            "",
            "# DELAY ROUTING",
            "  DLY.MODE / D.MODE <0-2> BYPASS/INSERT/SEND",
            "  DLY.TAIL / D.TAIL <0-2> CUT/RING/FREEZE",
            "",
            "# PLATE REVERB",
            "  REV.DEC / RV <0-16383>  REVERB DECAY",
            "  REV.PRE / RP <MS>       REVERB PRE-DELAY",
            "  REV.DMP / RH <0-16383>  REVERB DAMPING (HI)",
            "  REV.WET / RW <0-16383>  REVERB WET MIX",
            "",
            "# REVERB ROUTING",
            "  REV.MODE / R.MODE <0-2> BYPASS/INSERT/SEND",
            "  REV.TAIL / R.TAIL <0-2> CUT/RING/FREEZE",
            "",
        ],
    },
    HelpCategory {
        name: "METRO & SCRIPTS",
        lines: &[
            "",
            "# METRO",
            "  M             SHOW INTERVAL",
            "  M <MS>        SET INTERVAL",
            "  M.BPM <BPM>   SET BPM",
            "  M.ACT <0|1>   START/STOP",
            "  M.SCRIPT <1-8>  SCRIPT FOR METRO",
            "",
            "# SCRIPTS",
            "  SCRIPT <1-8>  EXECUTE STORED SCRIPT",
            "",
            "# DELAYED EXECUTION",
            "  DEL <MS>: <CMD>     EXECUTE CMD AFTER MS",
            "  DEL.CLR             CLEAR PENDING DELAYS",
            "  DEL.X <N> <MS>: CMD REPEAT N TIMES AT MS INTERVALS",
            "  DEL.R <N> <MS>: CMD EXEC NOW + REPEAT N-1 TIMES",
            "  MAX DELAY: 16000MS",
            "",
        ],
    },
    HelpCategory {
        name: "SYSTEM",
        lines: &[
            "",
            "# EXPRESSIONS",
            "  ALL NUMERIC ARGS ACCEPT EXPRESSIONS:",
            "  PF N ADD A 7",
            "  DC MUL PN.NEXT 0 100",
            "  A RRND 0 127",
            "",
        ],
    },
];

pub const HELP_LINES: &[&str] = &[
    "",
    "# COMMAND NAMING CONVENTION",
    "  PREFIX.SUFFIX - CANONICAL FORM",
    "  EXAMPLES: POSC.FREQ, FILT.CUT, AENV.ATK",
    "  SHORT FORMS REMAIN AS ALIASES (PF, FC, AD)",
    "  USE WHICHEVER FORM YOU PREFER",
    "",
    "# NAVIGATION",
    "  [ ]           CYCLE PAGES",
    "  ESC           TOGGLE HELP",
    "  F1-F8         SCRIPT 1-8",
    "  F9            LIVE PAGE",
    "  F10           METRO PAGE",
    "  F11           INIT PAGE",
    "  F12           PATTERN PAGE",
    "  CTRL+UP/DN    SCROLL REPL OUTPUT (LIVE PAGE)",
    "",
    "# EDITING (SCRIPT PAGES)",
    "  UP/DOWN       SELECT LINE",
    "  ENTER         SAVE LINE",
    "  CTRL+D        DUPLICATE LINE",
    "  CTRL+K        DELETE LINE",
    "  CTRL+C        COPY LINE",
    "  CTRL+X        CUT LINE",
    "  CTRL+V        PASTE LINE",
    "  CTRL+L/R      WORD MOVEMENT",
    "",
    "# TRIGGER & VOLUME",
    "  TR                 TRIGGER VOICE",
    "  OUT.VOL / VOL 0-1  MASTER VOLUME",
    "  SLEW.ALL <MS>      PARAM SLEW TIME (0-10000)",
    "  SLEW <P> <MS>      PER-PARAM SLEW TIME",
    "  RST                RESET TO DEFAULTS",
    "  Q/QUIT/EXIT        QUIT APPLICATION",
    "",
    "# REPL UTILITIES",
    "  CLEAR         CLEAR OUTPUT HISTORY",
    "  DEBUG <0-2>   SET VERBOSITY LEVEL",
    "  DEBUG 0       SILENT (ERRORS ONLY)",
    "  DEBUG 1       IMPORTANT (METRO, PRINT)",
    "  DEBUG 2       VERBOSE (ALL PARAMS)",
    "  PRINT \"TEXT\"  OUTPUT LITERAL STRING",
    "  PRINT <EXPR>  EVALUATE & PRINT",
    "  EXAMPLE: PRINT A, PRINT ADD 1 2",
    "",
    "# VARIABLES",
    "  A B C D       GLOBAL ACCUMULATORS",
    "  X Y Z T       GLOBAL ACCUMULATORS",
    "  J K           PER-SCRIPT LOCAL VARS",
    "  I             LOOP COUNTER (IN L)",
    "  EXAMPLE: A 100 (SET), PF A (USE)",
    "",
    "# MATH (COMMAND & EXPRESSION)",
    "  ADD/+ <A> <B>   ADD",
    "  SUB/- <A> <B>   SUBTRACT",
    "  MUL/* <A> <B>   MULTIPLY",
    "  DIV// <A> <B>   DIVIDE",
    "  MOD/% <A> <B>   MODULO",
    "  MAP <V> <I1> <I2> <O1> <O2>",
    "    MAP VALUE FROM INPUT RANGE TO OUTPUT",
    "  EXAMPLE: PF MAP A 0 127 200 2000",
    "",
    "# RANDOM & GENERATORS",
    "  RND <MAX>        0 TO MAX",
    "  RRND <MIN> <MAX> MIN TO MAX",
    "  TOSS             COIN FLIP (0/1)",
    "  EITH <A> <B>     RANDOM CHOICE A OR B",
    "  TOG <A> <B>      ALTERNATE BETWEEN A AND B",
    "",
    "# INLINE SEQUENCES",
    "  SEQ \"<PATTERN>\"  CYCLE THROUGH VALUES",
    "  TOKENS: X (1), _ OR . (0/REST)",
    "          NUMBERS: 100, -12, 0",
    "          NOTES: C3, E3, F#4, Bb2 (SEMITONES)",
    "  STATE: PER-SCRIPT AND PER-PATTERN",
    "  IF SEQ \"X _ X _\": TR      TRIGGER PATTERN",
    "  PF N SEQ \"C3 E3 G3 C4\"    ARPEGGIATE",
    "  A SEQ \"0 1 2 3\"           STORE IN VAR",
    "  PF N Q SEQ \"0 3 5 7\"      WITH QUANTIZATION",
    "",
    "# VOICE RANDOMIZATION",
    "  RND.VOICE  RANDOMIZE ALL OSC/FM PARAMS",
    "  RND.OSC    RANDOMIZE OSCILLATORS (PF/PW/MF/MW)",
    "  RND.FM     RANDOMIZE FM PARAMS (FM/FB/FBA/FBD)",
    "  RND.MOD    RANDOMIZE MODULATION ROUTING",
    "  RND.ENV    RANDOMIZE ENVELOPE SETTINGS",
    "",
    "# FX RANDOMIZATION",
    "  RND.FX     RANDOMIZE ALL EFFECTS",
    "  RND.FILT   RANDOMIZE FILTER PARAMS",
    "  RND.DLY    RANDOMIZE DELAY PARAMS",
    "  RND.VERB   RANDOMIZE REVERB PARAMS",
    "",
    "# PATTERN RANDOMIZATION",
    "  RND.P [MIN] [MAX]     RANDOMIZE WORKING PATTERN",
    "  RND.PN <N> [MIN] [MAX] RANDOMIZE PATTERN N",
    "  RND.PALL [MIN] [MAX]  RANDOMIZE ALL PATTERNS",
    "",
    "# NOTE/PITCH",
    "  N <SEMI>      SEMITONES TO HZ",
    "  N 0 = C3 (131 HZ)",
    "  N 12 = C4, N 21 = A4 (440)",
    "  EXAMPLE: PF N 12, PF N ADD A 7",
    "",
    "# CONTROL FLOW (PRE OPERATORS)",
    "  IF <X>: <CMD>        IF X != 0 (TRUTHY)",
    "  IF <COND>: <CMD>     WITH COMPARISON",
    "  ELIF <COND>: <CMD>   ELSE-IF",
    "  ELSE: <CMD>          ELSE BRANCH",
    "  PROB <0-100>: <CMD>  PROBABILITY %",
    "  EV <N>: <CMD>        EVERY NTH TICK",
    "  SKIP <N>: <CMD>      SKIP EVERY NTH",
    "  L <S> <E>: <CMDS>    LOOP S TO E",
    "  CMD1; CMD2           SUB-COMMANDS",
    "",
    "# COMPARISONS (RETURN 1/0)",
    "  EZ <X>       X == 0 (EQUALS ZERO)",
    "  NZ <X>       X != 0 (NOT ZERO)",
    "  EQ <A> <B>   A == B",
    "  NE <A> <B>   A != B",
    "  GT <A> <B>   A > B",
    "  LT <A> <B>   A < B",
    "  GTE <A> <B>  A >= B",
    "  LTE <A> <B>  A <= B",
    "  ALSO: > < >= <= == != IN COND",
    "",
    "# SCENES",
    "  SAVE <NAME>   SAVE SCRIPTS+PATTERNS",
    "  LOAD <NAME>   LOAD SCENE",
    "  SCENES        LIST SAVED SCENES",
    "  DELETE <NAME> DELETE SCENE",
    "",
    "# PRESETS",
    "  PSET <SCRIPT> <NAME>      LOAD PRESET INTO SCRIPT 1-8",
    "  PSET.SAVE <SCRIPT> <NAME> SAVE SCRIPT AS USER PRESET",
    "  PSET.DEL <NAME>           DELETE USER PRESET",
    "  PSETS                     LIST ALL PRESETS",
    "  [F] = FACTORY (READ-ONLY), [U] = USER",
    "  EXAMPLES: PSET 1 808-KICK, PSET.SAVE 2 MY-BASS",
    "",
    "# RECORDING",
    "  REC           START RECORDING (WAV)",
    "  REC.STOP      STOP RECORDING",
    "  REC.PATH <P>  SET PATH PREFIX",
    "",
    "# BEAT REPEAT",
    "  BR.ACT <0|1>  ENABLE BEAT REPEAT",
    "  BR.LEN <0-7>  LOOP DIV (0=1/16...7=8X)",
    "  BR.REV <0|1>  REVERSE PLAYBACK",
    "  BR.WIN <1-50> WINDOW SIZE (MS)",
    "  BR.MIX <0-16383> BEAT REPEAT MIX",
    "",
    "# PITCH SHIFT",
    "  PS.MODE <0|1>   MODE (NORMAL/GRANULAR)",
    "  PS.SEMI <-24-24> SHIFT (SEMITONES)",
    "  PS.GRAIN <5-100> GRAIN SIZE (MS)",
    "  PS.MIX <0-16383> PITCH SHIFT MIX",
    "  PS.TARG <0|1>    TARGET (INPUT/OUTPUT)",
    "",
    "# OSCILLATORS",
    "  POSC.FREQ / PF <HZ>    PRIMARY FREQ (20-20000)",
    "  POSC.WAVE / PW <0-2>   PRIMARY WAVE (SIN/TRI/SAW)",
    "  MOSC.FREQ / MF <HZ>    MOD FREQ (20-20000)",
    "  MOSC.WAVE / MW <0-2>   MOD WAVE (SIN/TRI/SAW)",
    "",
    "# FM SYNTHESIS",
    "  MBUS.FM / FM <0-16383> FM INDEX",
    "  FMEV.AMT / FA <0-16383> FM ENV AMOUNT",
    "  FMEV.DEC / FD <MS>     FM ENV DECAY",
    "",
    "# FEEDBACK FM",
    "  MOSC.FB / FB <0-16383>  FEEDBACK AMOUNT",
    "  FBEV.AMT / FBA <0-16383> FEEDBACK ENV AMOUNT",
    "  FBEV.DEC / FBD <MS>     FEEDBACK ENV DECAY",
    "",
    "# DISCONTINUITY",
    "  DISC.AMT / DC <0-16383> DISCONTINUITY AMOUNT",
    "  DENV.AMT / DA <0-16383> DC ENV AMOUNT",
    "  DENV.DEC / DD <MS>      DC ENV DECAY",
    "  DISC.MODE / DM <0-6>    MODE (FOLD/TANH/...)",
    "",
    "# LO-FI",
    "  LOFI.BIT / LB <1-16>    BIT DEPTH (16=CLEAN)",
    "  LOFI.SMP / LS <100-48K> SAMPLE RATE (HZ)",
    "  LOFI.MIX / LM <0-16383> LO-FI MIX",
    "",
    "# SVF FILTER",
    "  FILT.CUT / FC <HZ>      CUTOFF FREQ (20-20000)",
    "  FILT.RES / FQ <0-16383> RESONANCE",
    "  FILT.TYP / FT <0-3>     TYPE (LP/HP/BP/NOTCH)",
    "  FLEV.AMT / FE <0-16383> FILTER ENV AMOUNT",
    "  FLEV.DEC / FED <MS>     FILTER ENV DECAY",
    "  FILT.KEY / FK <0-16383> KEY TRACKING",
    "  ROUT.MF / MF.F <0-1>    MOD BUS -> FILTER",
    "",
    "# RING MOD",
    "  RING.FRQ / RGF <20-2000> RING MOD FREQ (HZ)",
    "  RING.WAV / RGW <0-3>     WAVEFORM (SIN/TRI/SAW/SQR)",
    "  RING.MIX / RGM <0-16383> RING MOD MIX",
    "",
    "# COMB RESONATOR",
    "  RESO.FRQ / RF <HZ>      RESONATOR FREQ",
    "  RESO.DEC / RD <MS>      RESONATOR DECAY",
    "  RESO.MIX / RM <0-16383> RESONATOR MIX",
    "  RESO.KEY / RK <0-16383> RESONATOR KEY TRACK",
    "",
    "# COMPRESSOR",
    "  COMP.THR / CT <0-16383> THRESHOLD",
    "  COMP.RAT / CR <1-20>    RATIO",
    "  COMP.ATK / CA <1-500>   ATTACK (MS)",
    "  COMP.REL / CL <10-2000> RELEASE (MS)",
    "  COMP.MKP / CM <0-16383> MAKEUP GAIN",
    "",
    "# PAN",
    "  OUT.PAN / PAN <-16K-16K> STEREO POSITION",
    "",
    "# AMPLITUDE ENVELOPE",
    "  AENV.DEC / AD <MS>       DECAY TIME (1-10000)",
    "  AENV.ATK <MS>            ATTACK TIME (1-10000)",
    "  AENV.CRV <V>             CURVE SHAPE (-8 TO 8)",
    "",
    "# PITCH ENVELOPE",
    "  PENV.AMT / PA <OCTAVES>  ENVELOPE AMOUNT (0-16)",
    "  PENV.DEC / PD <MS>       DECAY TIME (1-10000)",
    "  PENV.ATK <MS>            ATTACK TIME (1-10000)",
    "  PENV.CRV <V>             CURVE SHAPE (-8 TO 8)",
    "",
    "# FM ENVELOPE",
    "  FMEV.AMT / FA <0-16383>  ENVELOPE AMOUNT",
    "  FMEV.DEC / FD <MS>       DECAY TIME (1-10000)",
    "  FMEV.ATK <MS>            ATTACK TIME (1-10000)",
    "  FMEV.CRV <V>             CURVE SHAPE (-8 TO 8)",
    "",
    "# DISCONTINUITY ENVELOPE",
    "  DENV.AMT / DA <0-16383>  ENVELOPE AMOUNT",
    "  DENV.DEC / DD <MS>       DECAY TIME (1-10000)",
    "  DENV.ATK <MS>            ATTACK TIME (1-10000)",
    "  DENV.CRV <V>             CURVE SHAPE (-8 TO 8)",
    "",
    "# FEEDBACK ENVELOPE",
    "  FBEV.AMT / FBA <0-16383> ENVELOPE AMOUNT",
    "  FBEV.DEC / FBD <MS>      DECAY TIME (1-10000)",
    "  FBEV.ATK <MS>            ATTACK TIME (1-10000)",
    "  FBEV.CRV <V>             CURVE SHAPE (-8 TO 8)",
    "",
    "# FILTER ENVELOPE",
    "  FLEV.AMT / FE <0-16383>  ENVELOPE AMOUNT",
    "  FLEV.DEC / FED <MS>      DECAY TIME (1-10000)",
    "  FLEV.ATK <MS>            ATTACK TIME (1-10000)",
    "  FLEV.CRV <V>             CURVE SHAPE (-8 TO 8)",
    "",
    "# MOD BUS",
    "  MBUS.AMT / MB <0-16383> MOD BUS AMOUNT",
    "  MBUS.TRK / TK <0-16383> TRACKING AMOUNT",
    "  ROUT.MP / MP <0|1>      MOD -> PRIMARY FREQ",
    "  ROUT.MD / MD <0|1>      MOD -> DISCONTINUITY",
    "  ROUT.MT / MT <0|1>      MOD -> TRACKING",
    "  ROUT.MA / MA <0|1>      MOD -> AMPLITUDE",
    "",
    "# MIX",
    "  MBUS.MIX / MX <0-16383> MIX AMOUNT",
    "  MBUS.MMX / MM <0|1>     MOD BUS -> MIX",
    "  MBUS.EMX / ME <0|1>     ENVELOPE -> MIX",
    "",
    "# STEREO DELAY",
    "  DLY.TIME / DT <MS>      DELAY TIME (1-2000)",
    "  DLY.FB / DF <0-16383>   DELAY FEEDBACK",
    "  DLY.LP / DLP <HZ>       DELAY LP FILTER",
    "  DLY.WET / DW <0-16383>  DELAY WET MIX",
    "  DLY.SYN / DS <0-16383>  DELAY STEREO WIDTH",
    "",
    "# DELAY ROUTING",
    "  DLY.MODE / D.MODE <0-2> BYPASS/INSERT/SEND",
    "  DLY.TAIL / D.TAIL <0-2> CUT/RING/FREEZE",
    "",
    "# 3-BAND EQ",
    "  EQ.LOW / EL <-24-24>    LOW SHELF (DB)",
    "  EQ.MID / EM <-24-24>    MID PEAK (DB)",
    "  EQ.FRQ / EF <200-8000>  MID FREQ (HZ)",
    "  EQ.Q <0.1-10>           MID Q",
    "  EQ.HI / EH <-24-24>     HIGH SHELF (DB)",
    "",
    "# PLATE REVERB",
    "  REV.DEC / RV <0-16383>  REVERB DECAY",
    "  REV.PRE / RP <MS>       REVERB PRE-DELAY",
    "  REV.DMP / RH <0-16383>  REVERB DAMPING (HI)",
    "  REV.WET / RW <0-16383>  REVERB WET MIX",
    "",
    "# REVERB ROUTING",
    "  REV.MODE / R.MODE <0-2> BYPASS/INSERT/SEND",
    "  REV.TAIL / R.TAIL <0-2> CUT/RING/FREEZE",
    "",
    "# METRO",
    "  M             SHOW INTERVAL",
    "  M <MS>        SET INTERVAL",
    "  M.BPM <BPM>   SET BPM",
    "  M.ACT <0|1>   START/STOP",
    "  M.SCRIPT <1-8>  SCRIPT FOR METRO",
    "",
    "# SCRIPTS",
    "  SCRIPT <1-8>  EXECUTE STORED SCRIPT",
    "",
    "# DELAYED EXECUTION",
    "  DEL <MS>: <CMD>     EXECUTE CMD AFTER MS",
    "  DEL.CLR             CLEAR PENDING DELAYS",
    "  DEL.X <N> <MS>: CMD REPEAT N TIMES AT MS INTERVALS",
    "  DEL.R <N> <MS>: CMD EXEC NOW + REPEAT N-1 TIMES",
    "  MAX DELAY: 16000MS",
    "",
    "# COUNTERS",
    "  N1-N4         READ VALUE + AUTO-INCREMENT",
    "  N1.MIN <N>    SET MINIMUM (DEFAULT 0)",
    "  N1.MAX <N>    SET MAXIMUM (WRAPS BACK)",
    "  N1.RST        RESET TO MIN",
    "  EXAMPLE: N1.MIN 10; N1.MAX 14",
    "  CYCLES: 10, 11, 12, 13, 14, 10...",
    "",
    "# PATTERNS (WORKING - P.N)",
    "  P.N           GET WORKING PATTERN",
    "  P.N <0-5>     SET WORKING PATTERN",
    "  P.L / P.L <N> GET/SET LENGTH",
    "  P.I / P.I <N> GET/SET INDEX",
    "  P.HERE        VALUE AT INDEX",
    "  P.NEXT        ADVANCE, GET VALUE",
    "  P.PREV        REVERSE, GET VALUE",
    "  P <I> / P <I> <V>  GET/SET AT INDEX",
    "",
    "# PATTERNS (EXPLICIT - PN)",
    "  PN.L <P> / PN.L <P> <N>  LENGTH",
    "  PN.I <P> / PN.I <P> <N>  INDEX",
    "  PN.HERE <P>              VALUE",
    "  PN.NEXT <P>              ADVANCE",
    "  PN.PREV <P>              REVERSE",
    "  PN <P> <I> / PN <P> <I> <V>",
    "",
    "# EXPRESSIONS",
    "  ALL NUMERIC ARGS ACCEPT EXPRESSIONS:",
    "  PF N ADD A 7",
    "  DC MUL PN.NEXT 0 100",
    "  A RRND 0 127",
    "",
];
