pub struct HelpCategory {
    pub name: &'static str,
    pub lines: &'static [&'static str],
}

pub const HELP_CATEGORIES: &[HelpCategory] = &[
    HelpCategory {
        name: "NAVIGATION & EDITING",
        lines: &[
            "",
            "# COMMAND NAMING CONVENTION",
            "  PREFIX.SUFFIX - CANONICAL",
            "  EX: POSC.FREQ, FILT.CUT, AENV.ATK",
            "  SHORT FORMS AS ALIAS (PF, FC, AD)",
            "  USE WHICHEVER FORM YOU PREFER",
            "",
            "# NAVIGATION",
            "  [ ]           CYCLE PAGES",
            "  ESC           TOGGLE HELP",
            "",
            "# FUNCTION KEYS (ALL TERMINALS)",
            "  F1-F8         SCRIPT 1-8",
            "  F9            LIVE PAGE",
            "  F10           METRO PAGE",
            "  F11           INIT PAGE",
            "  F12           PATTERN PAGE",
            "",
            "# ALT KEYS (NEED ITERM2 CONFIG)",
            "  ALT+L         LIVE PAGE",
            "  ALT+1 TO 8    SCRIPT 1-8",
            "  ALT+M         METRO PAGE",
            "  ALT+I         INIT PAGE",
            "  ALT+P         PATTERN PAGE",
            "  ALT+S         SCOPE PAGE",
            "  ALT+V         VARIABLES PAGE",
            "  ALT+H         TOGGLE HELP",
            "",
            "# OTHER",
            "  CTRL+UP/DN    SCROLL REPL",
            "  TAB           LIVE / GRID VIEW",
            "",
            "# SEARCH",
            "  CTRL+F        SEARCH MODE",
            "  ENTER         NEXT MATCH",
            "  SHIFT+ENTER   PREVIOUS MATCH",
            "  ESC           EXIT SEARCH",
            "",
            "  HELP PAGE: SEARCHES HELP ONLY",
            "  OTHER PAGES: SEARCHES SCRIPTS",
            "",
            "# EDITING (SCRIPT PAGES)",
            "  UP/DOWN       SELECT LINE",
            "  ENTER         SAVE LINE",
            "  CTRL+D        DUPLICATE LINE (PUSH DOWN)",
            "  CTRL+K        DELETE LINE",
            "  CTRL+C        COPY LINE",
            "  CTRL+X        CUT LINE",
            "  CTRL+V        PASTE LINE",
            "  CTRL+L/R      WORD MOVEMENT",
            "",
            "# TRIGGER & VOLUME",
            "  TR            TRIGGER VOICE",
            "  OUT.VOL / VOL 0-1  MASTER VOL",
            "  VCA <0|1>     0=DRONE 1=GATED",
            "  SLEW.ALL <MS>  SLEW MS (0-10000)",
            "  SLEW <P> <MS>  PER-PARAM SLEW",
            "  FLASH <MS>     HOLD MS (DEF 200)",
            "  RST            RESET TO DEF",
            "  LOAD.RST       RST MODE (0=KEEP 1=RST)",
            "  LOAD.RST <0|1> SCENE LOAD MODE",
            "  LOAD.CLR <0|1> AUTO-CLEAR ON LOAD",
            "  Q/QUIT/EXIT    QUIT APP",
            "",
            "# REPL UTILITIES",
            "  CLEAR / CLR   CLEAR OUTPUT",
            "  DEBUG <0-5>   VERBOSITY TIER",
            "  DEBUG 0       SILENT (USE OVERRIDES)",
            "  DEBUG 1       ERRORS",
            "  DEBUG 2       + STATE CHANGES",
            "  DEBUG 3       + VALUE READS",
            "  DEBUG 4       + SET CONFIRMS",
            "  DEBUG 5       + VERBOSE (ALL)",
            "  OUT.ERR <0|1> OVERRIDE: SHOW ERRORS",
            "  OUT.ESS <0|1> OVERRIDE: SHOW ESSENTIAL",
            "  OUT.QRY <0|1> OVERRIDE: SHOW QUERIES",
            "  OUT.CFM <0|1> OVERRIDE: SHOW CONFIRMS",
            "  HEADER        SHOW HDR VERB",
            "  HEADER <0-4>  SET HDR VERBOSE",
            "  HEADER 0      NAV ONLY",
            "  HEADER 1      NAV + METERS",
            "  HEADER 2      NAV + MET + TR",
            "  HEADER 3      FULL NAV + MET + TR",
            "  HEADER 4      FULL + CPU (DEF)",
            "  PRINT \"TEXT\"  OUTPUT STRING",
            "  PRINT <EXPR>  EVAL & PRINT",
            "  EX: PRINT A, PRINT ADD 1 2",
            "",
            "# NOTES PAGE",
            "  NOTE \"TEXT\"   APPEND NOTE",
            "  NOTE.CLR      CLEAR ALL NOTES",
            "  SAVED WITH SCENES",
            "",
        ],
    },
    HelpCategory {
        name: "VARIABLES & MATH",
        lines: &[
            "",
            "# VARIABLES",
            "  A B C D       GLOBAL ACCUM",
            "  X Y Z T       GLOBAL ACCUM",
            "  J K           LOCAL VARS",
            "  I             LOOP COUNTER",
            "  EX: A 100 (SET), PF A (USE)",
            "",
            "# MATH (COMMAND & EXPRESSION)",
            "  ADD/+ <A> <B>   ADD",
            "  SUB/- <A> <B>   SUBTRACT",
            "  MUL/* <A> <B>   MULTIPLY",
            "  DIV// <A> <B>   DIVIDE",
            "  MOD/% <A> <B>   MODULO",
            "  MAP <V> <I1> <I2> <O1> <O2>",
            "    MAP VAL IN RANGE -> OUT",
            "  EX: PF MAP A 0 127 200 2000",
            "",
            "# RANDOM & GENERATORS",
            "  RND <MAX>        0 TO MAX",
            "  RRND <MIN> <MAX> MIN TO MAX",
            "  TOSS             COIN FLIP",
            "  EITH <A> <B>     RAND A OR B",
            "  TOG <A> <B>      ALT A/B",
            "",
            "# INLINE SEQUENCES",
            "  SEQ \"<PATTERN>\"  CYCLE VALS",
            "  TOKENS:",
            "    X           TRIGGER (RET 1)",
            "    _ OR .      REST (RET 0)",
            "    ?           RAND (50% 1, 50% 0)",
            "    NUMBERS     100, -12, 0",
            "    NOTES       C3, E3, F#4, Bb2",
            "  MODIFIERS:",
            "    *N          REPEAT N (C3*4 = C3 C3...)",
            "    <A B>       TOG (LIKE TOG)",
            "    {A B>       RAND (LIKE EITH)",
            "  STATE: PER-SCRIPT, PER-PATT",
            "  EXAMPLES:",
            "    SEQ \"X _ X _\"     TRIG PATT",
            "    SEQ \"C3*4 E3*2\"   REPEAT NOTES",
            "    SEQ \"<C3 E3> G3\"  TOG C3/E3, G3",
            "    SEQ \"{C3 E3} G3\"  RAND C3/E3, G3",
            "    SEQ \"X ? X ?\"     RANDOM TRIGGERS",
            "    SEQ \"<C3 E3>*2\"   TWO TOGGLES",
            "    SEQ \"{C3 E3}*2\"   TWO RANDOMS",
            "",
            "# VOICE RANDOMIZATION",
            "  RND.VOICE  RAND ALL OSC/FM",
            "  RND.OSC    RAND OSC (PF/PW/MF/MW)",
            "  RND.FM     RAND FM (FM/FB/FBA/FBD)",
            "  RND.MOD    RAND MOD ROUTING",
            "  RND.ENV    RAND ENVELOPES",
            "",
            "# FX RANDOMIZATION",
            "  RND.FX     RAND ALL FX",
            "  RND.FILT   RAND FILTER",
            "  RND.DLY    RAND DELAY",
            "  RND.VERB   RAND REVERB",
            "",
            "# PATTERN RANDOMIZATION",
            "  RND.P [MIN] [MAX]      RAND WORK PATT",
            "  RND.PN <N> [MIN] [MAX] RAND PATT N",
            "  RND.PALL [MIN] [MAX]   RAND ALL PATT",
            "",
            "# NOTE/PITCH",
            "  N <SEMI>      SEMITONES TO HZ",
            "  N 0 = C3 (131 HZ)",
            "  N 12 = C4, N 21 = A4 (440)",
            "  EX: PF N 12, PF N ADD A 7",
            "",
        ],
    },
    HelpCategory {
        name: "CONTROL FLOW",
        lines: &[
            "",
            "# CONTROL FLOW (PRE OPERATORS)",
            "  IF <X>: <CMD>        IF X != 0",
            "  IF <COND>: <CMD>     WITH COMPARE",
            "  ELIF <COND>: <CMD>   ELSE-IF",
            "  ELSE: <CMD>          ELSE",
            "  PROB <0-100>: <CMD>  PROB %",
            "  EV <N>: <CMD>        EVERY NTH",
            "  SKIP <N>: <CMD>      SKIP NTH",
            "  L <S> <E>: <CMDS>    LOOP S-E",
            "  BRK                  STOP SCRIPT",
            "  CMD1; CMD2           SUB-CMDS",
            "",
            "# IF/ELIF/ELSE SCOPE",
            "  SCOPE IS SCRIPT-LOCAL (MULTI-LINE)",
            "  IF STARTS NEW CHAIN, RESETS STATE",
            "  ELIF/ELSE CHECK PRIOR IF IN SCRIPT",
            "  WORKS ACROSS LINES & SEMICOLONS",
            "  EX: IF A > 5: TR",
            "      ELIF A > 2: PF 200",
            "      ELSE: PF 100",
            "  NOTE: NEW IF RESETS CHAIN STATE",
            "",
            "# COMPARISONS (RETURN 1/0)",
            "  EZ <X>       X == 0",
            "  NZ <X>       X != 0",
            "  EQ <A> <B>   A == B",
            "  NE <A> <B>   A != B",
            "  GT <A> <B>   A > B",
            "  LT <A> <B>   A < B",
            "  GTE <A> <B>  A >= B",
            "  LTE <A> <B>  A <= B",
            "  ALSO: > < >= <= == != IN COND",
            "",
            "# SCENES",
            "  SAVE <NAME>   SAVE SCRIPTS+PATT",
            "  LOAD <NAME>   LOAD SCENE",
            "  SCENES        LIST SCENES",
            "  DELETE <NAME> DELETE SCENE",
            "  AUTOLOAD <0|1> AUTO-LOAD LAST SCENE",
            "",
            "# PRESETS",
            "  PSET <SCRIPT> <NAME>      LOAD TO 1-8",
            "  PSET.SAVE <SCRIPT> <NAME> SAVE AS USER",
            "  PSET.DEL <NAME>           DEL USER",
            "  PSETS                     LIST ALL",
            "  [F] = FACTORY, [U] = USER",
            "  EX: PSET 1 808-KICK, PSET.SAVE 2 BASS",
            "",
            "# RECORDING",
            "  REC           START REC (WAV)",
            "  REC.STOP      STOP RECORDING",
            "  REC.PATH <P>  SET PATH PREFIX",
            "",
        ],
    },
    HelpCategory {
        name: "PATTERNS",
        lines: &[
            "",
            "# PATTERNS (WORKING - P.N)",
            "  P.N           GET WORK PATT",
            "  P.N <0-5>     SET WORK PATT",
            "  P.L / P.L <N> GET/SET LENGTH",
            "  P.I / P.I <N> GET/SET INDEX",
            "  P.HERE        VALUE AT INDEX",
            "  P.NEXT        ADVANCE, GET VAL",
            "  P.PREV        REVERSE, GET VAL",
            "  P <I> / P <I> <V>  GET/SET AT I",
            "",
            "# PATTERNS (EXPLICIT - PN)",
            "  PN.L <P> / PN.L <P> <N>  LEN",
            "  PN.I <P> / PN.I <P> <N>  IDX",
            "  PN.HERE <P>              VAL",
            "  PN.NEXT <P>              ADV",
            "  PN.PREV <P>              REV",
            "  PN <P> <I> / PN <P> <I> <V>",
            "",
            "# PATTERN MANIPULATION",
            "  P.PUSH <V>     PUSH VAL, SHIFT LEFT",
            "  P.POP          POP & RETURN LAST VAL",
            "  P.INS <I> <V>  INSERT VAL AT INDEX",
            "  P.RM <I>       REMOVE VAL AT INDEX",
            "  P.REV          REVERSE PATTERN",
            "  P.ROT <N>      ROTATE BY N STEPS",
            "  P.SHUF         SHUFFLE RANDOMLY",
            "  P.SORT         SORT ASCENDING",
            "  P.RND [MIN] [MAX]  RANDOMIZE VALUES",
            "  P.CLR          CLEAR (SET ALL TO 0)",
            "",
            "# PATTERN MATH",
            "  P.ADD <V>      ADD TO ALL VALUES",
            "  P.SUB <V>      SUBTRACT FROM ALL",
            "  P.MUL <V>      MULTIPLY ALL VALUES",
            "  P.DIV <V>      DIVIDE ALL VALUES",
            "  P.MOD <V>      MODULO ALL VALUES",
            "  P.SCALE <MIN> <MAX> SCALE TO NEW RANGE",
            "",
            "# PATTERN QUERIES",
            "  P.MIN          GET MINIMUM VALUE",
            "  P.MAX          GET MAXIMUM VALUE",
            "  P.SUM          GET SUM OF ALL",
            "  P.AVG          GET AVERAGE VALUE",
            "  P.FND <V>      FIND INDEX OF VAL (-1)",
            "",
            "  NOTE: PN.* VARIANTS TAKE PATTERN",
            "  NUMBER AS FIRST ARG (EX: PN.ADD 0 5)",
            "",
            "# COUNTERS",
            "  N1-N4         READ VAL + AUTO-INC",
            "  N1.MIN <N>    SET MIN (DEF 0)",
            "  N1.MAX <N>    SET MAX (WRAPS)",
            "  N1.RST        RESET TO MIN",
            "  EX: N1.MIN 10; N1.MAX 14",
            "  CYCLES: 10, 11, 12, 13, 14, 10...",
            "",
            "# STATE SYNCHRONIZATION",
            "  SYNC          RESET ALL STATE",
            "  SYNC.SEQ      RESET SEQ STATE",
            "  SYNC.TOG      RESET TOG/EITH STATE",
            "  SYNC.PAT      RESET PATTERN INDICES",
            "",
        ],
    },
    HelpCategory {
        name: "SCALE QUANTIZATION",
        lines: &[
            "",
            "# SCALE QUANTIZATION",
            "  Q <NOTE>       QUANT NOTE TO SCALE",
            "  Q.ROOT <0-11>  ROOT (C=0...B=11)",
            "  Q.SCALE <0-11> SCALE TYPE",
            "  Q.BIT <BINARY> CUSTOM SCALE MASK",
            "",
            "# SCALE TYPES",
            "  0=CHROM  1=MAJ      2=MIN",
            "  3=DOR    4=PHRYG    5=LYD",
            "  6=MIXO   7=PENT MAJ 8=PENT MIN",
            "  9=BLUES 10=WHOLE  11=DIM",
            "",
            "# Q.BIT EXAMPLES",
            "  Q.BIT 101010110101  MAJ (12-TET)",
            "  Q.BIT 10101         PENT (5-EDO)",
            "  Q.BIT <24 BITS>     QUARTER-TONE",
            "",
            "# USAGE",
            "  PF N Q A           QUANT A TO HZ",
            "  PF N Q P.NEXT      PATT TO SCALE",
            "",
        ],
    },
    HelpCategory {
        name: "OSCILLATORS & FM",
        lines: &[
            "",
            "# OSCILLATORS",
            "  POSC.FREQ / PF <HZ>    PRI FREQ (20-20K)",
            "  POSC.WAVE / PW <0-2>   PRI (SIN/TRI/SAW)",
            "  MOSC.FREQ / MF <HZ>    MOD FREQ (20-20K)",
            "  MOSC.WAVE / MW <0-2>   MOD (SIN/TRI/SAW)",
            "",
            "# FM SYNTHESIS",
            "  MBUS.FM / FM <0-16383> FM IDX",
            "  FMEV.AMT / FA <0-16383> FM ENV AMT",
            "  FMEV.DEC / FD <MS>     FM ENV DEC",
            "",
            "# FEEDBACK FM",
            "  MOSC.FB / FB <0-16383>  FB AMT",
            "  FBEV.AMT / FBA <0-16383> FB ENV AMT",
            "  FBEV.DEC / FBD <MS>     FB ENV DEC",
            "",
            "# DISCONTINUITY",
            "  DISC.AMT / DC <0-16383> DISC AMT",
            "  DENV.AMT / DA <0-16383> DC ENV AMT",
            "  DENV.DEC / DD <MS>      DC ENV DEC",
            "  DISC.MODE / DM <0-6>    MODE (FOLD/TANH)",
            "",
            "# LO-FI",
            "  LOFI.BIT / LB <1-16>    BIT (16=CLEAN)",
            "  LOFI.SMP / LS <100-48K> SAMP RATE",
            "  LOFI.MIX / LM <0-16383> MIX",
            "",
            "# MOD BUS",
            "  MBUS.AMT / MB <0-16383> MOD AMT",
            "  MBUS.TRK / TK <0-16383> TRACK AMT",
            "  ROUT.MP / MP <0|1>      MOD -> PRI FREQ",
            "  ROUT.MD / MD <0|1>      MOD -> DISC",
            "  ROUT.MT / MT <0|1>      MOD -> TRACK",
            "  ROUT.MA / MA <0|1>      MOD -> AMP",
            "",
            "# MIX",
            "  MBUS.MIX / MX <0-16383> MIX AMT",
            "  MBUS.MMX / MM <0|1>     MOD -> MIX",
            "  MBUS.EMX / ME <0|1>     ENV -> MIX",
            "",
        ],
    },
    HelpCategory {
        name: "ENVELOPES",
        lines: &[
            "",
            "# AMPLITUDE ENVELOPE",
            "  AENV.DEC / AD <MS>       DEC (1-10K)",
            "  AENV.ATK / AA <MS>       ATK (1-10K)",
            "  AENV.CRV / AC <V>        CRV (-8 TO 8)",
            "",
            "# PITCH ENVELOPE",
            "  PENV.AMT / PA <OCTAVES>  AMT (0-16)",
            "  PENV.DEC / PD <MS>       DEC (1-10K)",
            "  PENV.ATK / PAA <MS>      ATK (1-10K)",
            "  PENV.CRV / PC <V>        CRV (-8 TO 8)",
            "",
            "# FM ENVELOPE",
            "  FMEV.AMT / FA <0-16383>  AMT",
            "  FMEV.DEC / FD <MS>       DEC (1-10K)",
            "  FMEV.ATK / FAA <MS>      ATK (1-10K)",
            "  FMEV.CRV <V>             CRV (-8 TO 8)",
            "",
            "# DISCONTINUITY ENVELOPE",
            "  DENV.AMT / DA <0-16383>  AMT",
            "  DENV.DEC / DD <MS>       DEC (1-10K)",
            "  DENV.ATK / DAA <MS>      ATK (1-10K)",
            "  DENV.CRV <V>             CRV (-8 TO 8)",
            "",
            "# FEEDBACK ENVELOPE",
            "  FBEV.AMT / FBA <0-16383> AMT",
            "  FBEV.DEC / FBD <MS>      DEC (1-10K)",
            "  FBEV.ATK / FBAA <MS>     ATK (1-10K)",
            "  FBEV.CRV / FBC <V>       CRV (-8 TO 8)",
            "",
            "# FILTER ENVELOPE",
            "  FLEV.AMT / FE <0-16383>  AMT",
            "  FLEV.DEC / FED <MS>      DEC (1-10K)",
            "  FLEV.ATK / FLAA <MS>     ATK (1-10K)",
            "  FLEV.CRV / FLC <V>       CRV (-8 TO 8)",
            "",
            "# NOTE",
            "  FMEV.CRV, DENV.CRV: NO SHORT ALIAS",
            "  FC = FILT CUT, DC = DISC AMT",
            "",
        ],
    },
    HelpCategory {
        name: "FILTER & EFFECTS",
        lines: &[
            "",
            "# SVF FILTER",
            "  FILT.CUT / FC <HZ>      CUT (20-20K)",
            "  FILT.RES / FQ <0-16383> RES",
            "  FILT.TYP / FT <0-3>     TYP (LP/HP/BP/N)",
            "  FLEV.AMT / FE <0-16383> ENV AMT",
            "  FLEV.DEC / FED <MS>     ENV DEC",
            "  FILT.KEY / FK <0-16383> KEY TRACK",
            "  ROUT.MF / MF.F <0-1>    MOD -> FILT",
            "",
            "# RING MOD",
            "  RING.FRQ / RGF <20-2000> FREQ",
            "  RING.WAV / RGW <0-3>     WAV (SIN/TRI/SAW)",
            "  RING.MIX / RGM <0-16383> MIX",
            "",
            "# COMB RESONATOR",
            "  RESO.FRQ / RF <HZ>      FREQ",
            "  RESO.DEC / RD <MS>      DECAY",
            "  RESO.MIX / RM <0-16383> MIX",
            "  RESO.KEY / RK <0-16383> KEY TRACK",
            "",
            "# COMPRESSOR",
            "  COMP.THR / CT <0-16383> THR",
            "  COMP.RAT / CR <1-20>    RATIO",
            "  COMP.ATK / CA <1-500>   ATK MS",
            "  COMP.REL / CL <10-2000> REL MS",
            "  COMP.MKP / CM <0-16383> MAKEUP",
            "",
            "# PAN",
            "  OUT.PAN / PAN <-16K-16K> STEREO POS",
            "",
            "# BEAT REPEAT",
            "  BR.LEN <0-7>  DIV (0=1/16...7=8X)",
            "  BR.REV <0|1>  REVERSE",
            "  BR.WIN <1-50> WIN MS",
            "  BR.MIX <0-16383> MIX (ACTIVATES)",
            "",
            "# PITCH SHIFT",
            "  PS.MODE <0|1>   MODE (NORM/GRAN)",
            "  PS.SEMI <-24-24> SEMI",
            "  PS.GRAIN <5-100> GRAIN MS",
            "  PS.MIX <0-16383> MIX",
            "  PS.TARG <0|1>    TARG (IN/OUT)",
            "",
            "# 3-BAND EQ",
            "  EQ.LOW / EL <-24-24>    LOW DB",
            "  EQ.MID / EM <-24-24>    MID DB",
            "  EQ.FRQ / EF <200-8000>  MID FREQ",
            "  EQ.Q <0.1-10>           MID Q",
            "  EQ.HI / EH <-24-24>     HI DB",
            "",
        ],
    },
    HelpCategory {
        name: "DELAY & REVERB",
        lines: &[
            "",
            "# STEREO DELAY",
            "  DLY.TIME / DT <MS>      TIME (1-2000)",
            "  DLY.FB / DF <0-16383>   FEEDBACK",
            "  DLY.LP / DLP <HZ>       LP FILT",
            "  DLY.WET / DW <0-16383>  WET MIX",
            "  DLY.SYN / DS <0-16383>  STEREO WID",
            "",
            "# DELAY ROUTING",
            "  DLY.MODE / D.MODE <0-2> BYP/INS/SND",
            "  DLY.TAIL / D.TAIL <0-2> CUT/RNG/FRZ",
            "",
            "# PLATE REVERB",
            "  REV.DEC / RV <0-16383>  DECAY",
            "  REV.PRE / RP <MS>       PRE-DLY",
            "  REV.DMP / RH <0-16383>  DAMP (HI)",
            "  REV.WET / RW <0-16383>  WET MIX",
            "",
            "# REVERB ROUTING",
            "  REV.MODE / R.MODE <0-2> BYP/INS/SND",
            "  REV.TAIL / R.TAIL <0-2> CUT/RNG/FRZ",
            "",
        ],
    },
    HelpCategory {
        name: "METRO & SCRIPTS",
        lines: &[
            "",
            "# METRO",
            "  M             SHOW INTERVAL",
            "  M <MS>        SET INTERVAL",
            "  M.BPM <BPM>   SET BPM",
            "  M.ACT <0|1>   START/STOP",
            "  M.SCRIPT <1-8>  METRO SCRIPT",
            "",
            "# MIDI CLOCK SYNC",
            "  M.SYNC         SHOW SYNC MODE",
            "  M.SYNC <0|1>   SET SYNC MODE",
            "    0 = INTERNAL (DEFAULT)",
            "    1 = MIDI CLOCK (16TH NOTES)",
            "  MIDI.IN        LIST INPUTS",
            "  MIDI.IN <NAME> CONNECT DEV",
            "  NOTE: CONNECT FIRST, M.SYNC 1",
            "  TRANSPORT: START/STOP W/ MIDI",
            "",
            "# MIDI CLOCK DIAGNOSTICS",
            "  MIDI.DIAG <0|1>  ON/OFF TIMING",
            "  MIDI.DIAG REPORT WRITE TO FILE",
            "  SC.DIAG <0|1>    ON/OFF SC TIMING",
            "  SC.DIAG REPORT   WRITE TO FILE",
            "  REPORTS: midi_timing_report.txt",
            "           sc_timing_report.txt",
            "",
            "# SCRIPTS",
            "  SCRIPT <1-8>  EXEC SCRIPT",
            "",
            "# DELAYED EXECUTION",
            "  DEL <MS>: <CMD>     EXEC AFTER MS",
            "  DEL.CLR             CLR PENDING",
            "  DEL.X <N> <MS>: CMD REP N TIMES @ MS",
            "  DEL.R <N> <MS>: CMD NOW + REP N-1",
            "  MAX DELAY: 16000MS",
            "",
        ],
    },
    HelpCategory {
        name: "UI & DISPLAY",
        lines: &[
            "",
            "# UI TOGGLES",
            "  METER.HDR <0|1>   HDR METERS",
            "  METER.GRID <0|1>  GRID METERS",
            "  METER.ASCII <0|1> ASCII METER MODE",
            "  SPECTRUM <0|1>    SPECTRUM",
            "  ACTIVITY <0|1>    ACTIVITY IND",
            "  GRID <0|1>        PARAM GRID VIS",
            "  GRID.DEF <0|1>    DEF VIEW (REPL/GRID)",
            "  GRID.MODE <0|1>   LABEL/ICON",
            "  HL.SEQ <0|1>      SEQ/TOG HIGHL",
            "  HL.COND <0|1>     COND HIGHL",
            "  CPU <0|1>         CPU METER",
            "  BPM <0|1>         BPM DISPLAY",
            "  TITLE <0|1>       HDR TITLE MODE",
            "  SCRMBL            QUERY SCRAMBLE ON/OFF",
            "  SCRMBL <0|1>      HEADER SCRAMBLE FX",
            "  SCRMBL.MODE       QUERY SCRAMBLE STYLE",
            "  SCRMBL.MODE <0-3> 0=REG 1=SMASH 2=ROLL 3=OVER",
            "  SCRMBL.SPD        QUERY SCRAMBLE SPEED",
            "  SCRMBL.SPD <1-10> 1=SLOW 10=FAST",
            "  SCRMBL.CRV        QUERY SCRAMBLE CURVE",
            "  SCRMBL.CRV <0|1>  0=LINEAR 1=SETTLE",
            "  HEADER <0-4>      HDR VERBOSE",
            "  DEBUG <0-5>       VERBOSITY TIER",
            "",
            "# OUTPUT VERBOSITY",
            "  DEBUG <0-5>       SET VERBOSITY TIER",
            "  DEBUG 0           SILENT (OVERRIDES ONLY)",
            "  DEBUG 1           ERRORS",
            "  DEBUG 2           + STATE CHANGES",
            "  DEBUG 3           + VALUE READS",
            "  DEBUG 4           + SET CONFIRMS",
            "  DEBUG 5           + VERBOSE (ALL)",
            "  OUT.ERR <0|1>     OVERRIDE: SHOW ERRORS",
            "  OUT.ESS <0|1>     OVERRIDE: ESSENTIAL",
            "  OUT.QRY <0|1>     OVERRIDE: QUERIES",
            "  OUT.CFM <0|1>     OVERRIDE: CONFIRMS",
            "",
            "# TITLE MODE",
            "  TITLE 0           SHOW 'MONOKIT'",
            "  TITLE 1           SHOW SCENE NAME",
            "  TITLE.TIMER       QUERY STATE",
            "  TITLE.TIMER 0     DISABLE TIMER",
            "  TITLE.TIMER 1 <S> CYCLE EVERY <S> SECS (1-1800)",
            "",
            "# HEADER LEVELS (BPM AT 1-4)",
            "  HEADER 0          NAV ONLY",
            "  HEADER 1          NAV + METERS + BPM",
            "  HEADER 2          NAV + MET + TR + BPM",
            "  HEADER 3          FULL NAV + MET + TR",
            "  HEADER 4          FULL + CPU (DEF)",
            "",
        ],
    },
    HelpCategory {
        name: "OSCILLOSCOPE",
        lines: &[
            "",
            "# OSCILLOSCOPE SETTINGS",
            "  SCOPE.TIME <5-500> MS (30)",
            "  SCOPE.CLR <NAME>   COLOR",
            "    FOREGROUND SECONDARY HIGHLIGHT_BG",
            "    HIGHLIGHT_FG BORDER ERROR ACCENT",
            "    SUCCESS LABEL (OR 0-8)",
            "  SCOPE.MODE <0-4>    MODE",
            "    0 = BRAILLE",
            "    1 = BLOCK",
            "    2 = LINE",
            "    3 = DOT",
            "    4 = QUAD",
            "  SCOPE.UNI <0|1>     UNIPOLAR",
            "",
            "  NOTE: SCOPE.MODE 1 (blocks) may render",
            "  better than braille in some terminals.",
            "",
            "# NAVIGATION",
            "  ALT+S OR [ ]       SCOPE PAGE",
            "",
        ],
    },
    HelpCategory {
        name: "SYSTEM",
        lines: &[
            "",
            "# SYSTEM COMMANDS",
            "  VERSION / VER  SHOW VERSION",
            "  RST            RESET TO DEFAULTS",
            "    PF: 131 HZ (C3), MF: 262 HZ (C4)",
            "    PA: 0, FC: 10000 HZ",
            "    D.MODE: 2 (SND), R.MODE: 2 (SND)",
            "    CR: 1 (COMP OFF)",
            "  LOAD.RST       RESET MODE",
            "  LOAD.RST <0|1> SET LOAD MODE",
            "    0 = PERSIST SYNTH (DEF)",
            "    1 = RESET ALL BEFORE LOAD",
            "",
            "# AUDIO OUTPUT",
            "  AUDIO.OUT         LIST OUTPUT DEVICES",
            "  AUDIO.OUT <N>     SET OUTPUT BY NUMBER",
            "",
            "  DEVICE CHANGE RESTARTS AUDIO ENGINE",
            "  SAVED TO CONFIG FOR NEXT LAUNCH",
            "",
            "# TERMINAL COMPAT",
            "  COMPAT             Show capabilities",
            "  COMPAT.MODE        Query mode",
            "  COMPAT.MODE <0|1>  0=Full 1=Basic",
            "  Terminal.app has limited color support.",
            "  For best results use iTerm2 or similar.",
            "  256-color mode auto-enabled when needed.",
            "  Block chars may show gaps - try Monaco.",
            "",
            "# EXPRESSIONS",
            "  ALL NUMERIC ARGS ACCEPT EXPR:",
            "  PF N ADD A 7",
            "  DC MUL PN.NEXT 0 100",
            "  A RRND 0 127",
            "",
        ],
    },
];

pub const HELP_LINES: &[&str] = &[
    "",
    "# COMMAND NAMING CONVENTION",
    "  PREFIX.SUFFIX - CANONICAL FORM",
    "  EX: POSC.FREQ, FILT.CUT, AENV.ATK",
    "  SHORT FORMS AS ALIASES (PF, FC, AD)",
    "  USE WHICHEVER FORM YOU PREFER",
    "",
    "# NAVIGATION",
    "  [ ]           CYCLE PAGES",
    "  ESC           TOGGLE HELP",
    "",
    "# FUNCTION KEYS (WORK IN ALL TERMINALS)",
    "  F1-F8         SCRIPT 1-8",
    "  F9            LIVE PAGE",
    "  F10           METRO PAGE",
    "  F11           INIT PAGE",
    "  F12           PATTERN PAGE",
    "",
    "# ALT KEYS (REQUIRE ITERM2 CONFIG)",
    "  ALT+L         LIVE PAGE",
    "  ALT+1 TO 8    SCRIPT 1-8",
    "  ALT+M         METRO PAGE",
    "  ALT+I         INIT PAGE",
    "  ALT+P         PATTERN PAGE",
    "  ALT+S         SCOPE PAGE",
    "  ALT+V         VARIABLES PAGE",
    "  ALT+H         TOGGLE HELP",
    "",
    "# OTHER",
    "  CTRL+UP/DN    SCROLL REPL (LIVE PAGE)",
    "  TAB           LIVE PG / GRID VIEW",
    "",
    "# SEARCH",
    "  CTRL+F        ENTER SEARCH MODE",
    "  ENTER         NEXT MATCH",
    "  SHIFT+ENTER   PREVIOUS MATCH",
    "  ESC           EXIT SEARCH",
    "",
    "  HELP PAGE: SEARCHES HELP ONLY",
    "  OTHER PAGES: SEARCHES SCRIPTS",
    "",
    "# EDITING (SCRIPT PAGES)",
    "  UP/DOWN       SELECT LINE",
    "  ENTER         SAVE LINE",
    "  CTRL+D        DUPLICATE LINE (PUSH DOWN)",
    "  CTRL+K        DELETE LINE",
    "  CTRL+C        COPY LINE",
    "  CTRL+X        CUT LINE",
    "  CTRL+V        PASTE LINE",
    "  CTRL+L/R      WORD MOVEMENT",
    "",
    "# TRIGGER & VOLUME",
    "  TR                 TRIGGER VOICE",
    "  OUT.VOL / VOL 0-1  MASTER VOLUME",
    "  VCA <0|1>          0=DRONE 1=GATED",
    "  SLEW.ALL <MS>  PARAM SLEW MS (0-10000)",
    "  SLEW <P> <MS>  PER-PARAM SLEW MS",
    "  FLASH <MS>     FLASH HOLD MS (DEF 200)",
    "  RST            RESET TO DEFAULTS",
    "  LOAD.RST       RESET MODE (0=KEEP 1=RST)",
    "  LOAD.RST <0|1> SET SCENE LOAD MODE",
    "  Q/QUIT/EXIT        QUIT APPLICATION",
    "",
    "# REPL UTILITIES",
    "  CLEAR         CLEAR OUTPUT HISTORY",
    "  DEBUG <0-5>   SET VERBOSITY TIER",
    "  DEBUG 0       SILENT (USE OVERRIDES)",
    "  DEBUG 1       ERRORS",
    "  DEBUG 2       + STATE CHANGES",
    "  DEBUG 3       + VALUE READS",
    "  DEBUG 4       + SET CONFIRMS",
    "  DEBUG 5       + VERBOSE (ALL)",
    "  OUT.ERR <0|1> OVERRIDE: SHOW ERRORS",
    "  OUT.ESS <0|1> OVERRIDE: SHOW ESSENTIAL",
    "  OUT.QRY <0|1> OVERRIDE: SHOW QUERIES",
    "  OUT.CFM <0|1> OVERRIDE: SHOW CONFIRMS",
    "  HEADER        SHOW HDR VERBOSE",
    "  HEADER <0-4>  SET HEADER VERBOSITY",
    "  HEADER 0      NAV ONLY",
    "  HEADER 1      NAV + METERS",
    "  HEADER 2      NAV + METERS + TR",
    "  HEADER 3      FULL NAV + METERS + TR",
    "  HEADER 4      FULL + CPU (DEF)",
    "  PRINT \"TEXT\"  OUTPUT LITERAL STRING",
    "  PRINT <EXPR>  EVALUATE & PRINT",
    "  EXAMPLE: PRINT A, PRINT ADD 1 2",
    "",
    "# NOTES PAGE",
    "  NOTE \"TEXT\"   APPEND TO NOTES",
    "  NOTE.CLR      CLEAR ALL NOTES",
    "  SAVED WITH SCENES",
    "",
    "# VARIABLES",
    "  A B C D       GLOBAL ACCUMULATORS",
    "  X Y Z T       GLOBAL ACCUMULATORS",
    "  J K           PER-SCRIPT LOCAL VARS",
    "  I             LOOP COUNTER (IN L)",
    "  EXAMPLE: A 100 (SET), PF A (USE)",
    "",
    "# MATH (COMMAND & EXPRESSION)",
    "  ADD/+ <A> <B>   ADD",
    "  SUB/- <A> <B>   SUBTRACT",
    "  MUL/* <A> <B>   MULTIPLY",
    "  DIV// <A> <B>   DIVIDE",
    "  MOD/% <A> <B>   MODULO",
    "  MAP <V> <I1> <I2> <O1> <O2>",
    "    MAP VAL FROM IN RANGE TO OUT",
    "  EXAMPLE: PF MAP A 0 127 200 2000",
    "",
    "# RANDOM & GENERATORS",
    "  RND <MAX>        0 TO MAX",
    "  RRND <MIN> <MAX> MIN TO MAX",
    "  TOSS             COIN FLIP (0/1)",
    "  EITH <A> <B>     RANDOM CHOICE A OR B",
    "  TOG <A> <B>      ALTERNATE A/B",
    "",
    "# INLINE SEQUENCES",
    "  SEQ \"<PATTERN>\"  CYCLE VALUES",
    "  TOKENS:",
    "    X           TRIGGER (RET 1)",
    "    _ OR .      REST (RET 0)",
    "    ?           RANDOM (50% 1, 50% 0)",
    "    NUMBERS     100, -12, 0",
    "    NOTES       C3, E3, F#4, Bb2 (SEMI)",
    "  MODIFIERS:",
    "    *N          REPEAT N (C3*4 = C3 C3 C3 C3)",
    "    <A B>       TOGGLE (LIKE TOG)",
    "    {A B}       RANDOM (LIKE EITH)",
    "  STATE: PER-SCRIPT, PER-PATTERN",
    "  EXAMPLES:",
    "    SEQ \"X _ X _\"     TRIGGER PATTERN",
    "    SEQ \"C3*4 E3*2\"   REPEATED NOTES",
    "    SEQ \"<C3 E3> G3\"  TOGGLE C3/E3, G3",
    "    SEQ \"{C3 E3} G3\"  RANDOM C3/E3, G3",
    "    SEQ \"X ? X ?\"     RANDOM TRIGGERS",
    "    SEQ \"<C3 E3>*2\"   TWO TOGGLES",
    "    SEQ \"{C3 E3}*2\"   TWO RANDOMS",
    "",
    "# VOICE RANDOMIZATION",
    "  RND.VOICE  RAND ALL OSC/FM",
    "  RND.OSC    RAND OSC (PF/PW/MF/MW)",
    "  RND.FM     RAND FM (FM/FB/FBA/FBD)",
    "  RND.MOD    RAND MOD ROUTING",
    "  RND.ENV    RAND ENVELOPES",
    "",
    "# FX RANDOMIZATION",
    "  RND.FX     RANDOMIZE ALL EFFECTS",
    "  RND.FILT   RANDOMIZE FILTER PARAMS",
    "  RND.DLY    RANDOMIZE DELAY PARAMS",
    "  RND.VERB   RANDOMIZE REVERB PARAMS",
    "",
    "# PATTERN RANDOMIZATION",
    "  RND.P [MIN] [MAX]      RAND WORK PATT",
    "  RND.PN <N> [MIN] [MAX] RAND PATT N",
    "  RND.PALL [MIN] [MAX]   RAND ALL PATT",
    "",
    "# NOTE/PITCH",
    "  N <SEMI>      SEMITONES TO HZ",
    "  N 0 = C3 (131 HZ)",
    "  N 12 = C4, N 21 = A4 (440)",
    "  EXAMPLE: PF N 12, PF N ADD A 7",
    "",
    "# CONTROL FLOW (PRE OPERATORS)",
    "  IF <X>: <CMD>        IF X != 0",
    "  IF <COND>: <CMD>     WITH COMPARISON",
    "  ELIF <COND>: <CMD>   ELSE-IF",
    "  ELSE: <CMD>          ELSE BRANCH",
    "  PROB <0-100>: <CMD>  PROBABILITY %",
    "  EV <N>: <CMD>        EVERY NTH TICK",
    "  SKIP <N>: <CMD>      SKIP EVERY NTH",
    "  L <S> <E>: <CMDS>    LOOP S TO E",
    "  BRK                  STOP SCRIPT",
    "  CMD1; CMD2           SUB-COMMANDS",
    "",
    "# COMPARISONS (RETURN 1/0)",
    "  EZ <X>       X == 0 (EQUALS ZERO)",
    "  NZ <X>       X != 0 (NOT ZERO)",
    "  EQ <A> <B>   A == B",
    "  NE <A> <B>   A != B",
    "  GT <A> <B>   A > B",
    "  LT <A> <B>   A < B",
    "  GTE <A> <B>  A >= B",
    "  LTE <A> <B>  A <= B",
    "  ALSO: > < >= <= == != IN COND",
    "",
    "# SCENES",
    "  SAVE <NAME>   SAVE SCRIPTS+PATTERNS",
    "  LOAD <NAME>   LOAD SCENE",
    "  SCENES        LIST SAVED SCENES",
    "  DELETE <NAME> DELETE SCENE",
    "  AUTOLOAD <0|1> AUTO-LOAD LAST SCENE",
    "",
    "# PRESETS",
    "  PSET <SCRIPT> <NAME>      LOAD TO 1-8",
    "  PSET.SAVE <SCRIPT> <NAME> SAVE AS USER",
    "  PSET.DEL <NAME>           DEL USER",
    "  PSETS                     LIST ALL",
    "  [F] = FACTORY (READ-ONLY), [U] = USER",
    "  EX: PSET 1 808-KICK, PSET.SAVE 2 BASS",
    "",
    "# RECORDING",
    "  REC           START RECORDING (WAV)",
    "  REC.STOP      STOP RECORDING",
    "  REC.PATH <P>  SET PATH PREFIX",
    "",
    "# BEAT REPEAT",
    "  BR.LEN <0-7>  DIV (0=1/16...7=8X)",
    "  BR.REV <0|1>  REVERSE PLAYBACK",
    "  BR.WIN <1-50> WINDOW SIZE (MS)",
    "  BR.MIX <0-16383> MIX (ACTIVATES >0)",
    "",
    "# PITCH SHIFT",
    "  PS.MODE <0|1>   MODE (NORM/GRAN)",
    "  PS.SEMI <-24-24> SHIFT (SEMITONES)",
    "  PS.GRAIN <5-100> GRAIN SIZE (MS)",
    "  PS.MIX <0-16383> PITCH SHIFT MIX",
    "  PS.TARG <0|1>    TARG (IN/OUT)",
    "",
    "# OSCILLATORS",
    "  POSC.FREQ / PF <HZ>    PRI FREQ (20-20K)",
    "  POSC.WAVE / PW <0-2>   PRI (SIN/TRI/SAW)",
    "  MOSC.FREQ / MF <HZ>    MOD FREQ (20-20K)",
    "  MOSC.WAVE / MW <0-2>   MOD (SIN/TRI/SAW)",
    "",
    "# FM SYNTHESIS",
    "  MBUS.FM / FM <0-16383> FM INDEX",
    "  FMEV.AMT / FA <0-16383> FM ENV AMOUNT",
    "  FMEV.DEC / FD <MS>     FM ENV DECAY",
    "",
    "# FEEDBACK FM",
    "  MOSC.FB / FB <0-16383>  FB AMT",
    "  FBEV.AMT / FBA <0-16383> FB ENV AMT",
    "  FBEV.DEC / FBD <MS>     FB ENV DEC",
    "",
    "# DISCONTINUITY",
    "  DISC.AMT / DC <0-16383> DISC AMT",
    "  DENV.AMT / DA <0-16383> DC ENV AMOUNT",
    "  DENV.DEC / DD <MS>      DC ENV DECAY",
    "  DISC.MODE / DM <0-6>    MODE (FOLD/TANH)",
    "",
    "# LO-FI",
    "  LOFI.BIT / LB <1-16>    BIT (16=CLEAN)",
    "  LOFI.SMP / LS <100-48K> SAMP RATE",
    "  LOFI.MIX / LM <0-16383> LO-FI MIX",
    "",
    "# SVF FILTER",
    "  FILT.CUT / FC <HZ>      CUT (20-20K)",
    "  FILT.RES / FQ <0-16383> RES",
    "  FILT.TYP / FT <0-3>     TYP (LP/HP/BP/N)",
    "  FLEV.AMT / FE <0-16383> ENV AMT",
    "  FLEV.DEC / FED <MS>     ENV DEC",
    "  FILT.KEY / FK <0-16383> KEY TRACK",
    "  ROUT.MF / MF.F <0-1>    MOD -> FILT",
    "",
    "# RING MOD",
    "  RING.FRQ / RGF <20-2000> FREQ",
    "  RING.WAV / RGW <0-3>     WAV (SIN/TRI/SAW)",
    "  RING.MIX / RGM <0-16383> RING MOD MIX",
    "",
    "# COMB RESONATOR",
    "  RESO.FRQ / RF <HZ>      FREQ",
    "  RESO.DEC / RD <MS>      DECAY",
    "  RESO.MIX / RM <0-16383> MIX",
    "  RESO.KEY / RK <0-16383> KEY TRACK",
    "",
    "# COMPRESSOR",
    "  COMP.THR / CT <0-16383> THRESHOLD",
    "  COMP.RAT / CR <1-20>    RATIO",
    "  COMP.ATK / CA <1-500>   ATTACK (MS)",
    "  COMP.REL / CL <10-2000> RELEASE (MS)",
    "  COMP.MKP / CM <0-16383> MAKEUP GAIN",
    "",
    "# PAN",
    "  OUT.PAN / PAN <-16K-16K> STEREO POS",
    "",
    "# AMPLITUDE ENVELOPE",
    "  AENV.DEC / AD <MS>       DEC (1-10K)",
    "  AENV.ATK / AA <MS>       ATK (1-10K)",
    "  AENV.CRV / AC <V>        CRV (-8 TO 8)",
    "",
    "# PITCH ENVELOPE",
    "  PENV.AMT / PA <OCTAVES>  AMT (0-16)",
    "  PENV.DEC / PD <MS>       DEC (1-10K)",
    "  PENV.ATK / PAA <MS>      ATK (1-10K)",
    "  PENV.CRV / PC <V>        CRV (-8 TO 8)",
    "",
    "# FM ENVELOPE",
    "  FMEV.AMT / FA <0-16383>  AMT",
    "  FMEV.DEC / FD <MS>       DEC (1-10K)",
    "  FMEV.ATK / FAA <MS>      ATK (1-10K)",
    "  FMEV.CRV <V>             CRV (-8 TO 8)",
    "",
    "# DISCONTINUITY ENVELOPE",
    "  DENV.AMT / DA <0-16383>  AMT",
    "  DENV.DEC / DD <MS>       DEC (1-10K)",
    "  DENV.ATK / DAA <MS>      ATK (1-10K)",
    "  DENV.CRV <V>             CRV (-8 TO 8)",
    "",
    "# FEEDBACK ENVELOPE",
    "  FBEV.AMT / FBA <0-16383> AMT",
    "  FBEV.DEC / FBD <MS>      DEC (1-10K)",
    "  FBEV.ATK / FBAA <MS>     ATK (1-10K)",
    "  FBEV.CRV / FBC <V>       CRV (-8 TO 8)",
    "",
    "# FILTER ENVELOPE",
    "  FLEV.AMT / FE <0-16383>  AMT",
    "  FLEV.DEC / FED <MS>      DEC (1-10K)",
    "  FLEV.ATK / FLAA <MS>     ATK (1-10K)",
    "  FLEV.CRV / FLC <V>       CRV (-8 TO 8)",
    "",
    "# MOD BUS",
    "  MBUS.AMT / MB <0-16383> MOD AMT",
    "  MBUS.TRK / TK <0-16383> TRACK AMT",
    "  ROUT.MP / MP <0|1>      MOD -> PRI FREQ",
    "  ROUT.MD / MD <0|1>      MOD -> DISC",
    "  ROUT.MT / MT <0|1>      MOD -> TRACK",
    "  ROUT.MA / MA <0|1>      MOD -> AMP",
    "",
    "# MIX",
    "  MBUS.MIX / MX <0-16383> MIX AMT",
    "  MBUS.MMX / MM <0|1>     MOD -> MIX",
    "  MBUS.EMX / ME <0|1>     ENV -> MIX",
    "",
    "# STEREO DELAY",
    "  DLY.TIME / DT <MS>      TIME (1-2000)",
    "  DLY.FB / DF <0-16383>   FEEDBACK",
    "  DLY.LP / DLP <HZ>       LP FILT",
    "  DLY.WET / DW <0-16383>  WET MIX",
    "  DLY.SYN / DS <0-16383>  STEREO WID",
    "",
    "# DELAY ROUTING",
    "  DLY.MODE / D.MODE <0-2> BYP/INS/SND",
    "  DLY.TAIL / D.TAIL <0-2> CUT/RNG/FRZ",
    "",
    "# 3-BAND EQ",
    "  EQ.LOW / EL <-24-24>    LOW DB",
    "  EQ.MID / EM <-24-24>    MID DB",
    "  EQ.FRQ / EF <200-8000>  MID FREQ (HZ)",
    "  EQ.Q <0.1-10>           MID Q",
    "  EQ.HI / EH <-24-24>     HI DB",
    "",
    "# PLATE REVERB",
    "  REV.DEC / RV <0-16383>  REVERB DECAY",
    "  REV.PRE / RP <MS>       PRE-DLY",
    "  REV.DMP / RH <0-16383>  DAMP (HI)",
    "  REV.WET / RW <0-16383>  WET MIX",
    "",
    "# REVERB ROUTING",
    "  REV.MODE / R.MODE <0-2> BYP/INS/SND",
    "  REV.TAIL / R.TAIL <0-2> CUT/RNG/FRZ",
    "",
    "# METRO",
    "  M             SHOW INTERVAL",
    "  M <MS>        SET INTERVAL",
    "  M.BPM <BPM>   SET BPM",
    "  M.ACT <0|1>   START/STOP",
    "  M.SCRIPT <1-8>  SCRIPT FOR METRO",
    "",
    "# MIDI CLOCK SYNC",
    "  M.SYNC         SHOW SYNC MODE",
    "  M.SYNC <0|1>   SET SYNC MODE",
    "    0 = INTERNAL (DEFAULT)",
    "    1 = MIDI CLOCK (16TH NOTES)",
    "  MIDI.IN        LIST MIDI INPUTS",
    "  MIDI.IN <NAME> CONNECT TO DEVICE",
    "  NOTE: CONNECT FIRST, THEN M.SYNC 1",
    "  TRANSPORT: START/STOP FOLLOWS MIDI",
    "",
    "# MIDI CLOCK DIAGNOSTICS",
    "  MIDI.DIAG <0|1>  ON/OFF TIMING",
    "  MIDI.DIAG REPORT WRITE REPORT TO FILE",
    "  SC.DIAG <0|1>    ON/OFF SC TIMING",
    "  SC.DIAG REPORT   WRITE TO FILE",
    "  REPORTS: midi_timing_report.txt",
    "           sc_timing_report.txt",
    "",
    "# SCRIPTS",
    "  SCRIPT <1-8>  EXECUTE STORED SCRIPT",
    "",
    "# DELAYED EXECUTION",
    "  DEL <MS>: <CMD>     EXEC AFTER MS",
    "  DEL.CLR             CLR PENDING",
    "  DEL.X <N> <MS>: CMD REP N TIMES @ MS",
    "  DEL.R <N> <MS>: CMD NOW + REP N-1",
    "  MAX DELAY: 16000MS",
    "",
    "# COUNTERS",
    "  N1-N4         READ VAL + AUTO-INC",
    "  N1.MIN <N>    SET MINIMUM (DEFAULT 0)",
    "  N1.MAX <N>    SET MAX (WRAPS)",
    "  N1.RST        RESET TO MIN",
    "  EXAMPLE: N1.MIN 10; N1.MAX 14",
    "  CYCLES: 10, 11, 12, 13, 14, 10...",
    "",
    "# PATTERNS (WORKING - P.N)",
    "  P.N           GET WORKING PATTERN",
    "  P.N <0-5>     SET WORKING PATTERN",
    "  P.L / P.L <N> GET/SET LENGTH",
    "  P.I / P.I <N> GET/SET INDEX",
    "  P.HERE        VALUE AT INDEX",
    "  P.NEXT        ADVANCE, GET VALUE",
    "  P.PREV        REVERSE, GET VALUE",
    "  P <I> / P <I> <V>  GET/SET AT INDEX",
    "",
    "# PATTERNS (EXPLICIT - PN)",
    "  PN.L <P> / PN.L <P> <N>  LENGTH",
    "  PN.I <P> / PN.I <P> <N>  INDEX",
    "  PN.HERE <P>              VALUE",
    "  PN.NEXT <P>              ADVANCE",
    "  PN.PREV <P>              REVERSE",
    "  PN <P> <I> / PN <P> <I> <V>",
    "",
    "# PATTERN MANIPULATION",
    "  P.PUSH <V>     PUSH VAL, SHIFT LEFT",
    "  P.POP          POP & RETURN LAST VAL",
    "  P.INS <I> <V>  INSERT VAL AT INDEX",
    "  P.RM <I>       REMOVE VAL AT INDEX",
    "  P.REV          REVERSE PATTERN",
    "  P.ROT <N>      ROTATE BY N STEPS",
    "  P.SHUF         SHUFFLE RANDOMLY",
    "  P.SORT         SORT ASCENDING",
    "  P.RND [MIN] [MAX]  RANDOMIZE VALUES",
    "  P.CLR          CLEAR (SET ALL TO 0)",
    "",
    "# PATTERN MATH",
    "  P.ADD <V>      ADD TO ALL VALUES",
    "  P.SUB <V>      SUBTRACT FROM ALL",
    "  P.MUL <V>      MULTIPLY ALL VALUES",
    "  P.DIV <V>      DIVIDE ALL VALUES",
    "  P.MOD <V>      MODULO ALL VALUES",
    "  P.SCALE <MIN> <MAX> SCALE TO NEW RANGE",
    "",
    "# PATTERN QUERIES",
    "  P.MIN          GET MINIMUM VALUE",
    "  P.MAX          GET MAXIMUM VALUE",
    "  P.SUM          GET SUM OF ALL",
    "  P.AVG          GET AVERAGE VALUE",
    "  P.FND <V>      FIND INDEX OF VAL (-1)",
    "",
    "  NOTE: PN.* VARIANTS TAKE PATTERN",
    "  NUMBER AS FIRST ARG (EX: PN.ADD 0 5)",
    "",
    "# SYSTEM COMMANDS",
    "  RST                RESET TO DEFAULTS",
    "    PF: 131 HZ (C3), MF: 262 HZ (C4)",
    "    PA: 0, FC: 10000 HZ",
    "    D.MODE: 2 (SEND), R.MODE: 2 (SEND)",
    "    CR: 1 (COMPRESSOR OFF)",
    "  LOAD.RST           SHOW RESET MODE",
    "  LOAD.RST <0|1> SET LOAD MODE",
    "    0 = PERSIST SYNTH PARAMS (DEFAULT)",
    "    1 = RESET ALL PARAMS BEFORE LOAD",
    "",
    "# AUDIO OUTPUT",
    "  AUDIO.OUT         LIST OUTPUT DEVICES",
    "  AUDIO.OUT <N>     SET OUTPUT BY NUMBER",
    "",
    "  DEVICE CHANGE RESTARTS AUDIO ENGINE",
    "  SAVED TO CONFIG FOR NEXT LAUNCH",
    "",
    "# EXPRESSIONS",
    "  ALL NUMERIC ARGS ACCEPT EXPRESSIONS:",
    "  PF N ADD A 7",
    "  DC MUL PN.NEXT 0 100",
    "  A RRND 0 127",
    "",
];
