use super::help_categories::HelpCategory;

pub const METRO_SCRIPTS: HelpCategory = HelpCategory {
    name: "METRO & SCRIPTS",
    lines: &[
        "",
        "# PAGE NAVIGATION",
        "  PAGE <PAGE>   SWITCH TO PAGE",
        "  PAGE LIVE/L   LIVE PAGE",
        "  PAGE 1-8      SCRIPT 1-8",
        "  PAGE M        METRO PAGE",
        "  PAGE I        INIT PAGE",
        "  PAGE P        PATTERN PAGE",
        "  PAGE V        VARIABLES PAGE",
        "  PAGE N        NOTES PAGE",
        "  PAGE S        SCOPE PAGE",
        "  PAGE HELP/H   HELP PAGE",
        "  PAGE GRID/G   GRID VIEW ON LIVE",
        "  PG <PAGE>     ALIAS FOR PAGE",
        "",
        "# METRO",
        "  M             SHOW INTERVAL",
        "  M <MS>        SET INTERVAL",
        "  M.BPM <BPM>   SET BPM",
        "  M.ACT <0|1>   START/STOP",
        "  M.SCRIPT <1-8>  METRO SCRIPT",
        "",
        "# MIDI CLOCK SYNC",
        "  M.SYNC         SHOW SYNC MODE",
        "  M.SYNC <0|1>   SET SYNC MODE",
        "    0 = INTERNAL (DEFAULT)",
        "    1 = MIDI CLOCK (16TH NOTES)",
        "  MIDI.IN        LIST INPUTS",
        "  MIDI.IN <NAME> CONNECT DEV",
        "  NOTE: CONNECT FIRST, M.SYNC 1",
        "  TRANSPORT: START/STOP W/ MIDI",
        "",
        "# MIDI CLOCK DIAGNOSTICS",
        "  MIDI.DIAG <0|1>  ON/OFF TIMING",
        "  MIDI.DIAG REPORT WRITE TO FILE",
        "  SC.DIAG <0|1>    ON/OFF SC TIMING",
        "  SC.DIAG REPORT   WRITE TO FILE",
        "  REPORTS: midi_timing_report.txt",
        "           sc_timing_report.txt",
        "",
        "# SCRIPTS",
        "  SCRIPT <1-8>  EXEC SCRIPT",
        "  MUTE          QUERY ALL MUTE STATES",
        "  MUTE <1-8>    TOGGLE SCRIPT MUTE",
        "  MUTE <N> <0|1>  SET MUTE (0=ACTIVE 1=MUTED)",
        "  MUTE.1-8      TOGGLE SCRIPT N",
        "  MUTE.M        TOGGLE METRO MUTE",
        "  MUTE.I        TOGGLE INIT MUTE",
        "",
        "# DELAYED EXECUTION",
        "  DEL <MS>: <CMD>     EXEC AFTER MS",
        "  DEL.CLR             CLR PENDING",
        "  DEL.X <N> <MS>: CMD REP N TIMES @ MS",
        "  DEL.R <N> <MS>: CMD NOW + REP N-1",
        "  MAX DELAY: 16000MS",
        "",
    ],
};

pub const UI_DISPLAY: HelpCategory = HelpCategory {
    name: "UI & DISPLAY",
    lines: &[
        "",
        "# UI TOGGLES",
        "  METER.HDR <0|1>   HDR METERS",
        "  METER.GRID <0|1>  GRID METERS",
        "  METER.ASCII <0|1> ASCII METER MODE",
        "  SPECTRUM <0|1>    SPECTRUM",
        "  ACTIVITY <0|1>    ACTIVITY IND",
        "  GRID <0|1>        PARAM GRID VIS",
        "  GRID.DEF <0|1>    DEF VIEW (REPL/GRID)",
        "  GRID.MODE <0-5>   LBL/ICO/EQ/MIX/FX/SMP",
        "  HL.SEQ <0|1>      SEQ/TOG HIGHL",
        "  HL.COND <0|1>     COND HIGHL",
        "  CPU <0|1>         CPU METER",
        "  BPM <0|1>         BPM DISPLAY",
        "  TITLE <0|1>       HDR TITLE MODE",
        "  SCRMBL            QUERY SCRAMBLE ON/OFF",
        "  SCRMBL <0|1>      HEADER SCRAMBLE FX",
        "  SCRMBL.GRID / SG <0|1> GRID SCRAMBLE FX",
        "  SCRMBL.MODE       QUERY SCRAMBLE STYLE",
        "  SCRMBL.MODE <0-3> 0=REG 1=SMASH 2=ROLL 3=OVER",
        "  SCRMBL.SPD        QUERY SCRAMBLE SPEED",
        "  SCRMBL.SPD <1-10> 1=SLOW 10=FAST",
        "  SCRMBL.CRV        QUERY SCRAMBLE CURVE",
        "  SCRMBL.CRV <0|1>  0=LINEAR 1=SETTLE",
        "  HEADER <0-4>      HDR VERBOSE",
        "  DEBUG <0-5>       VERBOSITY TIER",
        "",
        "# OUTPUT VERBOSITY",
        "  DEBUG <0-5>       SET VERBOSITY TIER",
        "  DEBUG 0           SILENT (OVERRIDES ONLY)",
        "  DEBUG 1           ERRORS",
        "  DEBUG 2           + STATE CHANGES",
        "  DEBUG 3           + VALUE READS",
        "  DEBUG 4           + SET CONFIRMS",
        "  DEBUG 5           + VERBOSE (ALL)",
        "  OUT.ERR <0|1>     OVERRIDE: SHOW ERRORS",
        "  OUT.ESS <0|1>     OVERRIDE: ESSENTIAL",
        "  OUT.QRY <0|1>     OVERRIDE: QUERIES",
        "  OUT.CFM <0|1>     OVERRIDE: CONFIRMS",
        "",
        "# TITLE MODE",
        "  TITLE 0           SHOW 'MONOKIT'",
        "  TITLE 1           SHOW SCENE NAME",
        "  TITLE.TIMER       QUERY STATE",
        "  TITLE.TIMER 0     DISABLE TIMER",
        "  TITLE.TIMER 1 <S> CYCLE EVERY <S> SECS (1-1800)",
        "",
        "# HEADER LEVELS (BPM AT 1-4)",
        "  HEADER 0          NAV ONLY",
        "  HEADER 1          NAV + METERS + BPM",
        "  HEADER 2          NAV + MET + TR + BPM",
        "  HEADER 3          FULL NAV + MET + TR",
        "  HEADER 4          FULL + CPU (DEF)",
        "",
    ],
};

pub const OSCILLOSCOPE: HelpCategory = HelpCategory {
    name: "OSCILLOSCOPE",
    lines: &[
        "",
        "# OSCILLOSCOPE SETTINGS",
        "  SCOPE.TIME <5-500> MS (30)",
        "  SCOPE.CLR <NAME>   COLOR",
        "    FOREGROUND SECONDARY HIGHLIGHT_BG",
        "    HIGHLIGHT_FG BORDER ERROR ACCENT",
        "    SUCCESS LABEL (OR 0-8)",
        "  SCOPE.MODE <0-4>    MODE",
        "    0 = BRAILLE",
        "    1 = BLOCK",
        "    2 = LINE",
        "    3 = DOT",
        "    4 = QUAD",
        "  SCOPE.UNI <0|1>     UNIPOLAR",
        "  SCOPE.GAIN / SCG <0-16383> GAIN (8K=1X)",
        "  SCOPE.RST / SCR     RESET TO DEFAULTS",
        "",
        "  NOTE: SCOPE.MODE 1 (blocks) may render",
        "  better than braille in some terminals.",
        "",
        "# NAVIGATION",
        "  ALT+S OR [ ]       SCOPE PAGE",
        "",
    ],
};

pub const SYSTEM: HelpCategory = HelpCategory {
    name: "SYSTEM",
    lines: &[
        "",
        "# SYSTEM COMMANDS",
        "  VERSION / VER  SHOW VERSION",
        "  RST            RESET TO DEFAULTS",
        "    PF: 131 HZ (C3), MF: 262 HZ (C4)",
        "    PA: 0, FC: 10000 HZ",
        "    D.MODE: 2 (SND), R.MODE: 2 (SND)",
        "    CR: 1 (COMP OFF)",
        "  LOAD.RST       RESET MODE",
        "  LOAD.RST <0|1> SET LOAD MODE",
        "    0 = PERSIST SYNTH (DEF)",
        "    1 = RESET ALL BEFORE LOAD",
        "  CFM.QUIT <0|1> CONFIRM ON QUIT",
        "  CFM.SAVE <0|1> CONFIRM ON OVERWRITE",
        "",
        "# AUDIO OUTPUT",
        "  AUDIO.OUT         LIST OUTPUT DEVICES",
        "  AUDIO.OUT <N>     SET OUTPUT BY NUMBER",
        "  LIMIT <0|1>       OUTPUT LIMITER",
        "",
        "  DEVICE CHANGE RESTARTS AUDIO ENGINE",
        "  SAVED TO CONFIG FOR NEXT LAUNCH",
        "",
        "# TERMINAL COMPAT",
        "  COMPAT             Show capabilities",
        "  COMPAT.MODE        Query mode",
        "  COMPAT.MODE <0|1>  0=Full 1=Basic",
        "  Terminal.app has limited color support.",
        "  For best results use iTerm2 or similar.",
        "  256-color mode auto-enabled when needed.",
        "  Block chars may show gaps - try Monaco.",
        "",
        "# EXPRESSIONS",
        "  ALL NUMERIC ARGS ACCEPT EXPR:",
        "  PF N ADD A 7",
        "  DC MUL PN.NEXT 0 100",
        "  A RRND 0 127",
        "",
    ],
};
