pub use super::help_categories::HelpCategory;

use super::help_categories::*;
use super::help_synth::*;
use super::help_effects::*;
use super::help_system::*;

pub const HELP_CATEGORIES: &[HelpCategory] = &[
    NAV_EDITING,
    VARIABLES_MATH,
    CONTROL_FLOW,
    PATTERNS,
    SCALE_QUANTIZATION,
    OSCILLATORS_FM,
    ENVELOPES,
    PLAITS_SYNTH,
    SAMPLER,
    FILTER_EFFECTS,
    DELAY_REVERB,
    METRO_SCRIPTS,
    UI_DISPLAY,
    OSCILLOSCOPE,
    SYSTEM,
];

pub const HELP_LINES: &[&str] = &[
    "",
    "# COMMAND NAMING CONVENTION",
    "  PREFIX.SUFFIX - CANONICAL FORM",
    "  EX: POSC.FREQ, FILT.CUT, AENV.ATK",
    "  SHORT FORMS AS ALIASES (PF, FC, AD)",
    "  USE WHICHEVER FORM YOU PREFER",
    "",
    "# NAVIGATION",
    "  [ ]           CYCLE PAGES",
    "  ESC           TOGGLE HELP",
    "",
    "# FUNCTION KEYS (WORK IN ALL TERMINALS)",
    "  F1-F8         SCRIPT 1-8",
    "  F9            LIVE PAGE",
    "  F10           METRO PAGE",
    "  F11           INIT PAGE",
    "  F12           PATTERN PAGE",
    "",
    "# ALT KEYS (REQUIRE ITERM2 CONFIG)",
    "  ALT+L         LIVE PAGE",
    "  ALT+1 TO 8    SCRIPT 1-8",
    "  ALT+M         METRO PAGE",
    "  ALT+I         INIT PAGE",
    "  ALT+P         PATTERN PAGE",
    "  ALT+S         SCOPE PAGE",
    "  ALT+V         VARIABLES PAGE",
    "  ALT+H         TOGGLE HELP",
    "",
    "# SCRIPT MUTES",
    "  CTRL+SHIFT+1-8  TOGGLE SCRIPT MUTE",
    "  CTRL+SHIFT+M    TOGGLE METRO MUTE",
    "  CTRL+SHIFT+I    TOGGLE INIT MUTE",
    "",
    "# OTHER",
    "  CTRL+Q        QUIT APP",
    "  CTRL+UP/DN    SCROLL REPL (LIVE PAGE)",
    "  TAB           LIVE PG / GRID VIEW",
    "",
    "# SEARCH",
    "  CTRL+F        ENTER SEARCH MODE",
    "  ENTER         NEXT MATCH",
    "  SHIFT+ENTER   PREVIOUS MATCH",
    "  ESC           EXIT SEARCH",
    "",
    "  HELP PAGE: SEARCHES HELP ONLY",
    "  OTHER PAGES: SEARCHES SCRIPTS",
    "",
    "# EDITING (SCRIPT PAGES)",
    "  UP/DOWN       SELECT LINE",
    "  ENTER         SAVE LINE",
    "  CTRL+D        DUPLICATE LINE (PUSH DOWN)",
    "  CTRL+K        DELETE LINE",
    "  CTRL+C        COPY LINE",
    "  CTRL+X        CUT LINE",
    "  CTRL+V        PASTE LINE",
    "  CTRL+Z        UNDO (PAGE-LOCAL)",
    "  CTRL+SHIFT+Z  REDO",
    "  CTRL+L/R      WORD MOVEMENT",
    "",
    "# TRIGGER & VOLUME",
    "  TR                 TRIGGER VOICE",
    "  OUT.VOL / VOL 0-1  MASTER VOLUME",
    "  VCA <0|1>          0=DRONE 1=GATED",
    "  SLEW.ALL <MS>  PARAM SLEW MS (0-10000)",
    "  SLEW <P> <MS>  PER-PARAM SLEW MS",
    "  FLASH <MS>     FLASH HOLD MS (DEF 200)",
    "  RST            RESET TO DEFAULTS",
    "  LOAD.RST       RESET MODE (0=KEEP 1=RST)",
    "  LOAD.RST <0|1> SET SCENE LOAD MODE",
    "  Q/QUIT/EXIT        QUIT APPLICATION",
    "",
    "# REPL UTILITIES",
    "  CLEAR         CLEAR OUTPUT HISTORY",
    "  DEBUG <0-5>   SET VERBOSITY TIER",
    "  DEBUG 0       SILENT (USE OVERRIDES)",
    "  DEBUG 1       ERRORS",
    "  DEBUG 2       + STATE CHANGES",
    "  DEBUG 3       + VALUE READS",
    "  DEBUG 4       + SET CONFIRMS",
    "  DEBUG 5       + VERBOSE (ALL)",
    "  OUT.ERR <0|1> OVERRIDE: SHOW ERRORS",
    "  OUT.ESS <0|1> OVERRIDE: SHOW ESSENTIAL",
    "  OUT.QRY <0|1> OVERRIDE: SHOW QUERIES",
    "  OUT.CFM <0|1> OVERRIDE: SHOW CONFIRMS",
    "  HEADER        SHOW HDR VERBOSE",
    "  HEADER <0-4>  SET HEADER VERBOSITY",
    "  HEADER 0      NAV ONLY",
    "  HEADER 1      NAV + METERS",
    "  HEADER 2      NAV + METERS + TR",
    "  HEADER 3      FULL NAV + METERS + TR",
    "  HEADER 4      FULL + CPU (DEF)",
    "  PRINT \"TEXT\"  OUTPUT LITERAL STRING",
    "  PRINT <EXPR>  EVALUATE & PRINT",
    "  EXAMPLE: PRINT A, PRINT ADD 1 2",
    "",
    "# NOTES PAGE",
    "  NOTE \"TEXT\"   APPEND TO NOTES",
    "  NOTE.CLR      CLEAR ALL NOTES",
    "  SAVED WITH SCENES",
    "",
    "# VARIABLES",
    "  A B C D       GLOBAL ACCUMULATORS",
    "  X Y Z T       GLOBAL ACCUMULATORS",
    "  J K           PER-SCRIPT LOCAL VARS",
    "  I             LOOP COUNTER (IN L)",
    "  EXAMPLE: A 100 (SET), PF A (USE)",
    "",
    "# MATH (COMMAND & EXPRESSION)",
    "  ADD/+ <A> <B>   ADD",
    "  SUB/- <A> <B>   SUBTRACT",
    "  MUL/* <A> <B>   MULTIPLY",
    "  DIV// <A> <B>   DIVIDE",
    "  MOD/% <A> <B>   MODULO",
    "  MAP <V> <I1> <I2> <O1> <O2>",
    "    MAP VAL FROM IN RANGE TO OUT",
    "  EXAMPLE: PF MAP A 0 127 200 2000",
    "",
    "# RANDOM & GENERATORS",
    "  RND <MAX>        0 TO MAX",
    "  RRND <MIN> <MAX> MIN TO MAX",
    "  TOSS             COIN FLIP (0/1)",
    "  EITH <A> <B>     RANDOM CHOICE A OR B",
    "  TOG <A> <B>      ALTERNATE A/B",
    "",
    "# RHYTHM GENERATORS",
    "  ER f l s        EUCLIDEAN RHYTHM",
    "    f=FILL l=LEN s=STEP -> 0/1",
    "    EX: IF ER 5 8 I: TR",
    "  NR p m f s      NUMERIC REPEATER",
    "    p=PRIME(0-31) m=MASK(0-3)",
    "    f=FACTOR(0-16) s=STEP -> 0/1",
    "",
    "# COUNTERS",
    "  N1-N4         READ + AUTO-INC",
    "  N1.MIN <V>    SET MIN (DEF 0)",
    "  N1.MAX <V>    SET MAX (WRAPS AT MAX)",
    "  N1.RST        RESET TO MIN",
    "  SAME FOR N2, N3, N4",
    "  EXAMPLE: N1.MIN 10; N1.MAX 14",
    "  CYCLES: 10, 11, 12, 13, 14, 10...",
    "",
    "# INLINE SEQUENCES",
    "  SEQ \"<PATTERN>\"  CYCLE VALUES",
    "  TOKENS:",
    "    X           TRIGGER (RET 1)",
    "    _ OR .      REST (RET 0)",
    "    ?           RANDOM (50% 1, 50% 0)",
    "    NUMBERS     100, -12, 0",
    "    NOTES       C3, E3, F#4, Bb2 (SEMI)",
    "  MODIFIERS:",
    "    *N          REPEAT N (C3*4 = C3 C3 C3 C3)",
    "    <A B>       TOGGLE (LIKE TOG)",
    "    {A B}       RANDOM (LIKE EITH)",
    "  STATE: PER-SCRIPT, PER-PATTERN",
    "  EXAMPLES:",
    "    SEQ \"X _ X _\"     TRIGGER PATTERN",
    "    SEQ \"C3*4 E3*2\"   REPEATED NOTES",
    "    SEQ \"<C3 E3> G3\"  TOGGLE C3/E3, G3",
    "    SEQ \"{C3 E3} G3\"  RANDOM C3/E3, G3",
    "    SEQ \"X ? X ?\"     RANDOM TRIGGERS",
    "    SEQ \"<C3 E3>*2\"   TWO TOGGLES",
    "    SEQ \"{C3 E3}*2\"   TWO RANDOMS",
    "",
    "# VOICE RANDOMIZATION",
    "  RND.VOICE  RAND ALL OSC/FM",
    "  RND.OSC    RAND OSC (PF/PW/MF/MW)",
    "  RND.FM     RAND FM (FM/FB/FBA/FBD)",
    "  RND.MOD    RAND MOD ROUTING",
    "  RND.ENV    RAND ENVELOPES",
    "  RND.PL     RAND PLAITS PARAMS",
    "",
    "# FX RANDOMIZATION",
    "  RND.FX     RANDOMIZE ALL EFFECTS",
    "  RND.FILT   RANDOMIZE FILTER PARAMS",
    "  RND.DLY    RANDOMIZE DELAY PARAMS",
    "  RND.VERB   RANDOMIZE REVERB PARAMS",
    "",
    "# PATTERN RANDOMIZATION",
    "  RND.P [MIN] [MAX]      RAND WORK PATT",
    "  RND.PN <N> [MIN] [MAX] RAND PATT N",
    "  RND.PALL [MIN] [MAX]   RAND ALL PATT",
    "",
    "# NOTE/PITCH",
    "  N <SEMI>      SEMITONES TO HZ",
    "  N 0 = C3 (131 HZ)",
    "  N 12 = C4, N 21 = A4 (440)",
    "  EXAMPLE: PF N 12, PF N ADD A 7",
    "",
    "# CONTROL FLOW (PRE OPERATORS)",
    "  IF <X>: <CMD>        IF X != 0",
    "  IF <COND>: <CMD>     WITH COMPARISON",
    "  ELIF <COND>: <CMD>   ELSE-IF",
    "  ELSE: <CMD>          ELSE BRANCH",
    "  PROB <0-100>: <CMD>  PROBABILITY %",
    "  EV <N>: <CMD>        EVERY NTH TICK",
    "  SKIP <N>: <CMD>      SKIP EVERY NTH",
    "  L <S> <E>: <CMDS>    LOOP S TO E",
    "  BRK                  STOP SCRIPT",
    "  CMD1; CMD2           SUB-COMMANDS",
    "",
    "# COMPARISONS (RETURN 1/0)",
    "  EZ <X>       X == 0 (EQUALS ZERO)",
    "  NZ <X>       X != 0 (NOT ZERO)",
    "  EQ <A> <B>   A == B",
    "  NE <A> <B>   A != B",
    "  GT <A> <B>   A > B",
    "  LT <A> <B>   A < B",
    "  GTE <A> <B>  A >= B",
    "  LTE <A> <B>  A <= B",
    "  ALSO: > < >= <= == != IN COND",
    "",
    "# SCENES",
    "  SAVE <NAME>   SAVE SCRIPTS+PATTERNS",
    "  LOAD <NAME>   LOAD SCENE",
    "  SCENES        LIST SAVED SCENES",
    "  DELETE <NAME> DELETE SCENE",
    "  AUTOLOAD <0|1> AUTO-LOAD LAST SCENE",
    "",
    "# PRESETS",
    "  PSET <SCRIPT> <NAME>      LOAD TO 1-8",
    "  PSET.SAVE <SCRIPT> <NAME> SAVE AS USER",
    "  PSET.DEL <NAME>           DEL USER",
    "  PSETS                     LIST ALL",
    "  [F] = FACTORY (READ-ONLY), [U] = USER",
    "  EX: PSET 1 808-KICK, PSET.SAVE 2 BASS",
    "",
    "# RECORDING",
    "  REC           START RECORDING (WAV)",
    "  REC.STOP      STOP RECORDING",
    "  REC.PATH <P>  SET PATH PREFIX",
    "",
    "# PAGE NAVIGATION",
    "  PAGE <PAGE>   SWITCH TO PAGE",
    "  PAGE LIVE/L   LIVE PAGE",
    "  PAGE 1-8      SCRIPT 1-8",
    "  PAGE M        METRO PAGE",
    "  PAGE I        INIT PAGE",
    "  PAGE P        PATTERN PAGE",
    "  PAGE V        VARIABLES PAGE",
    "  PAGE N        NOTES PAGE",
    "  PAGE S        SCOPE PAGE",
    "  PAGE HELP/H   HELP PAGE",
    "  PAGE GRID/G   GRID VIEW ON LIVE",
    "  PG <PAGE>     ALIAS FOR PAGE",
    "",
    "# BEAT REPEAT",
    "  BR.LEN / BRL <0-7>  DIV (0=1/16...7=8X)",
    "  BR.REV / BRR <0|1>  REVERSE PLAYBACK",
    "  BR.WIN / BRW <1-50> WINDOW SIZE (MS)",
    "  BR.MIX / BRX <0-16383> MIX (ACTIVATES >0)",
    "",
    "# PITCH SHIFT",
    "  PS.MODE / PSM <0|1>   MODE (NORM/GRAN)",
    "  PS.SEMI / PSS <-24-24> SHIFT (SEMITONES)",
    "  PS.GRAIN / PSG <5-100> GRAIN SIZE (MS)",
    "  PS.MIX / PSX <0-16383> PITCH SHIFT MIX",
    "  PS.TARG / PST <0|1>    TARG (IN/OUT)",
    "",
    "# MICLOUDS GRANULAR",
    "  CL.TRIG / CLTR        TRIGGER GRAINS",
    "  CL.PITCH / CLP <0-16K> PITCH (8K=CTR)",
    "  CL.POS / CLO <0-16K>   BUF POSITION",
    "  CL.SIZE / CLS <0-16K>  GRAIN SIZE",
    "  CL.DENS / CLD <0-16K>  DENSITY",
    "  CL.TEX / CLT <0-16K>   TEXTURE",
    "  CL.WET / CLW <0-16K>   WET MIX",
    "  CL.GAIN / CLG <0-16K>  GAIN (8K=1X)",
    "  CL.SPREAD / CLSP <0-16K> STEREO",
    "  CL.RVB / CLR <0-16K>   INTL REVERB",
    "  CL.FB / CLF <0-16K>    FEEDBACK",
    "  CL.FREEZE / CLFZ <0|1> FREEZE BUF",
    "  CL.MODE / CLM <0-3>    MODE",
    "  CL.LOFI / CLLO <0-16K> LO-FI",
    "  MODES: 0=GRAN 1=PITCH 2=LOOP 3=SPEC",
    "",
    "# OSCILLATORS",
    "  POSC.FREQ / PF <HZ>    PRI FREQ (20-20K)",
    "  POSC.WAVE / PW <0-2>   PRI (SIN/TRI/SAW)",
    "  MOSC.FREQ / MF <HZ>    MOD FREQ (20-20K)",
    "  MOSC.WAVE / MW <0-2>   MOD (SIN/TRI/SAW)",
    "",
    "# FM SYNTHESIS",
    "  MBUS.FM / FM <0-16383> FM INDEX",
    "  FMEV.AMT / FA <0-16383> FM ENV AMOUNT",
    "  FMEV.DEC / FD <MS>     FM ENV DECAY",
    "",
    "# FEEDBACK FM",
    "  MOSC.FB / FB <0-16383>  FB AMT",
    "  FBEV.AMT / FBA <0-16383> FB ENV AMT",
    "  FBEV.DEC / FBD <MS>     FB ENV DEC",
    "",
    "# DISCONTINUITY",
    "  DISC.AMT / DC <0-16383> DISC AMT",
    "  DENV.AMT / DA <0-16383> DC ENV AMOUNT",
    "  DENV.DEC / DD <MS>      DC ENV DECAY",
    "  DISC.MODE / DM <0-6>    MODE (FOLD/TANH)",
    "",
    "# LO-FI",
    "  LOFI.BIT / LB <1-16>    BIT (16=CLEAN)",
    "  LOFI.SMP / LS <100-48K> SAMP RATE",
    "  LOFI.MIX / LM <0-16383> LO-FI MIX",
    "",
    "# FILTER",
    "  FILT.CUT / FC <HZ>      CUT (20-20K)",
    "  FILT.RES / FQ <0-16383> RES",
    "  FILT.TYP / FT <0-13>    TYPE",
    "    0=SVF LP  1=SVF HP  2=SVF BP  3=NOTCH",
    "    4=MOOG  5=RES LP  6=RES HP",
    "    7=DFM1 LP  8=DFM1 HP",
    "    9=BMOOG LP  10=BMOOG HP  11=BMOOG BP",
    "    12=SC LP  13=SC HP",
    "  FLEV.AMT / FE <0-16383> ENV AMT",
    "  FLEV.DEC / FED <MS>     ENV DEC",
    "  FILT.KEY / FK <0-16383> KEY TRACK",
    "  MODF.CUT / MFF <0-16383> MOD->CUT AMT",
    "  MODF.RES / MFQ <0-16383> MOD->RES AMT",
    "",
    "# RING MOD",
    "  RING.FRQ / RGF <20-2000> FREQ",
    "  RING.WAV / RGW <0-3>     WAV (SIN/TRI/SAW)",
    "  RING.MIX / RGM <0-16383> RING MOD MIX",
    "",
    "# COMB RESONATOR",
    "  RESO.FRQ / RF <HZ>      FREQ",
    "  RESO.DEC / RD <MS>      DECAY",
    "  RESO.MIX / RM <0-16383> MIX",
    "  RESO.KEY / RK <0-16383> KEY TRACK",
    "",
    "# COMPRESSOR",
    "  COMP.THR / CT <0-16383> THRESHOLD",
    "  COMP.RAT / CR <1-20>    RATIO",
    "  COMP.ATK / CA <1-500>   ATTACK (MS)",
    "  COMP.REL / CL <10-2000> RELEASE (MS)",
    "  COMP.MKP / CM <0-16383> MAKEUP GAIN",
    "  COMP.MIX / CRMIX <0-16383> DRY/WET",
    "    0=DRY 16383=WET (PARALLEL)",
    "",
    "# PAN",
    "  OUT.PAN / PAN <-16K-16K> STEREO POS",
    "",
    "# AMPLITUDE ENVELOPE",
    "  AENV.DEC / AD <MS>       DEC (1-10K)",
    "  AENV.ATK / AA <MS>       ATK (1-10K)",
    "  AENV.CRV / AC <V>        CRV (-8 TO 8)",
    "",
    "# PITCH ENVELOPE",
    "  PENV.AMT / PA <OCTAVES>  AMT (0-16)",
    "  PENV.DEC / PD <MS>       DEC (1-10K)",
    "  PENV.ATK / PAA <MS>      ATK (1-10K)",
    "  PENV.CRV / PC <V>        CRV (-8 TO 8)",
    "",
    "# FM ENVELOPE",
    "  FMEV.AMT / FA <0-16383>  AMT",
    "  FMEV.DEC / FD <MS>       DEC (1-10K)",
    "  FMEV.ATK / FAA <MS>      ATK (1-10K)",
    "  FMEV.CRV <V>             CRV (-8 TO 8)",
    "",
    "# DISCONTINUITY ENVELOPE",
    "  DENV.AMT / DA <0-16383>  AMT",
    "  DENV.DEC / DD <MS>       DEC (1-10K)",
    "  DENV.ATK / DAA <MS>      ATK (1-10K)",
    "  DENV.CRV <V>             CRV (-8 TO 8)",
    "",
    "# FEEDBACK ENVELOPE",
    "  FBEV.AMT / FBA <0-16383> AMT",
    "  FBEV.DEC / FBD <MS>      DEC (1-10K)",
    "  FBEV.ATK / FBAA <MS>     ATK (1-10K)",
    "  FBEV.CRV / FBC <V>       CRV (-8 TO 8)",
    "",
    "# FILTER ENVELOPE",
    "  FLEV.AMT / FE <0-16383>  AMT",
    "  FLEV.DEC / FED <MS>      DEC (1-10K)",
    "  FLEV.ATK / FLAA <MS>     ATK (1-10K)",
    "  FLEV.CRV / FLC <V>       CRV (-8 TO 8)",
    "",
    "# MOD BUS",
    "  MBUS.AMT / MB <0-16383> MOD AMT",
    "  MBEV.AMT / MBA <0-16383> MOD ENV AMT",
    "  MBEV.DEC / MBD <1-10000> MOD ENV DEC (MS)",
    "  MBUS.TRK / TK <0-16383> TRACK AMT",
    "",
    "# MOD ROUTING (TOGGLES)",
    "  ROUT.MP / MP <0|1>      MOD -> PRI FREQ",
    "  ROUT.MD / MD <0|1>      MOD -> DISC",
    "  ROUT.MT / MT <0|1>      MOD -> TRACK",
    "  ROUT.MA / MA <0|1>      MOD -> AMP",
    "  ROUT.MC / MC <0|1>      MOD -> FILTER CUT",
    "  ROUT.MQ / MQ <0|1>      MOD -> FILTER RES",
    "",
    "# MOD ROUTING (AMOUNTS)",
    "  MODF.CUT / MFF <0-16383> MOD->CUT AMOUNT",
    "  MODF.RES / MFQ <0-16383> MOD->RES AMOUNT",
    "",
    "# MIX",
    "  MBUS.MIX / MX <0-16383> MIX AMT",
    "  MBUS.MMX / MM <0|1>     MOD -> MIX",
    "  MBUS.EMX / ME <0|1>     ENV -> MIX",
    "",
    "# NOISE",
    "  NOISE.WAV / NW <0-2>  TYPE (WHT/PNK/BRN)",
    "  NOISE.PRI / NP <0-16K> -> PRI OSC FM",
    "  NOISE.MOD / NM <0-16K> -> MOD OSC FM",
    "  NOISE.VOL / NV <0-16K> NOISE VOL",
    "",
    "# SOURCE LEVELS",
    "  PRI.VOL / PV <0-16383> PRI OSC VOL",
    "  MOD.VOL / MV <0-16383> MOD OSC VOL",
    "  PLV <0-16383>          PLAITS MAIN VOL",
    "  PAV <0-16383>          PLAITS AUX VOL",
    "",
    "# PLAITS SYNTH (16 ENGINES)",
    "  PL.ENG <0-15>  SELECT ENGINE",
    "  0=VA  1=FOLD  2=FM  3=GRAIN",
    "  4=HARM  5=WAVE  6=CHORD  7=VOWEL",
    "  8=CLOUD  9=NOISE  10=PARTICLE",
    "  11=STRING  12=MODAL  13=KICK",
    "  14=SNARE  15=HIHAT",
    "",
    "# PLAITS PARAMETERS",
    "  PL.FREQ / PLF <HZ> PITCH (20-20K)",
    "  PL.HARM / PLH <0-16383> HARMONICS",
    "  PL.TIMB / PLT <0-16383> TIMBRE",
    "  PL.MORPH / PLM <0-16383> MORPH",
    "  PL.DEC / PLD <0-16383> DECAY ENV",
    "  PL.LPG / PLL <0-16383> LOWPASS GATE",
    "  PLTR               TRIGGER ENGINE",
    "  RND.PL             RAND PLAITS",
    "",
    "# PLAITS SIGNAL FLOW",
    "  POST-VCA MIX, BYPASSES DISC/LOFI/",
    "  FILT/RING/RESO/VCA. HITS: COMP/",
    "  EQ/DLY/VERB. INTERNAL ENV + LPG.",
    "",
    "# SAMPLER LOADING",
    "  KIT <PATH>        LOAD KIT/FILE",
    "    DIR = KIT MODE (ONE-SHOT PER SLOT)",
    "    FILE = SLICE MODE (AUTO-SLICED)",
    "  KIT               LIST KITS (REPL ONLY)",
    "  KIT.LEN / KL      SLOTS COUNT (EXPR OK)",
    "  KIT.INFO          CURRENT KIT INFO",
    "  STR <N>           TRIGGER SLOT (EXPR OK)",
    "  STR               RE-TRIGGER CURRENT",
    "  EX: STR 5, STR RND 0 15, STR + A 1",
    "",
    "# SAMPLER SLICING",
    "  S.SLICE / SSLC <2-128> EQUAL SLICES",
    "    DIVIDES FILE INTO N EQUAL PARTS",
    "  S.ONSET / SONS [0-10] AUTO-DETECT",
    "    FINDS TRANSIENTS, 0=MANY 10=FEW",
    "    DEFAULT 5, FALLBACK: S.SLICE 16",
    "  S.ONSET.MIN / SOMIN <10-500> MIN MS",
    "    MINIMUM MS BETWEEN ONSETS (DEF 50)",
    "  EX: S.ONSET, S.ONSET 3, SOMIN 30",
    "",
    "# SAMPLER PLAYBACK (S.*)",
    "  S.RATE / SR <0-16383>  RATE (8K=1X)",
    "  S.PITCH / SPT <-24-24> PITCH (SEMI)",
    "  S.FINE / SFN <-100-100> FINE (CENTS)",
    "  S.DIR / SD <0|1>       DIR (0=FWD 1=REV)",
    "  S.LOOP / SL <0|1>      LOOP MODE",
    "  S.START / SST <0-16383> START OFFSET",
    "  S.LEN / SLE <0-16383>  LOOP LENGTH",
    "",
    "# SAMPLER ENVELOPE",
    "  S.ATK / SA <0-16383>   ATTACK MS",
    "  S.DEC / SDC <0-16383>  DECAY MS",
    "  S.REL / SRE <0-16383>  RELEASE MS",
    "  S.SUST / SSU <0|1>     SUSTAIN MODE",
    "    0 = ONE-SHOT (PERCUSSIVE)",
    "    1 = HOLD WHILE GATE HIGH",
    "",
    "# SAMPLER OUTPUT",
    "  VOL.SMP / VS <0-16383> VOLUME (MIXER)",
    "  PAN.SMP / PS <-8K-8K>  PAN (MIXER)",
    "  S.FX / SFX <0-2>       FX ROUTE",
    "    0=DRY 1=POST-FILT 2=POST-ALL",
    "",
    "# SAMPLER MODULATION",
    "  S.RATEMOD / SRM <0-16383> RATE MOD",
    "  S.PITCHMOD / SPM <0-16383> PITCH MOD",
    "",
    "# SAMPLER FX: FILTER (SF.F*)",
    "  SF.CUT / SFC <0-16383> CUTOFF",
    "  SF.RES / SFQ <0-16383> RESONANCE",
    "  SF.TYPE / SFT <0|1>    TYPE (LP/HP)",
    "",
    "# SAMPLER FX: DECIMATOR (SF.D*)",
    "  SF.BITS / SFB <1-24>   BIT DEPTH",
    "  SF.RATE / SFR <0-16383> SRR AMOUNT",
    "  SF.DECI / SFD <0-16383> DECI MIX",
    "",
    "# SAMPLER FX: GLITCH (SF.G*)",
    "  SF.PROB / SFP <0-16383> GLIT PROB",
    "  SF.MULT / SFM <0-16383> GLIT MULT",
    "  SF.GLIT / SFG <0-16383> GLIT MIX",
    "",
    "# SIGNAL FLOW",
    "  SAMPLE -> DECIMATOR -> GLITCH ->",
    "  FILTER -> MAIN MIX (VOL.SMP/PAN.SMP)",
    "  USE GLOBAL DLY/REV/CL FOR SPACE",
    "",
    "# STEREO DELAY",
    "  DLY.TIME / DT <MS>      TIME (1-2000)",
    "  DLY.FB / DF <0-16383>   FEEDBACK",
    "  DLY.LP / DLP <HZ>       LP FILT",
    "  DLY.WET / DW <0-16383>  WET MIX",
    "  DLY.SYN / DS <0-16383>  STEREO WID",
    "",
    "# DELAY ROUTING",
    "  DLY.MODE / D.MODE <0-2> BYP/INS/SND",
    "  DLY.TAIL / D.TAIL <0-2> CUT/RNG/FRZ",
    "",
    "# 3-BAND EQ",
    "  EQ.LOW / EL <-24-24>    LOW DB",
    "  EQ.MID / EM <-24-24>    MID DB",
    "  EQ.FRQ / EF <200-8000>  MID FREQ (HZ)",
    "  EQ.Q <0.1-10>           MID Q",
    "  EQ.HI / EH <-24-24>     HI DB",
    "",
    "# PLATE REVERB",
    "  REV.DEC / RV <0-16383>  REVERB DECAY",
    "  REV.PRE / RP <MS>       PRE-DLY",
    "  REV.DMP / RH <0-16383>  DAMP (HI)",
    "  REV.WET / RW <0-16383>  WET MIX",
    "",
    "# REVERB ROUTING",
    "  REV.MODE / R.MODE <0-2> BYP/INS/SND",
    "  REV.TAIL / R.TAIL <0-2> CUT/RNG/FRZ",
    "",
    "# METRO",
    "  M             SHOW INTERVAL",
    "  M <MS>        SET INTERVAL",
    "  M.BPM <BPM>   SET BPM",
    "  M.ACT <0|1>   START/STOP",
    "  M.SCRIPT <1-8>  SCRIPT FOR METRO",
    "",
    "# MIDI CLOCK SYNC",
    "  M.SYNC         SHOW SYNC MODE",
    "  M.SYNC <0|1>   SET SYNC MODE",
    "    0 = INTERNAL (DEFAULT)",
    "    1 = MIDI CLOCK (16TH NOTES)",
    "  MIDI.IN        LIST MIDI INPUTS",
    "  MIDI.IN <NAME> CONNECT TO DEVICE",
    "  NOTE: CONNECT FIRST, THEN M.SYNC 1",
    "  TRANSPORT: START/STOP FOLLOWS MIDI",
    "",
    "# MIDI CLOCK DIAGNOSTICS",
    "  MIDI.DIAG <0|1>  ON/OFF TIMING",
    "  MIDI.DIAG REPORT WRITE REPORT TO FILE",
    "  SC.DIAG <0|1>    ON/OFF SC TIMING",
    "  SC.DIAG REPORT   WRITE TO FILE",
    "  REPORTS: midi_timing_report.txt",
    "           sc_timing_report.txt",
    "",
    "# SCRIPTS",
    "  SCRIPT <1-8>  EXECUTE STORED SCRIPT",
    "",
    "# DELAYED EXECUTION",
    "  DEL <MS>: <CMD>     EXEC AFTER MS",
    "  DEL.CLR             CLR PENDING",
    "  DEL.X <N> <MS>: CMD REP N TIMES @ MS",
    "  DEL.R <N> <MS>: CMD NOW + REP N-1",
    "  MAX DELAY: 16000MS",
    "",
    "# PATTERNS (WORKING - P.N)",
    "  P.N           GET WORKING PATTERN",
    "  P.N <0-5>     SET WORKING PATTERN",
    "  P.L / P.L <N> GET/SET LENGTH",
    "  P.I / P.I <N> GET/SET INDEX",
    "  P.HERE        VALUE AT INDEX",
    "  P.NEXT        ADVANCE, GET VALUE",
    "  P.PREV        REVERSE, GET VALUE",
    "  P <I> / P <I> <V>  GET/SET AT INDEX",
    "",
    "# PATTERNS (EXPLICIT - PN)",
    "  PN.L <P> / PN.L <P> <N>  LENGTH",
    "  PN.I <P> / PN.I <P> <N>  INDEX",
    "  PN.HERE <P>              VALUE",
    "  PN.NEXT <P>              ADVANCE",
    "  PN.PREV <P>              REVERSE",
    "  PN <P> <I> / PN <P> <I> <V>",
    "",
    "# PATTERN MANIPULATION",
    "  P.PUSH <V>     PUSH VAL, SHIFT LEFT",
    "  P.POP          POP & RETURN LAST VAL",
    "  P.INS <I> <V>  INSERT VAL AT INDEX",
    "  P.RM <I>       REMOVE VAL AT INDEX",
    "  P.REV          REVERSE PATTERN",
    "  P.ROT <N>      ROTATE BY N STEPS",
    "  P.SHUF         SHUFFLE RANDOMLY",
    "  P.SORT         SORT ASCENDING",
    "  P.RND [MIN] [MAX]  RANDOMIZE VALUES",
    "  P.CLR          CLEAR (SET ALL TO 0)",
    "",
    "# PATTERN MATH",
    "  P.ADD <V>      ADD TO ALL VALUES",
    "  P.SUB <V>      SUBTRACT FROM ALL",
    "  P.MUL <V>      MULTIPLY ALL VALUES",
    "  P.DIV <V>      DIVIDE ALL VALUES",
    "  P.MOD <V>      MODULO ALL VALUES",
    "  P.SCALE <MIN> <MAX> SCALE TO NEW RANGE",
    "",
    "# PATTERN QUERIES",
    "  P.MIN          GET MINIMUM VALUE",
    "  P.MAX          GET MAXIMUM VALUE",
    "  P.SUM          GET SUM OF ALL",
    "  P.AVG          GET AVERAGE VALUE",
    "  P.FND <V>      FIND INDEX OF VAL (-1)",
    "",
    "  NOTE: PN.* VARIANTS TAKE PATTERN",
    "  NUMBER AS FIRST ARG (EX: PN.ADD 0 5)",
    "",
    "# SYSTEM COMMANDS",
    "  RST                RESET TO DEFAULTS",
    "    PF: 131 HZ (C3), MF: 262 HZ (C4)",
    "    PA: 0, FC: 10000 HZ",
    "    D.MODE: 2 (SEND), R.MODE: 2 (SEND)",
    "    CR: 1 (COMPRESSOR OFF)",
    "  LOAD.RST           SHOW RESET MODE",
    "  LOAD.RST <0|1> SET LOAD MODE",
    "    0 = PERSIST SYNTH PARAMS (DEFAULT)",
    "    1 = RESET ALL PARAMS BEFORE LOAD",
    "",
    "# AUDIO OUTPUT",
    "  AUDIO.OUT         LIST OUTPUT DEVICES",
    "  AUDIO.OUT <N>     SET OUTPUT BY NUMBER",
    "",
    "  DEVICE CHANGE RESTARTS AUDIO ENGINE",
    "  SAVED TO CONFIG FOR NEXT LAUNCH",
    "",
    "# EXPRESSIONS",
    "  ALL NUMERIC ARGS ACCEPT EXPRESSIONS:",
    "  PF N ADD A 7",
    "  DC MUL PN.NEXT 0 100",
    "  A RRND 0 127",
    "",
];
