pub mod help;
pub mod help_content;
pub mod help_categories;
pub mod help_synth;
pub mod help_effects;
pub mod help_system;
pub mod init;
pub mod live;
pub mod metro;
pub mod notes;
pub mod pattern;
pub mod scope;
pub mod script;
pub mod variables;

pub use help::{render_help_page, HELP_CATEGORIES, HELP_LINES};
pub use init::render_init_page;
pub use live::render_live_page;
pub use metro::render_metro_page;
pub use notes::render_notes_page;
pub use pattern::render_pattern_page;
pub use scope::render_scope_page;
pub use script::render_script_page;
pub use variables::render_variables_page;
